### ISSUE TITLE
Ingestion Tracker Query

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#10]
I am able to view how much Paraquet File size got ingested in Ingestion Tracker, is there a similar way to see how much Content has been ingested in a single Ingestion Job?

**Comment by kilam005** [comment]
We do have the blob count info recorded against the ingestion set.
We should be able to get this supplied in the UI.
This is current available in the report.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/5e7df543-62c6-410e-a355-0338b4289325)

This will be taken as an enhancment and done in next release.

**Comment by sowndaryameiyazhagan** [comment]
Enhancement : Added content count for ingestion set on summery page

**Comment by harsha-kotha** [comment]
Please add screenshot showing Count, currently added has N/A. Please add ingestion report along with it.

**Comment by Udhayanila8** [comment]
@harsha-kotha, For your reference. Added screenshots and report.

**Report**
[Content_count_report.pdf](https://github.com/P3-Core-Dev-Team/P3-Q-A/files/13042797/Content_count_report.pdf)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/b3f6d6f5-08c5-4cc5-b240-f76f00ec907a)

**Comment by harsha-kotha** [comment]
Thanks
