### ISSUE TITLE
ADS-App Info/Config - Incorrect Spelling- Effectv/Dell

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#101]
Spelling incorrect
ADS>Select an app>View App Info/Config
---

**To reproduce**
ADS>Select an app>View App Info/Config
---

**Screenshots**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/0ff9759b-b3c5-49b1-bf2d-432b84185fd9)

---

Additional context
Build no : ADS v
Client : Effectv

**Comment by yowanrajan** [comment]
Polices to Policies updated
<img width="1673" alt="Screenshot 2024-04-03 at 1 03 14 PM" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/43135572/0995fdf3-d573-4599-be40-7f1b2991a21b">

**Comment by kilam005** [comment]
in which version is this fix coming in
patch or regular?
please indicate
@prabhakaranUI  / @yowanrajan

**Comment by yowanrajan** [comment]
Available  this tag 2024.02.45353_RC6

**Comment by kilam005** [comment]
@raniangamuthu 
The required fix is provided with the latest release.
kindly check and provide closure

**Comment by raniangamuthu** [comment]
Verified the fix
