### ISSUE TITLE
Status Monitoring - Error during report download

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#103]
**Server:** 192.168.1.218

We are seeing the below error during the report download for 'Failed' and 'Stopped' status. It is not occurring for all the failed and stopped jobs and not particular to any job type but occurring for some jobs.

**Note:** We don't have all the job status to test and verify. Please verify for all the other job status as well

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/3989342f-51ba-4d18-8849-ad5723d41f15)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/a3e30b75-fe2b-4bcd-b526-d52929f8d4a6)

**Comment by Nadarajan-suyambu** [comment]
@suseela22 
we don't give the job status like stopped for job management triggered job, only gave option started state job only we can cancel.
someone  changed the status in database so this issue occured.
can you confirm who changed the status in database.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/103422990/3fdb10a1-1e17-482b-8d1e-9f57a6c5617b)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/103422990/63c64374-5aba-4cfd-bca7-b0a25bec5e51)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/103422990/7564d972-676f-4525-a81d-992af3cf8806)

**Comment by kilam005** [comment]
@suseela22 
It seems like DB was accessed by Arshad and manually adjusted.
This issue is invalid and cannot be proceeded.

We recommend not to access the DB and will not be able to suport if DB entries are comprimised.

**Comment by kilam005** [comment]
@suseela22 
Please check the comments and close the issue.

NOTE: This issue will be auto closed by April 20

**Comment by suseela22** [comment]
Noted. I will keep the team informed.

**Comment by suseela22** [comment]
Facing below error while downloading the failed job report

**Note:** Checked with the team. There are no changes made at the database from our side. so reopening the issue

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/bcb114be-335f-42a4-89bd-f3d34a2fdbb0)

**Comment by ClementJosh21** [comment]
@suseela22 We need more info regarding the above screenshot. Can you provide us with the step to reproduce, the login details and the id for which the error occurs.

**Comment by suseela22** [comment]
So far, issue is occurring during the report download for "Failed" and "Partially Completed" ingestion jobs.

**Note:** Report is getting downloaded for some failed and partially completed jobs also. It is occurring randomly. We were not sure about the root cause.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/faf7a7d9-0a7c-41cc-aa21-85bbc83925e6)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/172e9cef-024e-405b-b4ef-e65b9cc27299)

**Comment by kilam005** [comment]
@ClementJosh21  to check and confirm positive cases will be working as expected.
As step to reproduce are not avaialble, he will attempt to recreate.

**Comment by ClementJosh21** [comment]
@kilam005  We have identified a scenario to replicate this issue. Team is currently working on the fix.

**Comment by kilam005** [comment]
@ClementJosh21 
please describe the step for clarity and history keeping.

**Comment by ClementJosh21** [comment]
@kilam005 

`RCA`
This issue occurs when the job is dead in Livy, the logs were not properly updated.

`Fix Provided`  
On retrieving the logs we will check whether the file is available in the database if not we will check the Redis then update the logs to the db, and send the log to UI. If not present in Redis we will throw a proper error message stating 'Log file is not available.'.

**Comment by ClementJosh21** [comment]
@ElakkiyaBalasubramanian10 The fix is available in the tag ['2024.05.45423_RC4 '](https://github.com/P3-Core-Dev-Team/ADS_BE/releases/tag/2024.05.45423_RC4) deployed in test region.

 @Udhayanila8  Can you check and confirm?

**Comment by Udhayanila8** [comment]
**_Tested in 146 server 
Version: 2024.05.45423_RC4_**
I have checked a few jobs, didn't face any issues. Hence add a verified tag.
Able to download logs for some failed jobs
**Screenshots**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/cd8a5d9e-8dbc-4b18-b7ee-60a69321a11a)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f79a511d-2c55-4366-b870-291fcd605aad)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/8790e24a-1ce6-464b-8bc3-29e6ef86be02)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/1dd19b73-5518-4671-90ab-b56d40ffe4a9)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f8d5c69d-86ae-4deb-ab66-03d4ac083c97)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/69120e87-5a11-4db4-9390-8a66ee665eea)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/0d1b61fe-9b7d-4648-ac2f-9dc2e23a58f8)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/696fadc5-9b51-41b5-800c-a31ccbb5ceb1)

**Comment by kilam005** [comment]
Planned to roll out in the upcoming release

**Comment by maheswarareddyi** [comment]
@suseela22 This fix is available in ADS v2024.09.45542 on the 218 server in Chennai DC.
Please check and confirm the working and provide closure to this fix.

**Comment by maheswarareddyi** [comment]
@suseela22 Could you please provide the verification status of this fix? If no update is received from your end by October 21, 2024, the fix will be marked as closed.

**Comment by suseela22** [comment]
Working as expected
