### ISSUE TITLE
Junk characters while running script file

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#104]
**Server:** 192.168.1.218

While running the **start-ads-cli.sh** script to add custom template, junk characters were there as below.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/ab0db2d9-b42e-447c-b3b4-3c9e7b53e0fd)

**Comment by prashanthtk33** [comment]
@suseela22 , The jar file which was used is a backup one and was not properly built and deployed which is evident from the screenshot attached below. Kindly check after a proper build and deployment.
Class file from improper jar :
![MicrosoftTeams-image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/129496181/934d8d2a-f374-4401-9b58-fcd7a2edccdd)

**Comment by kilam005** [comment]
@rajesh-jeyaraman  / @ashoksri0 ,
This is a process miss during build generation.
CLI build pass was from a old build.
Please add this to the checklist and inform Devops team to take care

**Comment by divya-subburaj** [comment]
We are checking the gap in the build process .
Will check and update on this.

**Comment by divya-subburaj** [comment]
@kilam005 @rajesh-jeyaraman 192.168.1.218 server is deployed with tag 2024.01.45313_P1 on 11/3/2024. CLI module was not included in the build . This will be added in checklist for any existing or new deployment going forward. 
I have deployed the CLI module with tag 2024.01.45313_P1 in the server . With the latest version , the reported bug doesn't exist.
<img width="1287" alt="Screenshot 2024-04-18 at 9 59 34 AM" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/108411723/cb1423ac-cad2-40cb-a461-d2bbf3e52e8f">

**Comment by ClementJosh21** [comment]
@suseela22  Can you check and provide closure for this.

**Comment by suseela22** [comment]
Working as expected

**Comment by kilam005** [comment]
`Fix details`
Team has taken steps and checklist to use the correct code base for build generation
