### ISSUE TITLE
Search Result - Update option not working 

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#108]
When Link (Self, Nested, Conditional) column is added in search result, Update button is not working.

**Server:** 192.168.1.218
**Version:** 2024.03.45414

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/a1850817-282c-4524-89eb-e57b55ae4f10)

**Comment by kilam005** [comment]
The bug is acknowledged and is already notified previously by testing team. Corrective code is being worked on.

**Comment by harsha-kotha** [comment]
Issue is blocking hand-on activities of more than one team.
@P3IND0167 Fyi. These should be caught in testing.

**Comment by P3IND0167** [comment]
@harsha-kotha this issue is already logged in test server on April 29 by @Udhayanila8 and it is Retested in Test server & closed on May 15.

Adding Git issue link for reference Harsha [#2688](https://github.com/P3-Core-Dev-Team/ADS_BE/issues/2688)

**Comment by Udhayanila8** [comment]
@harsha-kotha, As already mentioned, the issue above has been resolved and closed in the test region. The patch release has been notified to the DevOps team and it is currently in progress.

**Comment by harsha-kotha** [comment]
@Udhayanila8 How was the release with issues deployed in 218 server? Such basic issues should not be approved. I will need a complete RCA across Teams on how such basic issue gets escaped and gets deployed.
@kilam005 Need your help on this to prevent such issues in future.

**Comment by Udhayanila8** [comment]
@harsha-kotha, FYI
**RCA**
Added mandatory column binding name for the links and all values. 

**Provided Fix**
removed java x validation annotation

****Note:**
_This issue was raised in order to resolve the following issue.
https://github.com/P3-Core-Dev-Team/P3-Q-A/issues/36_**

**Comment by ElakkiyaBalasubramanian10** [comment]
@Udhayanila8 To check in 218 server and have to proceed as per findings

**Comment by Udhayanila8** [comment]
Able to update the links.
Tested in 218 server.
Version: 2024.03.45414_P1
Basic search with link
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/db02b3d0-859e-42af-b1dc-904da494ec8a)
Able to update the link search
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/b3666e64-219c-4bc7-9006-3e6071406855)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/6befda5c-816e-4b95-bfeb-6161e6e75f0c)

**Comment by kilam005** [comment]
@suseela22 ,
please validate and provide your confirmation

@harsha-kotha,
The version was cerified with no major blocker and build was initially taken.
A fix (#36) made had an impact and seem like the test cases were not updated to validate combinations.

This was identified post release ([#2688](https://github.com/P3-Core-Dev-Team/ADS_BE/issues/2688) and team has fixed it by May 7th and it was in testing side. Post verification it had now been included as part of patch fix and deployed.

Both teams (dev ad testing) were advised to be more diligent to take care not to miss such critical issues both during development and during test cases execution.

**Comment by suseela22** [comment]
Working as expected

**Comment by kilam005** [comment]
`Fix details`
Code review and correction for length validation is updated only for the required cases

**Comment by suseela22** [comment]
Update option is not working when the "Message Text" box is added in Search form

**Version:** 2024.03.45414_P1

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/0991aae7-a80e-4dbd-9964-6213cc1a2035)

**Comment by harsha-kotha** [comment]
@P3IND0167 @Udhayanila8  Please check this scenario.

**Comment by kilam005** [comment]
@suseela22  / @harsha-kotha 
please check he original issue and provide closure.
The messageText form area issue is tracked in #110.

**Comment by kilam005** [comment]
@suseela22 do not add new issues to existing issues unless it is a direct byproduct of the ongoing issue.
New issues can be tracked as a different issue.
We will lose grip of the issue if the title is framed for one need and focus is diverted to another.

**Comment by suseela22** [comment]
Noted. I will close this issue
