### ISSUE TITLE
Ingestion of Content needs to be improvised

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#11]
Environment - Pulte New Dev ADS 3.1.7

https://archon-datastore.platform3solutions.com/pulte/dev/login

App : Recruiting Management
Search : Test_Assign
Table : CANDIDATE_BLOB

Structured Parquet Size : 9.67 MB
Unstructured Size : 12.33
Both above sizes are post ingestion.

12.33 GB ingestion took 6 Hours 29 Minutes.

[INGESTION_REPORT_07936521-b624-4559-b7b3-8befe66246b7_1690129087974.pdf](https://github.com/P3-Core-Dev-Team/P3-Q-A/files/12139118/INGESTION_REPORT_07936521-b624-4559-b7b3-8befe66246b7_1690129087974.pdf)

**Comment by ClementJosh21** [comment]
@harsha-kotha We have given two fixes for this.
1. The blob transfer to staging location was changed to move the files batch by batch
2. The blob transfer to warehouse directory is parallelized.

Ingestion report before fix:
[Job_name_1695983869315.pdf](https://github.com/P3-Core-Dev-Team/P3-Q-A/files/12928649/Job_name_1695983869315.pdf)

Ingestion report after fix: 
[Job_name_1695983888069.pdf](https://github.com/P3-Core-Dev-Team/P3-Q-A/files/12928650/Job_name_1695983888069.pdf)

**Comment by Udhayanila8** [comment]
Blob Ingestion performance was improvised. 

**In 3.1.5 - 224368 record content count** 

Ingestion time - **1 hour 26 mins**

**Before Report -** 

[Job_name_1695983869315 (3).pdf](https://github.com/P3-Core-Dev-Team/P3-Q-A/files/13041439/Job_name_1695983869315.3.pdf)


**In 3.1.7 - 224368 records content count**

Ingestion time - **12 mins 7 sec**

**After Report -** 

[Job_name_1695983888069 (2).pdf](https://github.com/P3-Core-Dev-Team/P3-Q-A/files/13041445/Job_name_1695983888069.2.pdf)

**Comment by harsha-kotha** [comment]
Please share the size of Blob added in both runs.

**Comment by ClementJosh21** [comment]
@harsha-kotha We tested with more that one blob and also attached the screenshot for the size & count of blobs ingested.

**Count:**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/76196584/5eb7fb0b-adf6-4a2d-a8ba-92453cae22be)

**Size:**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/76196584/f7d6a3db-ce6d-4c44-ab14-db4e05877849)

**Comment by harsha-kotha** [comment]
Thanks, we will do more rounds from our side. I see scope for improvement in performance on Ingestion.
