### ISSUE TITLE
ADS-Search Form - Add Message Text 

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#110]
Add Messagetext control in the search form and the search is not saved or updated until it is removed

**To Reproduce**
1. Create new search
2. Add MessageText > enter some field label
3. Click Update
4. No action happens
**Expected behavior**
Screen should get saved and take to the search list page

**Comment by KowsalyaChandran** [comment]
![Screenshot from 2024-06-06 11-17-25](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/83642018/28708c1b-ece0-41f3-9554-eb297cbf7e1d)
![Screenshot from 2024-06-06 11-18-00](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/83642018/4873a066-415a-4051-8569-a300fb478405)

**Comment by KowsalyaChandran** [comment]
This is fixed in Tag '2024.05.45423_RC4' which is deployed in rented-test region (146)  @ElakkiyaBalasubramanian10  @Udhayanila8 Pls check

**Comment by Udhayanila8** [comment]
**_Tested in 146 server.
Version: 2024.05.45423_RC4_**
Hence added the verified tag.

Able to save and update the message text column.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/2f03fdfb-19ec-4b64-877d-337f26991ed9)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/81615766-21e0-47ad-a010-84f0ae71f918)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/519dd52b-0a17-4d27-b385-59503af3ee95)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/db5d0929-133a-4e4c-95c5-353f4dcc4add)
Able to update the search
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/2ad8f16d-0e41-48e3-af74-098560d030ac)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/1a7f8180-42ab-47c6-81bc-ab39ffff591d)

**Comment by kilam005** [comment]
@KowsalyaChandran  / @selvakumarchandran  in which release will this get released?

**Comment by KowsalyaChandran** [comment]
@kilam005  This issue has been fixed and tested in tag '2024.05.45423_RC4'
Will be released in next release (release version name not yet confirmed)

**Comment by KowsalyaChandran** [comment]
RCA: Issue occurred due to bean validation for binding name 
Fix provided : Validation removed for message text

**Comment by maheswarareddyi** [comment]
@raniangamuthu This fix is available in ADS v2024.09.45542 on the 218 server in Chennai DC.
Please check and confirm the working and provide closure to this fix.

**Comment by maheswarareddyi** [comment]
@raniangamuthu Could you please provide the verification status of this fix? If no update is received from your end by October 21, 2024, the fix will be marked as closed.

**Comment by raniangamuthu** [comment]
verified
