### ISSUE TITLE
Group Search - Not Visible to End User

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#113]
End User Permission is not working for group search

**Version:** 2024.03.45414_P1

**Steps Taken:**

1. Two Enduser group has been created
2. Two Child Searches has been created inside the group search, each search with different Enduser Group enabled
3. Application Permission has been enabled for both enduser group.
5. Tried login with one of the enduser group, the search is not present.

**User group creation**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/4ff28c5e-225c-4352-a36b-8e1dc4d18d6e)

**Application Permission for user group enabled**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/bd1d1b90-65c8-4193-aec2-38c5aa6faed9)

**Search level permission**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/de3dc949-62e7-439b-9cfc-68ebe146bb13)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/37558ea2-5420-41d3-ab9c-3b64304b8a01)

**Searches are set to ready**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/b8546c69-ee8f-4257-8b9c-aba2458affe6)

**No searches are present in End User login**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/3dd8fd04-c114-445d-aa83-2149b587dbfd)

**Note**: So far it has been tested with group search and end user group. Will add comment once tested with other searches and groups as well.

**Comment by kilam005** [comment]
`RCA`
Group search was saved in draft mode prevent end users from seeing them.

`Fix Details`
The group seraches will be saved in Active mode.

Fix has been done and will be send for testing this EOW.

**Comment by kilam005** [comment]
Additional changes required. Expecting dev completion by EOW

**Comment by ClementJosh21** [comment]
@kilam005 We have started working on. Estimated time for completion is EOW

**Comment by prashanthtk33** [comment]
@Udhayanila8 
This issue is fixed and and released to the testing team in the latest version 
Can you test and confirm this?

**Comment by kilam005** [comment]
Testing has been started.
Projected ETA:  Today EOD.

**Comment by Udhayanila8** [comment]
**_Server: 192.168.56.146
Version: 2024.08.45507_RC5_**

Created group search and set active status in 2 searches, 1 search not set in active state
![image](https://github.com/user-attachments/assets/88220552-a5e0-496f-b6e3-082b3c92e9b2)
Give permission for 2 different end-user groups
![image](https://github.com/user-attachments/assets/7de78c87-b5b6-42a9-9ff0-cb9282377838)
![image](https://github.com/user-attachments/assets/be7655d3-0294-4277-951d-909582032856)
Login with those end-user groups and users, application available
![image](https://github.com/user-attachments/assets/709bc439-40c4-49ed-8901-3302c42b5db7)
![image](https://github.com/user-attachments/assets/9d8ad0c9-3459-48c1-9bb7-34edfe14e5b5)
Search available in the end user group 1
![image](https://github.com/user-attachments/assets/bdffb778-aa5c-409e-a4af-21043c4eb7e3)
![image](https://github.com/user-attachments/assets/fee66291-674b-4d1d-b43b-3ca91666f545)
Child search also visible
![image](https://github.com/user-attachments/assets/c5b6c7bc-c4d5-4e0e-a41b-e905cefdf727)
Result
![image](https://github.com/user-attachments/assets/cf5e13f8-0ef9-4324-9ab6-7e4a97c62a4d)

**Comment by maheswarareddyi** [comment]
@suseela22 This fix is available in ADS v2024.09.45542 on the 218 server in Chennai DC.
Please check and confirm the working and provide closure to this bug.

**Comment by maheswarareddyi** [comment]
@suseela22 Could you please provide the verification status of this fix? If no update is received from your end by October 21, 2024, the fix will be marked as closed.

**Comment by suseela22** [comment]
Working as expected
