### ISSUE TITLE
FR : ADS - Search - Displaying Blob File Name in Search Result

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#114]
During the unstructured column configuration, the option to bind the value from another column is required.

**Eg:** If the customer wants to display the attachment name in the link we are providing to View/Download, there should be an option to get value from other column (Attachment Name column)

**ADS Screenshot where the configuration is required:**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/6ccecea6-64b8-49aa-ac99-5c73a00ae829)

**Example screenshots from InfoArchive:**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/b7f4c972-e3cd-4935-adb3-73a1496289d2)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/7772b0b9-572a-4145-984a-a7a88741274c)

**Comment by maheswarareddyi** [comment]
While configuring the result set in the ADS system for the BLOB data type and column type view column or download column we have a provision to configure the display type for the blob filed as Show icon and Show Text in the current system. 
The following enhancement covers the expectation on the blob data type result field enhancement.

Enhancement implementation expectation: 

- Add a new dropdown value "Get from a column" to the display type field while configuring the blob data type field result set. 
- In Advanced, Report, and Cross app searches, if the user selects the value "Get from a column" from the listed values of the field Display type, display a mandatory input filed "Column binding name". The users must be able to add a column binding name from the metadata available in the search.
- In basic search, if the user selects the values "Get from a column" display a mandatory dropdown field "Select a column" and the system must list the columns from the search selected table only. The user must be able to select any one of the columns from the available columns.
- The system should consider the values available in the given field while displaying the blob field results.

@suseela22 Please review and provide your acceptance of the above-mentioned expectation.

**Comment by kilam005** [comment]
@suseela22 
please confirm

**Comment by suseela22** [comment]
@kilam005 @maheswarareddyi Fine with the approach.. Please continue

**Comment by prabhakaranUI** [comment]
@kilam005 Development in progress

**Comment by kilam005** [comment]
Demo was given and review comments were shared.
The team has fixed the identified issues during demo and is ready for testing team delivery.
Awaiting PR to include in delivery package

**Comment by prashanthtk33** [comment]
Refer to PR for screenshots: https://github.com/P3-Core-Dev-Team/ADS_BE/pull/2893

**Comment by maheswarareddyi** [comment]
Testing is in progress by @Udhayanila8.

**Comment by Udhayanila8** [comment]
**_Server: 192.168.56.146
Version: 2024.07.45502_RC3_**

Able to display the blob file name and map the name with another column.
**Basic search**
![image](https://github.com/user-attachments/assets/56b61879-860c-405e-9ae9-64462ea05f94)
![image](https://github.com/user-attachments/assets/bb09e87b-f292-490c-bdf7-bc3627fb38ab)
![image](https://github.com/user-attachments/assets/4f7af05e-3e94-4a8a-aecf-ca9620cabb32)
![image](https://github.com/user-attachments/assets/b47b3d5e-5c66-4fe6-aeb9-d25d1fe8892a)
For basic search
![image](https://github.com/user-attachments/assets/63426912-8bc9-4d88-9ee0-d60d1cb712ca)
![image](https://github.com/user-attachments/assets/b416533b-af64-40c4-9990-63cd76e22462)
![image](https://github.com/user-attachments/assets/3c1c8498-22d4-4d73-bf04-a6a5b7ac02e9)
**In advance search**
![image](https://github.com/user-attachments/assets/4a597cf7-658f-4734-8ae7-41dddb15a4e7)
![image](https://github.com/user-attachments/assets/f06c0480-94ff-4e50-b78d-8bdaaff09951)
![image](https://github.com/user-attachments/assets/6161fafd-df60-469f-abc9-53f07cc14d91)
Cross app search
![image](https://github.com/user-attachments/assets/b9df1409-74a0-4114-92b8-f3a97fcfa38e)
![image](https://github.com/user-attachments/assets/c5e61f27-446c-4836-bdd4-f0e1975a5c8b)

**Comment by Udhayanila8** [comment]
Server: 192.168.1.218
Version: 2024.09.45542
Blob ingestion failed with a following error message, Due to that unable to retest this issue
![Image](https://github.com/user-attachments/assets/e461e0f3-3ad3-4a40-bf32-ae41b3f9e883)

**Comment by maheswarareddyi** [comment]
@suseela22 This feature is available in ADS v2024.09.45542 on the 218 server in Chennai DC.
Please check and confirm the working and provide closure to this feature.

**Comment by maheswarareddyi** [comment]
@suseela22 Could you please provide the verification status of this feature? If no update is received from your end by October 21, 2024, the feature will be marked as closed.

**Comment by suseela22** [comment]
In Report Search, 'Display Type' is not required since it will run in background and fetch the original file name only.

![image](https://github.com/user-attachments/assets/4d9fd61e-00ba-4db0-8b83-ceee73ec0fc6)

![image](https://github.com/user-attachments/assets/8113b0e0-c350-43b8-8c02-1542d6a01417)

![image](https://github.com/user-attachments/assets/bd552644-dfd2-4e8e-9d7c-5aa59be12ef0)

**Comment by kilam005** [comment]
please check for all cases and inform in one go @suseela22

**Comment by suseela22** [comment]
@kilam005 This has been verified with all 4 option of 'Display Type' for Basic, Advance and Cross App Search and exported , which is working as expected

**Comment by kilam005** [comment]
@suseela22 
in order to prevent file overwrite (in case if same name occurs) we add a randomized character in the front.

**Comment by ClementJosh21** [comment]
@kilam005 / @maheswarareddyi 
Need to work on this to implement the functionality in the export. To be completed by EOW.

**Comment by kilam005** [comment]
Fix made will be included in next build and will be shared for testing.

**Comment by kilam005** [comment]
Fix to be made available in 2024.09.45542_P7

**Comment by Udhayanila8** [comment]
**_Server: https://dev-support.platform3solutions.com/
Version: 2024.09.45542_P7_**

Still, report search shows the display type in the blob column.
Basic search
![image](https://github.com/user-attachments/assets/209386b8-6c12-4972-9b17-ee98615d89ba)
Get from column
![image](https://github.com/user-attachments/assets/c5c854ae-4d51-4e0c-a228-4b294c1a8799)
Original file name
![image](https://github.com/user-attachments/assets/73368049-5452-4899-ad81-98f56e8b2efa)
show icon
![image](https://github.com/user-attachments/assets/60393817-5ebe-4ac6-a42f-ad8b79e8a1f0)
Text value
![image](https://github.com/user-attachments/assets/db93e4f7-1920-4bd0-a121-880e8c6b4185)
Advance Search
![image](https://github.com/user-attachments/assets/425ff673-c68b-47f2-84b0-de9034c58757)
![image](https://github.com/user-attachments/assets/20ebbba3-aa5f-49f6-b6ad-ae7165b9dfec)
![image](https://github.com/user-attachments/assets/2c814603-9ffb-44a7-998b-457a4e8a9b51)
![image](https://github.com/user-attachments/assets/3879c924-c9fa-4bb2-823d-7ac988996ffd)
![image](https://github.com/user-attachments/assets/5da3b680-deaf-4926-9df6-da38f760c093)

Report search still shows the display type
![image](https://github.com/user-attachments/assets/8fc5f98e-e22f-4643-814d-4418c04926e8)

**Comment by Udhayanila8** [comment]
**_Server: https://dev-support.platform3solutions.com/
Version: 2024.09.45542_P7_**

Show icon removed in the display type for report search,
**Report search**
![image](https://github.com/user-attachments/assets/56fd4305-9e75-474e-9857-5838a9aaf9a9)
Show text
![image](https://github.com/user-attachments/assets/6509862f-be27-443c-a6f0-b6dbf0e3bc6c)
Original file
![image](https://github.com/user-attachments/assets/99c23dfd-5f96-474d-b1e3-7d0c84ce30e9)
Show column
![image](https://github.com/user-attachments/assets/fc481f94-7806-4139-9204-d984087d86ef)

After exporting results in advance search
![image](https://github.com/user-attachments/assets/0bc80742-5baa-4ebd-a1b1-7c33d15d778d)
![image](https://github.com/user-attachments/assets/051e5f83-520d-4679-9102-d85b01d9c4c1)

**Comment by kilam005** [comment]
@suseela22 
Reminder to check and provide closure

**Comment by ThulasiP3** [comment]
Verified and can be closed
