### ISSUE TITLE
ADS-Search Form - Combo box values getting truncated in display- Fairview

### ISSUE THREAD

**Issue by sumitraRaja** [P3-Core-Dev-Team/P3-Q-A#115]
**Describe the bug**
 When there is a Label like "HealthLine,LLC " the list label gets truncated in the display of a combo box

**To Reproduce**
1. Create a combo box 
2. Give Label and value as Healthline, LLC [ tried within single quote and double quote as well 'HealthLine,LLC' ]
3. Save the form
4. Click on the combo box

**Expected behavior**
The label should be as HealthLine, LLC if provided withing single quote
**Screenshots**
 
![Combo box issue](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18064684/feab1263-d2ab-4245-b4b9-9f3c57c94760)

 

**Additional context**
Build no : 2024.03.45414_P1
Region :
Client : Fairview

**Comment by prabhakaranUI** [comment]
Development completed, Now the user can use a comma inside a double quote. **eg: "HealthLine,LLC ".**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/0c991c02-e83e-4e9b-8c14-da9950552926)

**Comment by kilam005** [comment]
@prabhakaranUI show a demo to @sumitraRaja and get the confirmation before packing to release.

**Comment by sumitraRaja** [comment]
Working fine as expected
