### ISSUE TITLE
ADS - Search -Ctrl F on search - Generic

### ISSUE THREAD

**Issue by saumyaguptaa** [P3-Core-Dev-Team/P3-Q-A#116]
**Describe the bug**
When I do Ctrl F on search query, the badge covers the query area
**To Reproduce**
1. Go to query definition area of any search, make sure the query is big enough.
2. Click on Ctrl F
3. In the current screenshot, I have used Peoplesoft_Finance application. Search Name - AMAS2000-Cost Activity Detail Report https://ads.platform3solutions.com/

**Expected behavior**
When done Ctrl F, the search badge should not overlap with the search query and hide it.

**Screenshots**
<img width="1680" alt="image" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/26349192/e82dcc01-153b-4461-bfaa-d3e3890135d4">

**Additional context**
Build no : All
Region : All
Client : Generic

**Comment by kilam005** [comment]
this is the behaviour of the component.
Please suggest an alternate editor that best suits to resolve this.

**Comment by kilam005** [comment]
@saumyaguptaa awaiting response

**Comment by kilam005** [comment]
Current suggestion
- leasve first three lines blank
- Use line breaks better
- close and open find and replace popup if needed

This issue will be ignored as there is no reasonable development to do and it is accomodatable by any user.

**Comment by kilam005** [comment]
@saumyaguptaa 
This issue will be auto closed on 5th July if no valid response is received.

**Comment by kilam005** [comment]
Auto Closing issue as no response is received.
