### ISSUE TITLE
ADS-Search Result-Customize column export

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#117]
**Describe the bug**
If specific columns are selected from the customize column option and exported, it exports all the columns which is configured as exportable, which is not correct.

**To Reproduce**
1. Go to Search Result of any search where all the columns are configured as exportable 
2. Click on Configure Columns -> Customize
3. Select some of the columns
4. Export the result

**Expected behavior**
The exported file should have only the columns which are selected in the customize columns.

**Screenshots**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/892760d2-68ae-40bf-94a4-fb09f81b0d60)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/4fdd896a-2b75-4c23-802d-7ebc2558ca77)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/ce3bb64f-86a3-4dc4-9de2-6775c3ff828d)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/c0690f93-a476-4782-86c9-e959e80efccd)

**Additional context**
Build no : 2024.03.45414_P1
Region : http://192.168.1.218:4081/
Client :

**Comment by kilam005** [comment]
@suseela22 

Export works based on export configuration set during search creation. The configure column -> customise option is for ui view only. 

This is an invalid bug.

**Comment by suseela22** [comment]
@kilam005 Can we take it as an enhancement? Is it doable? If so we will discuss on the use case

**Comment by kilam005** [comment]
@suseela22 what should we do about the export configuration option then?
it will be conflicting.

Also Config column is only for table main column. They do not affect expanded results. 
It will end up be more confusing.

I will set up some time to understand the need. Lets decide post that.

**Comment by suseela22** [comment]
@kilam005 Sure

**Comment by kilam005** [comment]
@suseela22 
As per last dicussion you were supposed to get back on this?
is there any update ?

**Comment by maheswarareddyi** [comment]
@suseela22  As discussed, this issue can be closed and you can create a new request once you are ready with the requirements.
