### ISSUE TITLE
Ingestion status not updated properly - Fugro

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#118]
Ingestion is failed due to the datatype conversion issue but the status is in '**In-Progress**' state for long hours

![image](https://github.com/user-attachments/assets/2fa4a2e8-36b9-4d68-b3c0-3ee9b1062ed7)

![image](https://github.com/user-attachments/assets/557b6965-94f3-4a71-a7c4-4cc648eb0216)

**Note:** Ingestion path is from S3 bucket

**Additional context**
Build no : 2024.03.45414_P2
Region : [Fugro-Dev](https://fugro-dev.platform3solutions.com/)
Client : Fugro

**Comment by Nadarajan-suyambu** [comment]
RCA: The ingestion job failed on the EMR serverless side. EMR side failed ingestion job status not handled

FixGiven: Emr side failed jobs status captured using the scheduler and same status update in ads with captured message

Screenshots: 
![image](https://github.com/user-attachments/assets/29ca3730-711a-46f2-9917-127d697bcd3a)
![image](https://github.com/user-attachments/assets/4d7e2d4c-daa0-498f-b49f-3d97a7a4cdec)
![image](https://github.com/user-attachments/assets/12779f7e-9d3c-40b0-b234-ef52002006e0)

**Comment by kilam005** [comment]
@Nadarajan-suyambu is this added in build and released or yet to release?

**Comment by kilam005** [comment]
@Udhayanila8 : This is ready for testimg.
Do the needful

**Comment by Udhayanila8** [comment]
**_Server: 192.168.56.146
Version: 2024.08.45507_RC6_**
Trigger ingestion using s3- bucket
![image](https://github.com/user-attachments/assets/e49b1e07-2ceb-41c3-b14c-f0be4b063d8d)
![image](https://github.com/user-attachments/assets/bda06801-d327-4630-a1d4-f9afe3e2722d)
![image](https://github.com/user-attachments/assets/f2a5c56d-d770-48cc-b399-8f1a676c9167)
Ingestion succeeded.
![image](https://github.com/user-attachments/assets/b8fa4664-289c-4102-9745-0ea95ba0d4b7)

**Comment by maheswarareddyi** [comment]
@suseela22  Could you please provide the verification status of this fix? If no update is received from your end by October 21, 2024, the fix will be marked as closed.

**Comment by maheswarareddyi** [comment]
Closing this issue as no concerns were raised within the provided timeline and confirmation was received from @suseela22 via chat. @Udhayanila8 verified this issue in both testing (146) and implementation (218) servers and confirmed that the provided fix is working as expected.

![image](https://github.com/user-attachments/assets/7129f332-2cd3-4210-b5c1-891a83bee16a)
