### ISSUE TITLE
Ingestion failure - Datatype conversion issue - Fugro

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#119]
2 parallel ingestion jobs has been triggered with the data size of 8.5 GB and 1.5 GB each. The log stated the datatype conversion issue. So the metadata has been updated with "**string**" datatype for all the columns and uploaded again. Same error occurred after the datatype change also. 

**Note:** Ingestion path is from S3 bucket

![image](https://github.com/user-attachments/assets/b8b1e45d-d8d6-4405-b442-0697ff679d0e)

![image](https://github.com/user-attachments/assets/91719dd9-fbb0-499d-888a-4af8750a3771)

**Additional context**
Build no : 2024.03.45414_P2
Region : [Fugro-Dev](https://fugro-dev.platform3solutions.com/)
Client : Fugro

**Comment by Nadarajan-suyambu** [comment]
RCA: During the s3 profile ingestion calculating the free space using the file size here the data type varied (Instead of long it's in Integer) so the issue occurred.
Fix Given: JPA return type changed (instead of Integer changed to Long)

@suseela22 
Issue addressed. Now the patch release (2024.08.45507_P1) deployed in the Fugro region
Screen Shots
![image](https://github.com/user-attachments/assets/f9ec8d8e-7e76-445a-b343-ccf9bfdf8c23)
![image](https://github.com/user-attachments/assets/7c7da75d-f511-4d40-b199-1c1302d53538)

**Comment by kilam005** [comment]
@Udhayanila8 : this is read for testing.
Please do the needful.

**Comment by Udhayanila8** [comment]
Created group search and set active status in 2 searches, 1 search not set in active state
![image](https://github.com/user-attachments/assets/88220552-a5e0-496f-b6e3-082b3c92e9b2)
Give permission for 2 different end-user groups
![image](https://github.com/user-attachments/assets/7de78c87-b5b6-42a9-9ff0-cb9282377838)
![image](https://github.com/user-attachments/assets/be7655d3-0294-4277-951d-909582032856)
Login with those end-user groups and users, application available
![image](https://github.com/user-attachments/assets/709bc439-40c4-49ed-8901-3302c42b5db7)
![image](https://github.com/user-attachments/assets/9d8ad0c9-3459-48c1-9bb7-34edfe14e5b5)
Search available in the end user group 1
![image](https://github.com/user-attachments/assets/bdffb778-aa5c-409e-a4af-21043c4eb7e3)
![image](https://github.com/user-attachments/assets/fee66291-674b-4d1d-b43b-3ca91666f545)
Child search also visible
![image](https://github.com/user-attachments/assets/c5b6c7bc-c4d5-4e0e-a41b-e905cefdf727)
Result
![image](https://github.com/user-attachments/assets/cf5e13f8-0ef9-4324-9ab6-7e4a97c62a4d)

**Comment by Udhayanila8** [comment]
**_Server: 192.168.56.146
Version: 2024.08.45507_RC6_**
Triggered around 5 GB data
![image](https://github.com/user-attachments/assets/0aa763f1-bbd3-4026-ab60-628d9e3aa6e2)
Trigger ingestion for that, using s3 bucket
![image](https://github.com/user-attachments/assets/fc0fedbf-95cf-4c87-af36-7c75ddf778df)
![image](https://github.com/user-attachments/assets/10c41551-6efe-49d1-bcb5-44da687b6177)
![image](https://github.com/user-attachments/assets/70eae5a2-43e5-4576-a137-7312ee18faf6)
Ingestion succeeded.
![image](https://github.com/user-attachments/assets/1a353aa6-6932-4349-a33c-b9351a537ed6)
![image](https://github.com/user-attachments/assets/19d86e84-91e0-4ae4-9218-a5a39092675b)
![image](https://github.com/user-attachments/assets/7a3f4ba0-b4b4-4911-8e31-e55422c5f94c)
![image](https://github.com/user-attachments/assets/082c579f-3433-49bb-84c3-1f326424be8b)

**Comment by maheswarareddyi** [comment]
@suseela22 Could you please provide the verification status of this fix? If no update is received from your end by October 21, 2024, the fix will be marked as closed.

**Comment by maheswarareddyi** [comment]
Closing this issue as no concerns were raised within the provided timeline and confirmation was received from @suseela22 via chat. @Udhayanila8 verified this issue in both testing (146) and implementation (218) servers and confirmed that the provided fix is working as expected.

![image](https://github.com/user-attachments/assets/419e23a3-ff52-4d2c-9d46-5ccc9df68dff)
