### ISSUE TITLE
ADS - Metadata - Table Columns in Graph view - Export

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#123]
**Describe the bug**
Export the graph view is not the same as we see in ADS screen

**To Reproduce**
1. Go to any application > Metadata
2. Click on Schema > Tables > columns > graph view
3. Export the graph view as SVG
4. Compare the exported file
**Expected behavior**
It should be same as what we see in ADS. Here the table names and column names are printed twice in the exported file.

**Screenshots**
 
![image](https://github.com/user-attachments/assets/ec1b8225-f094-4694-ac0f-bad6d91a03d5)

**Additional context**
Version: 2024.02.45353_RC6
http://192.168.56.163:4081/

**Comment by maheswarareddyi** [comment]
The fix is in progress and the expected ETA is Sep 06, 2024.

**Comment by yowanrajan** [comment]
Issue has been completed 
Version:  2024.09.45542_RC1

<img width="1479" alt="Screenshot 2024-09-09 at 7 20 07 PM" src="https://github.com/user-attachments/assets/468f7a7b-ffd9-456e-b096-b6689dca9ce2">

**Comment by kilam005** [comment]
@yowanrajan what is the RCA?
is it passable for testing team?

**Comment by prabhakaranUI** [comment]
@kilam005 
`RCA` 
The internal JS function was not working while creating SVG. so the tooltip appeared a second time.

`Fix Provided`
We remove the tooltip while creating an SVG

**Comment by Udhayanila8** [comment]
**_Server: 192.168.56.146
Version: 2024.09.45542_RC1_**

Table level column graph view
![image](https://github.com/user-attachments/assets/fabe29fb-7c6e-4e57-ab1b-8104f6be4eca)
Downloaded SVG file.
![image](https://github.com/user-attachments/assets/87f9a8ce-7ffc-45f0-8f7a-cec43b7b0981)

**Comment by maheswarareddyi** [comment]
@raniangamuthu Fix for this issue is available in ADS v2024.09.45542 on the 218 server in Chennai DC.
Please check and confirm the working and provide closure to this issue.

**Comment by maheswarareddyi** [comment]
@raniangamuthu Could you please provide the verification status of this fix? If no update is received from your end by October 21, 2024, the fix will be marked as closed.

**Comment by raniangamuthu** [comment]
verified
