### ISSUE TITLE
ADS - Search - Failure on Unstructured Data retrieval - Neste

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#125]
**Describe the bug**
Ingestion was successfully completed in s3 storage. While viewing the blob data from the search result, the error occurs as "the file not found"

**Screenshots**

![image](https://github.com/user-attachments/assets/0400f150-debf-4931-9a66-46d08862f06e)

**Additional context**
Build no : 2024.08.45507_P2
Region : https://neste-dev.platform3solutions.com/login
Client : Neste

**Comment by ashoksri0** [comment]
Deployment Issues happened with the storage tier configuration now its resolved and working now

**Comment by suseela22** [comment]
Tested in Neste region. Working as expected
