### ISSUE TITLE
ADS - Rollback - Job has no progress - Neste

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#127]
**Describe the bug**
Rollback job was triggered for the job which has 62 tables and 5 GB data size. Job is in scheduled state for more than an hour and no progress.

**Screenshots**
![image](https://github.com/user-attachments/assets/e5184faa-888d-4a3e-bc42-98c264d4d1bc)

![image](https://github.com/user-attachments/assets/4cae6d5c-4bc8-47a8-8bca-d31a40873b6b)

**Additional context**
Build no : 2024.08.45507_P4
Region : https://neste-dev.platform3solutions.com/
Client : Neste

**Comment by suseela22** [comment]
**Additional info:**

When rollback is initialized for the first time the error showed as "unable to establish connectivity". The second time also it throwed the same error and doesn't indicated whether the job has been scheduled or not. The third time when i triggered it showed "rollback exist already". When checked into the ingestion session it shows two session as below.

![image](https://github.com/user-attachments/assets/1312152b-23e6-4148-b899-92c2f3309680)

**Comment by ashoksri0** [comment]
We have identified the issue and restated the services to kill the rollback jobs as workaround. the actual issue is if we do rollback for a small number of tables, it is working, but for large numbers it fails. we will provide the code fix for larger table sizes as a patch. @P3IND0167 have it in your test case for testing

**Comment by harsha-kotha** [comment]
Larger Table size is not clear, meaning tables with large volumes of data or number of table is high? If we say high number of tables what is the limit? when is it failing? Will the fix provided will cater and work without any issue for DBs that has let's say 100000 of tables?

**Comment by kilam005** [comment]
@ashoksri0  / @Nadarajan-suyambu please provide the updated asked by hasha and provide details on the issue fix plan.

**Comment by maheswarareddyi** [comment]
Planned to deliver this fix to the testing team by this EOW

**Comment by Nadarajan-suyambu** [comment]
Root Cause Analysis (RCA): Previously, during a rollback involving a large number of tables (e.g., 140 tables), we were sending a request with a payload containing 140 objects, which made the payload too large. As a result, Spark clusters were rejecting the rollback job. Now, instead of sending individual objects, we are sending the current base path of all tables, allowing support for significantly larger numbers, such as 100,000.

**Comment by ashoksri0** [comment]
@harsha-kotha This issue can be reproduced when rolling back more than 60 tables. The failure occurs because ADS sends the table paths as an array. As the number of tables increases, the array size also grows, leading AWS EMR to decline the request due to its large size. We have resolved this by sending the root path instead of all individual table paths.

**Comment by kilam005** [comment]
This issue fix is avaialble in Tag '2024.10.45564_RC3'.
This is current passed on to testing team for verification

**Comment by Udhayanila8** [comment]
**_Server: 192.168.56.146
Module: Rollback
Version: 2024.10.45564_RC3_**

Rollback completed successfully for 138 tables. 

Created application with 138 tables
![Image](https://github.com/user-attachments/assets/71255fad-2ebd-4421-b42b-b09bd7e8c2d4)
Triggered ingestion for that
![Image](https://github.com/user-attachments/assets/5b382ed3-2133-443b-8e11-53dfc07e328b)
Ingestion completed for 138 tables in 1 hr 30 mins
![Image](https://github.com/user-attachments/assets/6f64eb02-84fa-47f1-85ad-dead9d6bfcee)
Triggered Rollback for 138 tables
![Image](https://github.com/user-attachments/assets/c4dbec31-4ba0-418a-806b-3b83a2beef82)
![Image](https://github.com/user-attachments/assets/4fd045e0-4545-4e86-b96d-fb0482bbfb5c)
Rollback completed for all 138 tables in 30 mins
![Image](https://github.com/user-attachments/assets/41f9680d-d0ad-4d6b-972f-d2f9434b3cda)
Status also updated properly.
![Image](https://github.com/user-attachments/assets/e44969ce-b471-47c2-b564-88e552575f62)
Record count also updated.
![Image](https://github.com/user-attachments/assets/19ba2ad7-1e2d-4029-b247-4796a75f4ee3)
Data tab
![Image](https://github.com/user-attachments/assets/4a014c4d-d7a9-4b30-bdb0-55669013fb9d)

**Comment by Udhayanila8** [comment]
**_Server: http://192.168.1.251:4081/
Version: 2024.09.45542_RC1_**

Trigger ingestion for 138 tables
![image](https://github.com/user-attachments/assets/4cdc5ca2-35d3-48d8-8bea-15333178fdcb)
Ingestion completed successfully
![image](https://github.com/user-attachments/assets/1f5941cc-fbe0-41c9-948c-5063b2687bd9)
Triggered rollback for the 138 tables,
![image](https://github.com/user-attachments/assets/f3e91bee-5ac2-41cb-97e7-986c5824dd51)
In preparing status,
![image](https://github.com/user-attachments/assets/fb9f39ef-b7fe-4dfa-b057-c2f06a080559)
One rollback session failed, again triggering rollback for the same session
![image](https://github.com/user-attachments/assets/b1058891-d311-4bdf-a61e-412b70388344)
![image](https://github.com/user-attachments/assets/7d4aa32f-73b2-4f49-89f3-66a837ecd140)
Rollback complete 
![image](https://github.com/user-attachments/assets/100ea124-3e86-44ac-87f9-f24a76c7fbff)
Table counts added.
![image](https://github.com/user-attachments/assets/6ff69862-584e-4630-a132-73a1e692a233)

**Comment by suseela22** [comment]
**Case 1:**
Rollback has been scheduled and completed successfully for 78 tables but the status is not getting updated.

![image](https://github.com/user-attachments/assets/871393c8-05ab-4e2e-b1d6-94f39dcc3253)

**Case 2:**
Rollback job has been scheduled for one table. It is in ready state for long time and not picked up. so retention was applied to that table and disposed.

![image](https://github.com/user-attachments/assets/a7a9e77d-5643-4b5d-8b2b-c8d2a29fc385)

**Comment by maheswarareddyi** [comment]
@dinesh-p3  to Validate the fixes with @suseela22  and deliver the fixes to @Udhayanila8 for testing.

**Comment by kilam005** [comment]
Case 2 is reproduced and the code issue was identified.
@dinesh-p3  please add more details on the issue and code update made. Include PR links for clarity or reference issue in PRs.

**Comment by dinesh-p3** [comment]
for the case 2: 
 `RCA`

The rollback job was not picked due to the inactive transaction in the async method

`Fix provided`

Added the required transaction to the method

This fix will be available in the release 24.09.xxxx_P6.

**Comment by kilam005** [comment]
This issue has been verifed by testing team

**Comment by Udhayanila8** [comment]
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P6_**

Rollback job has been completed.
![image](https://github.com/user-attachments/assets/3740cc3e-3080-4699-a779-b91f60580ccd)
Rollback in progress
![image](https://github.com/user-attachments/assets/3a9de987-f7e7-4c96-b48d-6c968488761e)
![image](https://github.com/user-attachments/assets/3d52106c-f4b1-47cf-8a4e-5642784286b6)
![image](https://github.com/user-attachments/assets/a161297c-20cf-44b0-8212-759d6cafc2ba)
Triggered multiple rollback session
![image](https://github.com/user-attachments/assets/94eddab9-64c0-459b-b31d-5136fbc98aed)
Triggered rollback for 50 files
![image](https://github.com/user-attachments/assets/0afabc8d-5a94-4b03-a394-f2358c5b0080)
All rollback job has been completed
![image](https://github.com/user-attachments/assets/04dcf196-54dc-448f-99e3-1f5c4d65a04a)

**Comment by suseela22** [comment]
Working as expected
