### ISSUE TITLE
ADS and P360-Screen- Expectation is to replace </BR> tags with new line for a string-Fairview

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#128]
**Describe the bug**
For a string with multiple <BR> tags, The Expectation is to replace </BR> tags with new line. But unable to add new line(escape sequence) in ADS  and P360

**To Reproduce**
1.Create a search with search result column that has multiple <BR> .(refer Attachments)
2.Run the query. Able to see <Br> tags removed. But the new line isn't seen 
Attachments : 
[screenshots.docx](https://github.com/user-attachments/files/17123626/screenshots.docx)

**Expected behavior**
The Expectation is to replace </BR> tags with new line

**Screenshots**
Refer attachments

**Additional context**
Build no :
Region :
Client :

**Comment by P3IND0167** [comment]
Verified in Test server adding screenshots

![image](https://github.com/user-attachments/assets/f0381f10-a87f-4cc6-976f-423f5ebd8bba)
![image](https://github.com/user-attachments/assets/29982002-949b-4b12-aa3d-6d8bfad6b588)
![image](https://github.com/user-attachments/assets/794e472a-26eb-4ee1-8a42-f143fcfae326)

**Comment by kilam005** [comment]
This issue is no longer associated with P360.
This was wokring fine from the start. 
No code changes were made for this.
So removing association with p360.

**Comment by kilam005** [comment]
Code fixes are ready.
Internal testing to be done. and PR would be raised by EOW

**Comment by prabhakaranUI** [comment]
Fix ready and deployed in test region, 1925.
Version: 2024.10.45564_RC1
![image](https://github.com/user-attachments/assets/e62c6061-296f-4bc9-9f51-aae547e40f7b)

**Comment by kilam005** [comment]
Fix has been provided by FE teams.
Awaiting deployment to pass this to testing team.
ETA: today

**Comment by Udhayanila8** [comment]
Server: 192.168.56.146
Version: 2024.10.45564_RC4

The tags are replaced with the new line.
![image](https://github.com/user-attachments/assets/a03b2c9c-2df4-485f-86a7-8abde8d59b2c)
after performing the search /br removed and a new line has been added
![image](https://github.com/user-attachments/assets/065a8ed0-4bd9-4e35-8d3b-eb2b9525c097)

**Comment by kilam005** [comment]
Release is belived to be provided but missed to track.
@prabhakaranUI to check with @ThulasiP3  for confirmation of the fix in Fairview region.

**Comment by kilam005** [comment]
@ThulasiP3 
Please check and provide yoyr closure

**Comment by ThulasiP3** [comment]
Verified IN Faireview..Closing the issue
