### ISSUE TITLE
ADS- Sorting is not working - Neste

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#135]
**Describe the bug**

After fetching the search result, the sort is executed but it shows "No Data available"

**Screenshots**

![image](https://github.com/user-attachments/assets/656166ee-f0dd-4ef3-a93b-33e61dccbbcb)

![image](https://github.com/user-attachments/assets/01769d05-2c8f-4963-937e-baaac4422e10)

**Additional context**
Build no : 2024.09.45542
Region : https://neste-dev.platform3solutions.com/
Client : Neste

**Comment by Nadarajan-suyambu** [comment]
RCA: Data type mismatch validation was missed for the serverless region.
Fix: Data type mismatch validation implemented

**Comment by Nadarajan-suyambu** [comment]
@Udhayanila8 
This issue was resolved in Tag '2024.10.45564_RC3'.
Check this issue in the serverless region.

**Comment by Udhayanila8** [comment]
Serverless region https://testregion.platform3solutions.com/
Version: **2024.10.45564_RC3**

For datatype mismatch, while applying sort, warning icon with tooltip message "mismatch in datatype, can't sort" is displayed in result screen. And sorting is working for correct datatypes.
Working as expected, added verified label.
Screenshots:
![image](https://github.com/user-attachments/assets/3800905d-7f69-49ed-8f01-dc178b566040)
![image](https://github.com/user-attachments/assets/a75739be-960b-4558-b862-0b90eb62baa2)
![image](https://github.com/user-attachments/assets/95d115e1-ac2e-468b-a5ed-973d9c814b3c)
![image](https://github.com/user-attachments/assets/c13af74f-9cdb-4043-9ea8-59e04dc38016)
![image](https://github.com/user-attachments/assets/6c400b2c-8058-4fd5-98c2-bd871a63e558)
![image](https://github.com/user-attachments/assets/d78ec218-039f-4467-9bcb-f68d454caaae)

**Comment by Nadarajan-suyambu** [comment]
@maheswarareddyi This issue was fixed and Deployed in the Neste region with tag(2024.09.45542_p3)

**Comment by suseela22** [comment]
Working with the build **2024.09.45542_P3** deployed in Neste environment.
