### ISSUE TITLE
ADS - Screens are not displayed on Group Search to create nested link - Neste

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#137]
**Describe the bug**

Inside a group search created a new group search . In that new group search, created a Main screen and a Nested Screen. Screens are not displayed in the dropdown while giving nested link from main screen

**Screenshots**
 
![image](https://github.com/user-attachments/assets/327dc879-a1af-4567-bd53-77c5a635d13b)

![image](https://github.com/user-attachments/assets/1c0bed1a-2621-4fc5-9d7b-5c305e51aed4)

![image](https://github.com/user-attachments/assets/ad2ae5c3-a967-4b0b-9b66-525e4d756f45)

![image](https://github.com/user-attachments/assets/c7747b16-3f6f-49c7-a6df-75c8bda7ad7a)

![image](https://github.com/user-attachments/assets/c4efd7cb-767b-429d-9879-04271734b741)

**Additional context**
Build no : 2024.09.45542
Region : https://neste-dev.platform3solutions.com/
Client : Neste

**Comment by yowanrajan** [comment]
**RCA**
Previously childlist not mapped so unable to view childlist
**Fix Provided**
Childlist also mapped 


<img width="799" alt="Screenshot 2024-10-08 at 10 35 59 AM" src="https://github.com/user-attachments/assets/1a7b57fd-6803-4ce9-8b62-89cae4ef4e3c">

**Comment by maheswarareddyi** [comment]
@Udhayanila8 Please verify and update the fix status

**Comment by Udhayanila8** [comment]
http://192.168.56.146:4081/
**Version**: 2024.10.45564_RC4

In the current version of ADS the searches under the nested group search are visible in the link mapping screen.
 
**Screenshot:**
Creating a parent group search
![image](https://github.com/user-attachments/assets/3b569f65-0679-48cb-950e-e6207a2b3b6c)

Creating another group search with some searches inside the parent group search
![image](https://github.com/user-attachments/assets/bf8899b8-bb21-4bb3-811f-ca2caea0b2ef)
![image](https://github.com/user-attachments/assets/9f7597f3-c7f0-4a90-b797-dddb5a85e9c4)

Creating a link for the searches present inside the group search
![image](https://github.com/user-attachments/assets/05b3dcf0-92cc-45c8-a0e0-aa93b20c7d4c)
![image](https://github.com/user-attachments/assets/528d9867-bcc7-4a4a-b432-159c8b0cc7a4)

**Comment by Udhayanila8** [comment]
http://192.168.1.251:4081/
Version: 2024.09.45542_RC1

The searches under the nested group search are visible in the link mapping screen.

Screenshot:
Creating a parent group search
![image](https://github.com/user-attachments/assets/3db9ebb3-ad9b-493a-aeb1-4b6a0a77b02b)
Creating another group search with some searches inside the parent group search
![image](https://github.com/user-attachments/assets/68f57f78-942d-4054-87e5-51e12d697913)
![image](https://github.com/user-attachments/assets/644837d8-19e5-4657-a49d-cd5903c9ece0)
Creating a link for the searches present inside the group search
![image](https://github.com/user-attachments/assets/74dc82bf-0f0f-4903-ad7c-5559f6f6e050)

**Comment by suseela22** [comment]
Working with the build **2024.09.45542_P3** deployed in Neste environment.
