### ISSUE TITLE
ADS - Data Mismatch for Decimal Number - Neste

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#138]
**Describe the bug**

Source data contains decimal value and its datatype is Number. While ingesting to ADS, decimal values are converted to whole number.

**Screenshots**

**Source Data:**
![image](https://github.com/user-attachments/assets/1dc32d3e-3812-4a3d-a009-7792cc6a45dd)

**Extracted Data:**
![image](https://github.com/user-attachments/assets/30b0ed23-9d5b-4eab-b3bc-cc10cacfff87)

**ADS Data:**
![image](https://github.com/user-attachments/assets/fd1b3aad-cab9-4de7-b09b-ec036458feb0)

**Additional context**
Build no : 2024.09.45542
Region : https://neste-dev.platform3solutions.com/
Client : Neste

**Comment by Nadarajan-suyambu** [comment]
@suseela22 
In Oracle databases, data types like NUMBER are used, but during the ETL process, the NUMBER data type is being converted into DECIMAL. However, in the extracted metadata, the data type is still represented as NUMBER, which caused the issue.

**Comment by kilam005** [comment]
Vetri or Logapriya,
Please update the ETL metadata generation logic.

**Comment by kilam005** [comment]
@UmashankarPalanichamy Please provide the details requested by @harsha-kotha 
Pass the same to @maheswarareddyi and Priya for updating in Docummenattion appendix.

@UmashankarPalanichamy  As informed earlier, this seems like a issue with metadata generation. Hope it is getting addressed in ETL. Either you or Vetri or Logapriyan kindly update the issue tracker with the status of the fix, expected release info. 

Also detail out the fix details.

**Comment by kilam005** [comment]
Code fix are ready.
Demo to be given to @suseela22 before build generation.
Expected to deliver build to testing team today.

@abishekkp this is high priority so checking and upate before 11am tomorrow.

**Comment by abishekkp** [comment]
@kilam005 
**_ETL Tested Version: 2024.10.45588_P2
Server: 192.168.1.75_**

Oracle_Number Datatype mismatch issue is working as expected
Expected datatype conversion from the implementation team
![image](https://github.com/user-attachments/assets/e274e8ed-e30a-4cc2-bd54-62c3849634b5)
**Source Database**
![image](https://github.com/user-attachments/assets/f781e70d-c235-48b3-942e-05086915e54a)
**Extracted Data from ETL**
![image](https://github.com/user-attachments/assets/a59470b2-f116-467c-a3d0-0cc0ed63b44d)
**Ingested Data in ADS, Datatype is matched as expected**
![image](https://github.com/user-attachments/assets/c547808a-d66c-4a1a-8741-f2d776097a1b)

**Comment by suseela22** [comment]
@abishekkp Please mention the ADS version tested and also it is on-prem or serverless. Screenshot from ADS is the expected behavior but it is not displayed as such with the current build (2024.09.45542_P3) in Neste 

@kilam005  It is decided to have zero for the whole number which has 'DOUBLE' datatype. As per the screenshot provided by @abishekkp , COLUMN2 has no zero to the whole number. As per understanding, no fix will be given from ADS side for this issue.

Please make sure the ADS/ETL testing team to test the version and the region used similar to the client environment before release.

Current build in Neste - 2024.09.45542_P3

**Column which has Double datatype**
 
![image](https://github.com/user-attachments/assets/d35b120e-28da-41b9-9290-0348f8539861)

**For whole number .0 is present**

![image](https://github.com/user-attachments/assets/a712f02d-42fb-4cc7-ac71-2d4313d892b5)

**Comment by abishekkp** [comment]
@suseela22 
This is the ADS server and version given for testing,

![image](https://github.com/user-attachments/assets/1751cda0-eeeb-40dc-b43c-2916f3d33a6f)

**Comment by maheswarareddyi** [comment]
An internal review is in progress.

**Comment by kilam005** [comment]
Fix is merged and is expected to roll out in 2024.09.xxxx_P6 or P7

**Comment by kilam005** [comment]
@suseela22 
Kindly check and provide your comments / closure.

**Comment by suseela22** [comment]
Working as expected with the build 2024.09.45542_P6
