### ISSUE TITLE
ADS-values list-NESTE

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#141]
**Describe the bug**

**To Reproduce**
1. As an admin create the values list to use across application
2. Use it for a dropdown to any screen
3. complete the screen development and login as an end user to execute the search

**Expected behavior**
End user should be able to seamlessly use the dropdown with the values pulled from the query mode for values list

**Screenshots**
![image](https://github.com/user-attachments/assets/7714690f-782c-4041-99fe-03c9bea36e3d)

**Additional context**
Build no :
Region :
Client :neste

**Comment by Harik726** [comment]
RCA : 
   This issue occured api permission issue
Fix Provided : 
   provided values list permission based on search permission

ALL ACCESS LOGIN :
![image](https://github.com/user-attachments/assets/85ce4bae-d807-4fd8-ba06-2e9c865ddb7c)
END USER LOG IN :
![image](https://github.com/user-attachments/assets/9a7e1c10-3661-486a-9537-5b5bd7dab3dd)

**Comment by kilam005** [comment]
@selvakumarchandran to check and then move to PRT and assign to @Udhayanila8

**Comment by ShaliniSettu** [comment]
@Udhayanila8 issue have been moved to PRT, kindly start testing it

**Comment by Udhayanila8** [comment]
**Version:** 2024.10.45564_RC6
**Server:**   http://192.168.56.146:4081/login

**Working as expected, The dropdown values are correctly displayed to the end user, and those values are retrieved from the values list in query mode.**

**Working Screenshots:**
## Admin user:
![image](https://github.com/user-attachments/assets/486c33f3-20c1-45b2-b220-56328f7fe5ef)
![image](https://github.com/user-attachments/assets/b7b8fb8a-df49-4784-bb06-f967ae578b31)
![image](https://github.com/user-attachments/assets/7bc8d418-a9b5-48c6-879d-c86755cf33d4)
![image](https://github.com/user-attachments/assets/c23f72a6-2d41-49e0-97f7-7b705311d33a)
![image](https://github.com/user-attachments/assets/2b3c7f88-e619-4511-9fb7-eb3aa971d477)
![image](https://github.com/user-attachments/assets/f3237e76-fdc5-46d9-a504-7a046ca68d90)
![image](https://github.com/user-attachments/assets/e108c656-cdc3-41d3-9e2d-7951257b729d)

## End user:
![image](https://github.com/user-attachments/assets/833576be-3df9-4844-be81-195b4261924f)
![image](https://github.com/user-attachments/assets/85444541-5ffb-42a2-9783-ee6eb36285e0)
![image](https://github.com/user-attachments/assets/da0c9957-fef1-495a-a039-b98bdd0ef523)
![image](https://github.com/user-attachments/assets/917ede59-8fe9-44f9-b007-aaf986d85a68)
![image](https://github.com/user-attachments/assets/938dc999-64de-492e-a66c-0376d772e584)
Multi select Combo box:
![image](https://github.com/user-attachments/assets/0389e366-4a3d-4880-a2dd-b40b28777ea9)
![image](https://github.com/user-attachments/assets/fb91ab5a-97b2-4fa2-9edc-8884bb52222a)
![image](https://github.com/user-attachments/assets/4f98d909-b51f-4f95-9a7a-c19cec1d6a4e)

**Comment by maheswarareddyi** [comment]
@selvakumarchandran  @ashoksri0  Can you confirm the deliverable status of this fix to NESTE environment?

**Comment by kilam005** [comment]
@raniangamuthu 
The fix is available in neste environment.
Kindly check, validate and provide closure

**Comment by raniangamuthu** [comment]
verified and good to close
