### ISSUE TITLE
ADS - Direct background search and export from search form is not working for group searches- Neste 

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#142]
**Describe the bug**
On giving input in search form and  trying a direct background search or export  is not working for group search

**To Reproduce**
1.Inside a group search create a group search
2.In that new group search, created a Main screen and a Nested Screen.
3.From main screen search form ,giving input and trying for direct background search and export.
4.No background job is triggered.

**Expected behavior**
Direct Background job should be triggered and completed for direct background search and export

**Screenshots**
![bg_1](https://github.com/user-attachments/assets/69f42a3e-49c9-407d-a561-8e673066997b)

![BG_2](https://github.com/user-attachments/assets/d5cef00a-9cd8-4e4d-842a-443346958600)

No background job is triggered.

![bg_3](https://github.com/user-attachments/assets/964d3ea2-c7d1-42dc-82d6-69ee7e07dade)

**Additional context**
Build no :
Region :https://neste-dev.platform3solutions.com/
Client :Neste

**Comment by kilam005** [comment]
@prabhakaranUI 
Backend call is not happening.
There is a console eror popping up probablly stopping the API call.

Please check and assign to others if needed

**Comment by kilam005** [comment]
Fix has been provided by FE teams.
Awaiting deployment to pass this to testing team.
ETA: today

**Comment by harsha-kotha** [comment]
Please add RCA details of the issue.

**Comment by ayyandurai-madhes** [comment]
This issue was resolved in tag 2024.10.45564_RC4.
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/321c9181-d15f-404e-b55c-96bfe90b3eff">
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/40d825f7-a21a-47a2-a3e1-e6c742d5ce38">

**Comment by prabhakaranUI** [comment]
`RCA`
 Error occurred If the search form has date and combo fields while performing a background search

**Comment by Udhayanila8** [comment]
http://192.168.1.251:4081/login
Version: 2024.09.45542_RC1

**Background Search and export from the search form working as expected.**

**Scheduling as a background search**
![image](https://github.com/user-attachments/assets/d3749e89-3f79-4ffb-935a-0db897ae7b60)
![image](https://github.com/user-attachments/assets/3aa96a1c-6d2e-4800-9a55-21c3e0efe755)
![image](https://github.com/user-attachments/assets/7e62e629-1d66-4d53-b245-b29fb18107ee)
![image](https://github.com/user-attachments/assets/00d1766b-ce06-4cf8-931d-937e5912dcca)
![image](https://github.com/user-attachments/assets/8e8d47ae-8839-4ce9-a003-f8a82723aba1)
![image](https://github.com/user-attachments/assets/0700604c-e4d0-4ce5-af7a-a2da9f7524bd)


**Export from the search form**

![image](https://github.com/user-attachments/assets/164b5b76-a1cf-4f1c-9acc-b8be4ac8b99c)
![image](https://github.com/user-attachments/assets/74e94eab-232d-46ff-b5b0-d731afb50a91)
![image](https://github.com/user-attachments/assets/febd8c25-e905-4ad4-b0ea-e7f1b4bf5954)
![image](https://github.com/user-attachments/assets/9d9f8533-6029-4de9-9eef-4ff7c7bcb50d)
![image](https://github.com/user-attachments/assets/0e4d8f77-6581-4d94-bc41-94d9bfb00ae3)

**Comment by ThulasiP3** [comment]
This Fix is verified is NESTE environment
