### ISSUE TITLE
ADS-Navigating back from Nested search to Main search is not working for Group search-Neste

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#143]
**Describe the bug**
Navigating back from Nested search to Main search is not working for Group search through breadcrumbs

**To Reproduce**
1.Inside a group search created a new group search . In that new group search, created a Main search and a Nested search 
2.From the nested search navigating back to parent search through breadcrumbs
3.Getting error."Data unavailable"(Please refer word doc attached in screenshot section for reference)

**Expected behavior**
User should be able to navigate from Nested search to Main search for group search.

**Screenshots**
[Work_order.docx](https://github.com/user-attachments/files/17359838/Work_order.docx)

**Additional context**
Build no :
Region : https://neste-dev.platform3solutions.com/
Client : Neste

**Comment by kilam005** [comment]
@Nadarajan-suyambu this seems to require validation at BE side. Please check and update details

**Comment by prabhakaranUI** [comment]
@kilam005 fix from UI side, team working on it

**Comment by yowanrajan** [comment]
Waiting Development , a fix available in V_2024.09.45542

**RCA**
Previously breadcrumb not updated search filter sort bean in nested search

**Fix Provided**
Search filter sort bean updated in breadcrumb


<img width="1674" alt="Screenshot 2024-10-17 at 6 18 23 PM" src="https://github.com/user-attachments/assets/338bb84a-b1d4-4382-b761-6ce5175b9235">

**Comment by Udhayanila8** [comment]
Server: http://192.168.56.146:4081/login
Version: 2024.10.45564_RC4

Working as expected in 146, the user can navigate back from the nested search to the main search and see the data.
![image](https://github.com/user-attachments/assets/8b7b7881-1c12-4a93-aa85-ca8ae87f4300)
![image](https://github.com/user-attachments/assets/906a5e5e-e5cf-4da9-919f-2bac743f559b)
![image](https://github.com/user-attachments/assets/92fd1336-f182-49df-b434-9561c0e4ed43)
![image](https://github.com/user-attachments/assets/f22a2a80-9ef6-435c-ba7b-bc0cc06e3373)
WHEN CLICK THE LINK
![image](https://github.com/user-attachments/assets/08a611f0-9e44-4f73-8910-67fcb6e5834f)
![image](https://github.com/user-attachments/assets/a9b8e621-f184-4971-a42b-48adde88f0da)
WHEN NAVIGATING BACK FROM NESTED SEARCH TO MAIN SEARCH
![image](https://github.com/user-attachments/assets/7b6b6099-aa06-44b9-905d-d66aa7dd1b3d)

**Comment by Udhayanila8** [comment]
Server: http://192.168.1.251:4081/login
Version:  2024.09.45542_RC1

Working as expected in 146, the user can navigate back from the nested search to the main search and see the data.
![image](https://github.com/user-attachments/assets/4403129c-23e4-4348-861c-6485a18580fc)
![image](https://github.com/user-attachments/assets/90143793-8776-42c0-8ce0-9d6e96c70188)
![image](https://github.com/user-attachments/assets/cfeb230a-53b4-4ddd-813e-3d8af9a01d44)
after clicking back 
![image](https://github.com/user-attachments/assets/9de9c264-632a-4fad-8d8c-177b940ae0e9)

**Comment by Nadarajan-suyambu** [comment]
@maheswarareddyi  This issue was fixed and Deployed in the Neste region with tag(2024.09.45542_p3)

**Comment by ThulasiP3** [comment]
Verified in NESTE region. Able to navigate back through breadcrumbs

**Comment by maheswarareddyi** [comment]
We are closing this issue, based on the above comment.
