### ISSUE TITLE
ADS-Error when search is performed using incorrect input on search form-Neste

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#144]
**Describe the bug**
Error when search is performed using incorrect input on search form .Error:" Table \ view does not contain data"

**To Reproduce**
1.Created a main screen and gave a wrong search input. Click on search
2.Getting error: Table \ view does not contain data . It must only show "No data available".

**Expected behavior**
On entering incorrect input in search form user should only see no data available. The Error:" Table \ view does not contain data" should not be displayed.

**Screenshots**

![image](https://github.com/user-attachments/assets/f926c096-87b7-40a0-9519-98530d3b4b39)

![image](https://github.com/user-attachments/assets/a4f6f6f2-9453-4742-a64b-a61c1fd1b2fc)

**Additional context**
Build no :
Region :https://neste-dev.platform3solutions.com/applications
Client :Neste

**Comment by kilam005** [comment]
@ThulasiP3 the message is wrongly displayed. this is noted internally also. This will be fixed soon by the team.

**Comment by kilam005** [comment]
@Nadarajan-suyambu please update on the issue. provide details on the RCA and fix info

**Comment by Nadarajan-suyambu** [comment]
RCA: If the result comes empty means a custom exception was thrown. No need to throw an exception if the result is empty.
FIX: Custom Exception removed.

**Comment by maheswarareddyi** [comment]
@Nadarajan-suyambu @ashoksri0 @abirami1994 Confirm the issue deliverable status to the client environment.

**Comment by Nadarajan-suyambu** [comment]
@maheswarareddyi This issue was fixed and Deployed in the Neste region with tag(2024.09.45542_p3)

**Comment by ThulasiP3** [comment]
verified in NESTE region..Issue fixed

**Comment by maheswarareddyi** [comment]
We are closing this issue, based on the above comment.
