### ISSUE TITLE
ADS-Export not working - Neste

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#145]
**Describe the bug**
Search exports are not working. background job show no progress for exports.

**To Reproduce**
1.Enter search input in search form .click search
2.From the search results select records to export by CSV.
3.Background job on export show no progress

**Expected behavior**
Export job should complete and must be able to download

**Screenshots**
![image](https://github.com/user-attachments/assets/9325eee8-7b41-4f40-a294-ba3dacbf3632)

**Additional context**
Build no :
Region :https://neste-dev.platform3solutions.com/login
Client :Neste

**Comment by kilam005** [comment]
FE issue fix is completed and once deployed it will be released for testing.
in BE exception handling code is also included.

**Comment by prakash-kandasamy** [comment]
@Udhayanila8  this issue was resolved in tag 2024.10.45564_RC4.

<img width="1425" alt="image" src="https://github.com/user-attachments/assets/e5d28d91-1c2c-4098-8272-a43e3002c40f">
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/4ad06255-ac09-4b67-bab0-46bdfd757441">

**Comment by prakash-kandasamy** [comment]
RCA: Error occurred while the search result with the link was exported or scheduled as background search.

**Comment by Udhayanila8** [comment]
**_Server: 192.168.56.146
Version: 2024.10.45564_RC4_**

Performed search with payload and selected the records, and exported in csv. 
Able to export the results.
![image](https://github.com/user-attachments/assets/35f94a0a-55da-4ce2-95b5-9d0395829c88)
![image](https://github.com/user-attachments/assets/f4c196cc-70f2-4ead-a922-0d99e5e471d0)
![image](https://github.com/user-attachments/assets/1979c693-7345-4205-9687-802f5a636db3)
After exporting
![image](https://github.com/user-attachments/assets/54b21e3c-2dc3-4b11-ae37-bbfc946fade5)

**Comment by kilam005** [comment]
> RCA: Error occurred while the search result record was exported or scheduled as background search.

@prakash-kandasamy 
This is not RCA. Its the issue rewritten again in your words.
Explain the RCA and the fix provided in details.

**Comment by prakash-kandasamy** [comment]
RCA: The payload of the selected records was sent as an array of values during export, hence parsing was not working.

Fix details: Value has been corrected to send as map of strings instead of array.

**Comment by Udhayanila8** [comment]
**_Server: http://192.168.1.251:4081/
Version: 2024.09.45542_RC1_**

Able to export searches using links also,
Group search
![image](https://github.com/user-attachments/assets/77a81bb7-d5e8-4009-8d95-02c69331049b)
Group search inside the group search
![image](https://github.com/user-attachments/assets/756afc87-25d6-4a7d-8ee8-4b04a3e3de3f)
Performing the search, and clicking the link 
![image](https://github.com/user-attachments/assets/65d878f7-a53b-4f1f-abe2-95abe7f0404e)
After selecting the link the performed results,
![image](https://github.com/user-attachments/assets/67cb9567-ecca-425d-9e59-612b0ce37f69)
Export using CSV format,
![image](https://github.com/user-attachments/assets/1cb41eb2-4dbf-4640-ac6d-5f8bb4a01d23)
After exporting
![image](https://github.com/user-attachments/assets/e51eff9e-5527-463d-a200-b85dab7439a3)

**Comment by Nadarajan-suyambu** [comment]
@maheswarareddyi This issue was fixed and Deployed in the Neste region with tag(2024.09.45542_p3)

**Comment by ThulasiP3** [comment]
verified in NESTE region..Issue has been fixxed..

**Comment by maheswarareddyi** [comment]
We are closing this issue, based on the above comment.
