### ISSUE TITLE
ADS-Error message displayed while using Advance filter in search results-Neste

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#147]
**Describe the bug**
Error message displayed while using Advance filter in search results [Error:Cannot invoke "com.p3.ads.persistence.application.table.column.model.ColumnEntity.getDataType()" because "entity" is null]

**To Reproduce**
1. create a screen with filtering configuration enabled for columns
2. execute search and on result page select advance filter
4. On giving the input value and clicking on apply button receiving the error message .But the filtered results are also displayed
5. [Error:Cannot invoke "com.p3.ads.persistence.application.table.column.model.ColumnEntity.getDataType()" because "entity" is null] Refer word document for screenshots

**Expected behavior**
Error should not appear on using advance filter.

**Screenshots**
[Advance_filter_issue.docx](https://github.com/user-attachments/files/17375380/Advance_filter_issue.docx)

**Additional context**
Build no :
Region :https://neste-dev.platform3solutions.com/applications
Client :Neste

**Comment by kilam005** [comment]
@Udhayanila8  
I believe this issue is fixed in the recent RC version.
Validate once and then mark it to a developer if its replicable.

**Comment by Udhayanila8** [comment]
http://192.168.56.146:4081/
Version: 2024.10.45564_RC4

@kilam005 It's not replicating in 146 server.
![image](https://github.com/user-attachments/assets/036bdf52-ea04-4b24-ad75-950ce896ef05)
![image](https://github.com/user-attachments/assets/632557ef-0c1a-42d2-b761-80180ffebc4f)

**Comment by kilam005** [comment]
Please check exact case by discussing with @ThulasiP3 .
See if you are replicating for simialr case as theirs.

**Comment by Nadarajan-suyambu** [comment]
ReplicationScenario: Create a search with one table and configure the result and query with another table, Now try the advanced filter getting this exception

RCA: The Filter column is not in the chosen table so getting a null pointer

FixGiven:  Checked notNull condition for columnEntity

**Comment by Udhayanila8** [comment]
http://192.168.56.146:4081/
version: 2024.10.45564_RC4
Created a search with one table and configured the result and query with another table, and tried the advanced filter, getting this exception. It's replicating in 146 server.

Screenshots:
![image](https://github.com/user-attachments/assets/bf3b4f2d-10f9-44ce-814f-eb407d413f10)
![image](https://github.com/user-attachments/assets/d8fa4ed4-04c5-4eb8-bad6-417a147b5faa)
![image](https://github.com/user-attachments/assets/7a657283-0fdb-4596-a0ef-cc66a256cb4e)
![image](https://github.com/user-attachments/assets/b93ab1aa-de84-4343-b58f-477360c9a76f)
![image](https://github.com/user-attachments/assets/0a58321c-2d06-44b5-8892-0cc4ba1b54f2)
![image](https://github.com/user-attachments/assets/81d1a4de-2217-4987-986c-1c56ccec1549)

**Comment by maheswarareddyi** [comment]
@ayyandurai-madhes Please add the development and deliverable status of this issue fix.

**Comment by ayyandurai-madhes** [comment]
@maheswarareddyi  This issue will be deliverable in next release.

**Comment by kilam005** [comment]
@Udhayanila8  please check this and confirm

**Comment by Udhayanila8** [comment]
http://192.168.56.146:4081/
**Version: 2024.10.45564_RC6**
Created a search with one table and configured the result and query with another table, and tried the advanced filter, it's working as expected.

Screenshots:
![image](https://github.com/user-attachments/assets/4c6a7997-9561-4823-b71c-c85753cbce9f)
![image](https://github.com/user-attachments/assets/9a0b9ad6-7593-436f-8a51-bc14dd5e3d95)
![image](https://github.com/user-attachments/assets/6699dafe-c267-478e-85f8-3d84d0346e66)
![image](https://github.com/user-attachments/assets/3ca9ad20-37b5-40f2-8fa6-5ea804e50409)
![image](https://github.com/user-attachments/assets/885e0c18-b313-4746-8ac6-80f751be53f5)

**Comment by kilam005** [comment]
@Udhayanila8 is this verified then. Can it be marked as ready for rollout?

**Comment by Udhayanila8** [comment]
https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P4

Created a search with one table and configured the result and query with another table, and tried the advanced filter, it's working as expected.

Screenshots:
![image](https://github.com/user-attachments/assets/69466126-0b1a-40ab-a675-49783a78ab31)
![image](https://github.com/user-attachments/assets/ab345bbd-7e23-4cbc-abab-79eda3f87177)
![image](https://github.com/user-attachments/assets/ee4131df-6e89-4ba3-8279-73dde013893f)
![image](https://github.com/user-attachments/assets/1fd11f60-da68-43a2-b5ed-8c8372c7452e)
![image](https://github.com/user-attachments/assets/153ba614-b355-4902-b89b-24ac71a1ee99)

**Comment by Nadarajan-suyambu** [comment]
This fix will be available in the next release.

**Comment by kilam005** [comment]
@ThulasiP3 please check and confirm

**Comment by kilam005** [comment]
@ThulasiP3 
please validate and provide closure

**Comment by ThulasiP3** [comment]
Fix verified in NESTE..
