### ISSUE TITLE
ADS - COC - Rate exceeded Error for Some tables  - Neste

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#149]
**Describe the bug**
Schema level COC report is generated for 1864 tables. Among those, 64 tables failed with the error "**Error Occurred: Rate exceeded (Service: Athena, Status Code: 400, Request ID: f087bf06-5b04-4b14-8353-4c81c57f6816)**"

To check the failure, 5 failed tables were triggered again. 4/5 tables got succeeded. One table which got failed was triggered and it is  In_Progress for more than 3 hours and not completed yet.

**Screenshots**

_**One of the failed tables at the first run:**_

![image](https://github.com/user-attachments/assets/5189506b-48ed-4270-9c84-093af5b171e4)

 _**Same table got succeed at the next run:**_

![image](https://github.com/user-attachments/assets/2867f393-af9f-44af-a97f-626c7a57ac17)

_**COC Job In-progress for a long time:**_
![image](https://github.com/user-attachments/assets/9f7c35b3-f676-4f31-bef8-724e4df56a54)

_**No logs were captured:**_
![image](https://github.com/user-attachments/assets/77440590-2480-4722-82b1-9e9d789b24ae)

**Additional context**
Build no : 2024.09.45542_P2
Region : https://neste-dev.platform3solutions.com/
Client : Neste

**Comment by kilam005** [comment]
@abirami1994 update RCA and plan to fix

**Comment by suseela22** [comment]
We face similar issue while executing the search as well

![image](https://github.com/user-attachments/assets/5937ef51-bcfa-4ebf-b97f-d855e7a603c0)

**Comment by ClementJosh21** [comment]
@kilam005 The fix was merged yesterday. 
@Udhayanila8 Need to verify this.

**Comment by abirami1994** [comment]
@kilam005 The fix was merged yesterday.
@Udhayanila8 Need to verify this.

**Comment by Udhayanila8** [comment]
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P4_**

While retesting COC job failed. so issue got reopened.
Trigger application level COC with regex selection,
![image](https://github.com/user-attachments/assets/832e402d-32bd-420b-adba-6d1c3762d78f)
![image](https://github.com/user-attachments/assets/2a5d4398-79e6-44ef-a790-1287edefa432)
COC job failed.
![image](https://github.com/user-attachments/assets/24db2c9d-ba65-4774-ba4a-de7872dade2d)

**Comment by kilam005** [comment]
@suseela22 is verifing and will update

**Comment by suseela22** [comment]
COC report is generated successfully. Working as expected

**Comment by kilam005** [comment]
Thanks for the confirmation @suseela22 .
As discussed once you get the report for the all table all coc case generated confim us back.

**Comment by kilam005** [comment]
@suseela22 
Awaiting you comment to close the issue

**Comment by suseela22** [comment]
Working as expected.COC is successfully completed for 1900 tables with all the cases enabled.
