### ISSUE TITLE
Application_ End user able to view the application when it is dev status.

### ISSUE THREAD

**Issue by Udhayanila8** [P3-Core-Dev-Team/P3-Q-A#15]
**Server**
Pulte prod

**Module**
Application

**Steps**

1. Login as sysadmin.
2. Create the application in dev status
3. Login as end user.

**Expected behavior**
The application should not be visible to the end user.

**Current behavior**
The application is visible to the end user.

**Comment by Udhayanila8** [comment]
Issue fixed. Tested in EMR region.

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f9096d9e-e385-468c-a11f-d932d2404f6b)

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/1595bf9c-e4ea-4b8b-986d-a4e7f9b4ee15)

**Comment by ClementJosh21** [comment]
@harsha-kotha 

**_RCA:_** The permission was not handled properly.

**_Fix:_** The user roles are checked and then the application are listed based on it

**Comment by kilam005** [comment]
@harsha-kotha 
This is avaialble in version 3.1.7 and verified.
kindly check and provide a closure
