### ISSUE TITLE
Screen-Records counts displayed in nested link search results in P_360_v1 but not in P360_v2 -Fairview

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#151]
**Describe the bug**
In P360_v1  patient lookup nested link also displays the record count , But P360_v2 we can only configure the link as icon or text.

P360_v1: As mentioned in screenshot below in the Encounter visit screen we have link to Vitals and measures screen .But that displays with the record counts .

![image](https://github.com/user-attachments/assets/f33e11e6-0953-49bc-9592-eb7a024b8196)

P360_v2:But as mentioned below the new P360 has nested link either as icon or a static display text .Need a UI configuration that will also take up the record counts as display text 

![image](https://github.com/user-attachments/assets/729c7674-efeb-4818-88ce-ee29b20afe0b)
![image](https://github.com/user-attachments/assets/6d6e145d-242d-4276-9add-cbef15bbda85)

Build no :
Region :
Client :

**Comment by kilam005** [comment]
@ThulasiP3 
Please verify and update your notes or concerns.

**Comment by kilam005** [comment]
@P3IND0167 
This is a scenerio based assistance.
Please check and try replicating the result and add `Verified` tag if everything seems ok from testing team's end.

**Comment by P3IND0167** [comment]
Verification of this issue is blocked due to [#364](https://github.com/P3-Core-Dev-Team/Archon-P360-BE/issues/364), once issue closed will recheck & comment here

**Comment by P3IND0167** [comment]
In P360_v2, displaying count has a link is achieved by enabling links option on top of a data column and using query

Adding screenshots below for reference

![Image](https://github.com/user-attachments/assets/d6287c0d-34df-4cc9-9f86-1e4f299a5111)
![Image](https://github.com/user-attachments/assets/b068ecc8-1a90-41e6-a7e2-4ff75dc100fc)
![Image](https://github.com/user-attachments/assets/dda3e20e-1b8f-458b-bf99-1f0aae86408f)
![Image](https://github.com/user-attachments/assets/a2cd81c1-257d-4e6f-90a5-7e5a8c8d9fb0)
![Image](https://github.com/user-attachments/assets/372cabd8-c59a-4bf3-bccf-dc44b0821d39)
![Image](https://github.com/user-attachments/assets/50666836-a024-415c-8a23-b75ec01e6c2e)
![Image](https://github.com/user-attachments/assets/205a15e0-b551-4aba-b5a1-19982a952fe6)
![Image](https://github.com/user-attachments/assets/2e87c4ea-ed96-40cb-bb03-03a0dcb5519b)

**Comment by kilam005** [comment]
@ThulasiP3 
Please check and close this issue.

**Comment by kilam005** [comment]
@ThulasiP3 
This is long standing even after resolution is provided.
Please close or this will be auto closed on 25th Nov.

**Comment by kilam005** [comment]
Auto closing the issue as no action is taken.
