### ISSUE TITLE
ADS-ROLLBACK - Roll Back Issue - ABB

### ISSUE THREAD

**Issue by AshsubM** [P3-Core-Dev-Team/P3-Q-A#155]
**Describe the bug**
After successful ingestion of the data into ADS, when i try do the roll back it is in the READY state only.
No progress after that
The below is the screen shot
Ingestion ID: f958ec08-a0bb-4e3c-9384-a887db51b29f
Roll Back ID: dc294931-d160-41f6-b98c-6602452177b5
![image](https://github.com/user-attachments/assets/c203706d-69ea-40e3-a8c3-8462b7aee766)

![image](https://github.com/user-attachments/assets/197019b4-8fa5-4c35-8e85-ddf347effce3)

Additional context
Build no :2024.09.45542_P3
Region :https://dev.ads-platform3.elis.abb.com/metadata/a3f70340-91d7-41bb-bce6-c250b234ee3f
Client :ABB

**Comment by dinesh-p3** [comment]
`RCA`

The rollback job was not picked due to the inactive transaction in the async method

`👨🏻‍🔧Fix Provided`

Added the required @Transactional annotation to the required method

**Comment by dinesh-p3** [comment]
This issue is fixed and deployed in the region: https://uat-ads.platform3solutions.com/
@Udhayanila8 need to verify

**Comment by Udhayanila8** [comment]
Server: https://uat-ads.platform3solutions.com/login
Version: 2024.09.45542_P4

ingestion Session id for rollback: 0eeb7fa9-b60a-49fd-8e48-563228b4294b

Rollback is not picking and completed, it is under ready status for a long time.
For 3 tables.
Trigger rollback for the ingestion
![image](https://github.com/user-attachments/assets/ba0db710-47d2-4e24-b726-5dc89669eb09)
Rollback is ready status for a long time
![image](https://github.com/user-attachments/assets/5bbbc487-a58e-4d37-89dc-047a11adf557)
![image](https://github.com/user-attachments/assets/75c0fc28-3dd9-4a8c-b6f6-b6cc306fe843)

**Comment by kilam005** [comment]
Issue fix to be rolled out in 2024.09.xxxx_P6.
Post testing the fix will reoslve the issue in ABB

**Comment by dinesh-p3** [comment]
`RCA`

The rollback job was not picked due to the inactive transaction in the async method

`👨🏻‍🔧Fix Provided`

Added the required transaction to the method

PR link: https://github.com/P3-Core-Dev-Team/ADS_BE/pull/3399

**Comment by Udhayanila8** [comment]
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P6_**

Rollback job has been completed.
![image](https://github.com/user-attachments/assets/3740cc3e-3080-4699-a779-b91f60580ccd)
Rollback in progress
![image](https://github.com/user-attachments/assets/3a9de987-f7e7-4c96-b48d-6c968488761e)
![image](https://github.com/user-attachments/assets/3d52106c-f4b1-47cf-8a4e-5642784286b6)
![image](https://github.com/user-attachments/assets/a161297c-20cf-44b0-8212-759d6cafc2ba)
Triggered multiple rollback session
![image](https://github.com/user-attachments/assets/94eddab9-64c0-459b-b31d-5136fbc98aed)
Triggered rollback for 50 files
![image](https://github.com/user-attachments/assets/0afabc8d-5a94-4b03-a394-f2358c5b0080)
All rollback job has been completed
![image](https://github.com/user-attachments/assets/04dcf196-54dc-448f-99e3-1f5c4d65a04a)

**Comment by kilam005** [comment]
@AshsubM ABB regions have been updated.
please check and provide closure

**Comment by AshsubM** [comment]
Hi Team,
Now we could able to perform Roll back job.
Hence closing this issue
