### ISSUE TITLE
ADS-Search-View BLob is not working for PDF file type-NESTE-

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#158]
**Describe the bug**

In NESTE region when we have the Blob type as  PDF(upper case) the view blob feature shows black screen. I am able to view the blob files for lower case pdf and other upper case file types as XML etc..,

**Screenshots**
![image](https://github.com/user-attachments/assets/b7951551-f43c-49ab-9871-a7cd4ec3baaa)

**Additional context**
Build no :
Region :NESTE
Client :

**Comment by Udhayanila8** [comment]
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P4_**

Unable to view the blob data, so reopen this issue.
Content ingestion successful
![image](https://github.com/user-attachments/assets/92b381fc-42ac-4756-94c5-9aac6b7c8a3f)
![image](https://github.com/user-attachments/assets/be0d78a7-ae32-4d8e-8854-a9a09882fc80)
But unable to view the blob data.
![image](https://github.com/user-attachments/assets/96ba1a24-0a84-43a1-baf5-d7ff892ca11f)

**Comment by Udhayanila8** [comment]
**https://uat-ads.platform3solutions.com/**
**2024.09.45542_P4**

While performing ingestion with blob format as PDF (uppercase) extension, Once ingestion is completed, In sample data, blob is visible and in search result also blob is visible, working as expected.

Screenshots:
Sample Data
![image](https://github.com/user-attachments/assets/0e7e59a1-7722-42ee-b020-a7f2af0cd3ff)
![image](https://github.com/user-attachments/assets/aa661d51-4ad6-48b1-9f2a-f5e34951cfaa)
Search Result
![image](https://github.com/user-attachments/assets/f9d14513-1e14-4fea-83d6-de998ea690f1)

**Comment by Udhayanila8** [comment]
@ashoksri0, able to replicate the issue,

**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P4_**

It is not only for the uppercase extension,
If the blob file name has special characters issue occur,
Sample name: Testfile%u00D6T_06-check1976905-1-A1-1_3f8e941b-2af.PDF

Data page screenshots
![image](https://github.com/user-attachments/assets/8ef23dc3-b38a-426a-b359-a3589337465e)
Search page
![image](https://github.com/user-attachments/assets/7e76b2ab-44cc-47e2-a5cf-4b366e7d4f3c)

**Comment by prabhakaranUI** [comment]
`RCA`  
    Special characters in the file name are not supported when viewing the blob on the FE side. 
`Fix'
    Encode the file name using the encodeURI() method to view the blob.

 **Version: [V_2024.09.45542]**

  
[screen-capture (5).webm](https://github.com/user-attachments/assets/5669217c-d593-496f-9072-923e355643d8)

**Comment by kilam005** [comment]
@prabhakaranUI i reviewed the issue.
Please tag the issue to your PR for reference

**Comment by prabhakaranUI** [comment]
@kilam005 
https://github.com/P3-Core-Dev-Team/ADS_FE/commit/0b9453ce01819c42e9cf85a096ce4e099cc4b992

**Comment by Udhayanila8** [comment]
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P5_**

Able to view the blob file if the file name has special characters
filename with special character and upper case extension
![image](https://github.com/user-attachments/assets/9887ed21-99e6-484f-bf4f-1174a57d1f93)
![image](https://github.com/user-attachments/assets/3e8e2999-8182-49b3-90f7-2f1daaabed81)

Include all special characters and extension in Upper case
![image](https://github.com/user-attachments/assets/0f158a56-8e64-404f-b689-13e396be16fb)
ingestion triggered using that file
![image](https://github.com/user-attachments/assets/b54cd625-8e5f-4b3c-b68e-09fbd2503a16)

Able to view the blob in the search page
![image](https://github.com/user-attachments/assets/0e2927aa-b82f-46d8-837d-dda186ca9c6a)
Able to view the blob in the data page
![image](https://github.com/user-attachments/assets/c5d28ec7-1aef-4f4d-a8ce-b9943d82017c)

**Comment by kilam005** [comment]
@ThulasiP3 
The issue has been fixed and can be verified in Neste's environment.
Kindly check and provide closure.

**Comment by ThulasiP3** [comment]
Issue fixed in NESTE
