### ISSUE TITLE
ADS-Rate Exceeded Error-Searches-NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#159]
In NESTE Region -On query validation and search execution we getting the error: 
This error is inconsistent.
![image](https://github.com/user-attachments/assets/efae800d-c79b-46fd-a17a-9ef67a022f86)

![image](https://github.com/user-attachments/assets/a4dbb8d3-be82-4715-8f0b-f9fafd43a55b)

**Additional context**
Build no :
Region :NESTE
Client :

**Comment by abirami1994** [comment]
@kilam005 The fix was merged yesterday.
@Udhayanila8 Need to verify this.

**Comment by kilam005** [comment]
@ThulasiP3 Please check this once in Neste

**Comment by ThulasiP3** [comment]
In the (2024.09.45542_P4) unable to see the error..Closing this issue
