### ISSUE TITLE
ADS-connectivity Error-Searches-NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#160]
**Describe the bug**
In NESTE Searches, Whenever we try to fetch records more than 1lakh (approx). We are getting the below error.

![{FB6A5F0B-D8C7-4AB2-8113-D68658DB80F9}](https://github.com/user-attachments/assets/55a5ca23-f329-40c4-8f18-fca35055892e)

**Additional context**
Build no :
Region :NESTE
Client :

**Comment by suseela22** [comment]
While trying to clone the search, the same issue is occurring after 60 seconds. After refreshing the page it displays the cloned search.

![image](https://github.com/user-attachments/assets/2b8f6757-7452-42db-bd16-581f8de12f5e)

![image](https://github.com/user-attachments/assets/8e47f79f-4990-422b-882d-a24f55f4c98a)

![image](https://github.com/user-attachments/assets/8dffcd2c-bb05-4dd5-9e51-36409b725ce9)

![image](https://github.com/user-attachments/assets/693aca08-f8f0-4618-b2d9-538d5ecff6cd)

**Comment by ClementJosh21** [comment]
@suseela22  
Can you attach the network trace for the above scenario?

**Comment by suseela22** [comment]
[clone_issue- afterrefresh.txt](https://github.com/user-attachments/files/17773959/clone_issue-.afterrefresh.txt)
[clone_issue-beforerefresh.txt](https://github.com/user-attachments/files/17773967/clone_issue-beforerefresh.txt)

**Comment by suseela22** [comment]
**Findings:** Search Execution, Cloning the search - wherever the screen is on standby for 60 second this issue occurs

**Comment by prashanthtk33** [comment]
https://platform3solutionsllc-my.sharepoint.com/:v:/g/personal/clement_m_platform3solutions_com/EUG8aA4lPglIvl8c-AbcDC0BlKQflXbfHYOHhjs5VQcQ7g?e=00hpTr

**Comment by harsha-kotha** [comment]
idle_timeout (a load balancer attribute 
Old Timeout : 60 Seconds
New Timeout : ??
Why is the error message shown on the screen showing inappropriate error message: as "Unable to Establish connection, Please try later" - can we provide appropriate Error message?
Where is this Timeout specified? Are we giving any warning to the user that the time limit is about to reach?
How can you ensure this issue will not occur next time with a even higher volume search?

**Comment by kilam005** [comment]
Load balanced time out will be 5 mins will be the timeout.
at 5 min, serch will be forced to be cancelled or scheduled to BG.

**Comment by santhanakumari15** [comment]
**Server :** https://uat-ads.platform3solutions.com/login
**Version :** 2024.09.45542_P5

Working as expected, in searches, when trying to fetch records of more than 1 lakh records, the search schedules as a background search without any error, and the job gets completed. You can also view the records without any errors.
And The searches can clone successfully without any error.

**Perform Search**
![image](https://github.com/user-attachments/assets/6e0836cb-7c25-4639-8300-d55d471be5e7)
![image](https://github.com/user-attachments/assets/ae98de9e-d235-4f0d-92a6-d35b3bfdfc9f)
![image](https://github.com/user-attachments/assets/937da097-ca5e-4d29-a0e5-3d804a9ae3b1)
![image](https://github.com/user-attachments/assets/b98ea688-fe36-426b-994c-b8ce0d1596b1)

**Clone**:
![image](https://github.com/user-attachments/assets/c4363d8a-bd5a-4ef3-81cb-68051c7e3489)
![image](https://github.com/user-attachments/assets/3feb2c18-0882-40f7-a03e-5ce007bd7661)
![image](https://github.com/user-attachments/assets/f9fd328c-3e3c-43f2-b9c9-105878292a3a)

**Comment by kilam005** [comment]
@ThulasiP3 
The timeout configurations have been updated as previous indicated.
Kindly check and confirm the fix from Neste's environment.

**Comment by ThulasiP3** [comment]
Issue resolved in NESTE ..
