### ISSUE TITLE
ADS-Background search - Background search issue - ABB

### ISSUE THREAD

**Issue by Sethu-P3** [P3-Core-Dev-Team/P3-Q-A#161]
When scheduling the background search, the job is scheduled. But afterward an error appears stating  cannot invoke "java.util.Map.get(Object)" because "payload" is null. 
This is a CRT search

Step 1: Index Search CRT
Step 2: select any one of the index column among different index columns
Step 3: Click on perform background job
Step 4: Will get payload Null error

![image](https://github.com/user-attachments/assets/7a24f014-45cb-48c5-a761-39877ff3e72a)

Screenshot for Background jobs 

![image](https://github.com/user-attachments/assets/fba10b24-3104-4e03-9654-dd5cb88f85c3)

**Additional context**
Build no : 2024.08.45507_p3
Region : https://dev.ads-platform3.elis.abb.com/login
Client : ABB

**Comment by Sethu-P3** [comment]
For now, we are addressing this issue with a temporary workaround from the Front End. However, it must be thoroughly tested and verified in the upcoming release.

**Comment by ClementJosh21** [comment]
`✏️ Description or RCA`

While scheduling background search for any link, nested payload was not handled.

##
`👨🏻‍🔧Fix Provided`

While scheduling background search for any link, nested payload is passed and set as payload

##
`📑PR link`

[3417](https://github.com/P3-Core-Dev-Team/ADS_BE/pull/3417)

**Comment by Udhayanila8** [comment]
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P6_**

Able to view the records using CRT search and nested link.
Created CRT search with the link,
![image](https://github.com/user-attachments/assets/3c0e310b-41c8-4a14-bf19-9ffc32466f98)
Performed the search
![image](https://github.com/user-attachments/assets/45e80ddc-039c-4da8-a81c-c399dfcbe273)
Click the link column, bg search is triggered
![image](https://github.com/user-attachments/assets/7b127678-3e0b-48ad-b345-260039cdad8f)
Job completed
![image](https://github.com/user-attachments/assets/14093dea-07a2-493b-b309-6dde62aa6cc6)
Able to view the records in BG search.
![image](https://github.com/user-attachments/assets/31c55ba0-729b-44a0-8e8f-c8ef1f07c721)

**Comment by Sethu-P3** [comment]
I am now able to view the data when performing a background search. but it is taking longer to complete the job

**Comment by kilam005** [comment]
@Sethu-P3 
from the comment above, i hope this is verified.
Kindly close the issue if the issue is resolved

**Comment by Sethu-P3** [comment]
This issue was cleared and it is working as expected.. Thank you
