### ISSUE TITLE
ADS-Improper sorting of Null values for String datatype-NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#164]
Improper sorting of Null values for String datatype in search results
Reproduce:
1.Run a search with with result column configured as (string datatype , has null values and sorting enabled)
The below screenshot shows on sorting for event description column ,the null values populate in between rather than the beginning or end.
![image](https://github.com/user-attachments/assets/5cfad6be-7433-4d67-bfa4-426953ea7c8c)

![image](https://github.com/user-attachments/assets/bdd16a7c-1226-4830-9234-dffc93e1c5b1)

**Additional context**
Build no :
Region :NESTE
Client :

**Comment by kilam005** [comment]
@ThulasiP3 
please use `COALESCE(M.DESCR,'') as DESCR` as a **workaround** to fix this issue.
For some reason, this issue happens only on this column.

We'll check from code presepective once. But this could be data related.
Please let me know if it occus in any other column too.

**Comment by VikramSelvadurai** [comment]
**RCA**
default value added for null value(.nullValue("NONE")) in open search, due to this sorting not working
**Fix Details**
removed change NONE to "" empty string to handle sorting 

removed Is null and Is not null case from UI, for both is empty and is null having same case, 
so removed is null and Is not null for String data types

**Comment by harsha-kotha** [comment]
Please add RCA

**Comment by santhanakumari15** [comment]
**Server :**  https://uat-ads.platform3solutions.com/login
**Version :** 2024.09.45542_P5

Working as expected, when applying sorting by ascending and descending order,
the null values are populated at the beginning and end only.

**Before sorting:**
![image](https://github.com/user-attachments/assets/f0ed4c50-fe59-4e39-9852-e1df8200ac0a)

**After Sorting:**

![image](https://github.com/user-attachments/assets/a0757cd5-50dc-4da0-a1cc-18db28599cae)
![image](https://github.com/user-attachments/assets/c837d9b4-62a6-40ae-93c4-9a4d49e27ac6)
![image](https://github.com/user-attachments/assets/7f6504ec-dbff-4953-8784-e71660c862f6)

**Comment by kilam005** [comment]
@ThulasiP3 
This issue can be retested in neste's environment.
Please clear any available cache before checking.
Kindly confirm and provide closure

**Comment by ThulasiP3** [comment]
This Issue is resolved in NESTE now..
