### ISSUE TITLE
ADS-SEARCH - END user unbale to see the Latest Records - ABB

### ISSUE THREAD

**Issue by AshsubM** [P3-Core-Dev-Team/P3-Q-A#165]
**Describe the bug**
I ingested two new reports in the application(MOBIUS VIEW), Already there are 55 reports ingested .
After I ingest the two reports , In admin login i checked via search and can able to see 57 reports( 55 already present +2 new ingest)
Admin login,
![image](https://github.com/user-attachments/assets/eb70f9c2-3197-48e7-aae1-a85355850943)
 

Then  after that I logged in as an end user and performed the same search
I got only 55 Reports,
 
![image](https://github.com/user-attachments/assets/fe19c7b6-1169-4b94-851f-b210ebe50a6f)

Then I cleared the cache for the search 
![image](https://github.com/user-attachments/assets/fdc3a585-81cf-488f-bf55-4a9cd277c5bb)

 

And tried the same search as an end user login, Now the result is showing 57 in end user login
![image](https://github.com/user-attachments/assets/9cc14c81-40bc-425d-b04f-4d4c13910485)

Kindly refer the documnet below 

 
[RECORDS not properly displyed for the end user.docx](https://github.com/user-attachments/files/17770447/RECORDS.not.properly.displyed.for.the.end.user.docx)

**Additional context**
Build no : Version: 2024.09.45542_P3
Region : https://dev.ads-platform3.elis.abb.com/applications
Client : ABB

**Comment by ClementJosh21** [comment]
`✏️ Description or RCA`

Cache table was working based on user ID

##
`👨🏻‍🔧Fix Provided`

Filtering cache based in user ID was altered

##
`📑PR link`

[3415](https://github.com/P3-Core-Dev-Team/ADS_BE/pull/3415)

**Comment by kilam005** [comment]
@Udhayanila8 Please check and confirm

**Comment by santhanakumari15** [comment]
**Server:** http://192.168.56.146:4081/login
**Version:** 2024.10.45564_RC8

## Working as expected. When Login as end user and perform a search -> all the records are fetched correctly, and the record counts are proper.

**First Ingest - 99 records**
![image](https://github.com/user-attachments/assets/afcaa9fd-152a-4520-bd61-09270a1f7642)
![image](https://github.com/user-attachments/assets/88db8e1e-9e7f-456f-80f7-4ed59339839e)
## Admin:
![image](https://github.com/user-attachments/assets/20fc5396-50bb-4326-a6cd-ae3d930b5e3c)
## Enduser:
![image](https://github.com/user-attachments/assets/8b2ca8f9-7597-4a9e-a717-99c2d9a71dd9)

**Again ingest - 51 records**
![image](https://github.com/user-attachments/assets/c1fda2e9-4dc3-4afd-8570-44ef24226982)
![image](https://github.com/user-attachments/assets/bba3bc4d-f11a-4bfd-8292-8043258c6146)

## Admin user:
![image](https://github.com/user-attachments/assets/bf84a29c-7c78-4581-b85a-bd51d3df9028)
## End user:
![image](https://github.com/user-attachments/assets/3e59f897-5e71-4e78-9c3f-4b58ab452422)

**Comment by kilam005** [comment]
@AshsubM 
please check and provide closure

**Comment by AshsubM** [comment]
Will check and update

**Comment by kilam005** [comment]
@AshsubM 
Please confirm soon

**Comment by AshsubM** [comment]
Hi Team, Working as expected hence closing this issue
