### ISSUE TITLE
ADS - Application Name - Edit - Neste

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#166]
**Describe the bug**

While editing the application name from 'M+ IFS App' to 'M+ IFS Application' it eliminates the '+' from Application Name

**Screenshots**

![image](https://github.com/user-attachments/assets/8f4f8345-d7d1-4080-8ec5-d5d2215867e2)

![image](https://github.com/user-attachments/assets/db865afc-4c73-43e6-818c-238905955570)

**Additional context**
Build no : 2024.09.45542_P4
Region : https://neste-dev.platform3solutions.com/
Client : Neste

**Comment by Nadarajan-suyambu** [comment]
RCA: As a result of the penetration test, we restricted special characters to enhance security.

 FIX: We removed the '+' character from the list of restricted special characters, which now includes the
 following characters: < > " ' ` & ; / \ ( ) { } [ ] : = % $ | ^ ~.

**Comment by kilam005** [comment]
To avoid scripting hijacks (such as Cross-Site Scripting or XSS)  the below characters will be restricted in key inputs areas.
< > " ' ` & ; / \ ( ) { } [ ] : = % $ | ^ ~

**Comment by Udhayanila8** [comment]
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P5_**

Edit the application name and give + in the application name 
![image](https://github.com/user-attachments/assets/1c579394-6664-463f-9f85-296eb838de27)
And save the application
The edited name was added, and the reference name remains the same
![image](https://github.com/user-attachments/assets/4ac5d603-d220-48c7-9577-d2607ad6e61a)
Able to edit with space
![image](https://github.com/user-attachments/assets/f069ffb6-a9ba-45c3-8bdd-96bf15eadb49)

Able to give the following special character only other characters are restricted
![image](https://github.com/user-attachments/assets/1aab3929-79df-4374-ac9c-2f4bb2f3c193)
The application name has changed and the reference name remains the same
![image](https://github.com/user-attachments/assets/546ed449-abaa-4d15-ade3-cdff4556ad26)

Create an application with special characters
![image](https://github.com/user-attachments/assets/af20d6ef-19e6-4bc9-b7db-0db2c2075ee9)
Application created
![image](https://github.com/user-attachments/assets/1a2485bb-39f6-4302-835e-1051672728bd)
Special characters considered as underscore
![image](https://github.com/user-attachments/assets/aa277728-2b48-4701-8227-4b08af1072e6)
Metadata page
![image](https://github.com/user-attachments/assets/dd0d3a21-7e9e-4ecb-ab41-d45f058643ce)
Search page
![image](https://github.com/user-attachments/assets/246c4d33-f1c4-4cdb-80fb-7d537b84d269)

With space
![image](https://github.com/user-attachments/assets/605df5e9-c4fc-48b9-934b-af7c25c2c805)
In BG job
![image](https://github.com/user-attachments/assets/eb40ab58-515e-4933-b67e-40c1c83eb341)
In status monitoring
![image](https://github.com/user-attachments/assets/cda04bc9-5c67-4bef-8178-6b64f536b118)
Query editor page
![image](https://github.com/user-attachments/assets/c4da17f7-bba1-40cb-b302-ce6fc21d4461)

**Comment by kilam005** [comment]
@suseela22 
I believe you have already verified the fix.
Kindly confirm and close this issues

**Comment by suseela22** [comment]
Working as Expected.
