### ISSUE TITLE
ADS-Update button on  search screen is not working properly-NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#169]
**Describe the bug**
After the new deployment (2024.09.45542_P5), the update button is not working on search screen. For those Search that has special character as search name it is not updatable.. After removing the special character we are able to update..

![image](https://github.com/user-attachments/assets/d3e09a42-5b48-4458-b852-bae5f5c9ca90)
![image](https://github.com/user-attachments/assets/de69f35e-7ccb-4b40-9759-e3fbb73b3f2c)
![image](https://github.com/user-attachments/assets/a1065a6a-df3c-4825-89ff-b5790112867a)

**Additional context**
Build no :
Region :
Client :

**Comment by Nadarajan-suyambu** [comment]
RCA: We restricted special characters to enhance security due to the penetration test.
FIX:  If any application and search contains < > " ' ` & ; / \ ( ) { } [ ] : = % $ | ^ ~ 
these characters mean that characters changed into _ using a script

**Comment by Nadarajan-suyambu** [comment]
As per pen test recommendation to avoid cross-hijack, the following chars are restricted from the input.
< > " ' ` & ; / \ ( ) { } [ ] : = % $ | ^ ~

We are planning to check the allowance of () and / alone. Once we get confirmation will remove the restriction on the selected characters from the restricted char list.

**Comment by kilam005** [comment]
@Udhayanila8 to check

**Comment by kilam005** [comment]
@ThulasiP3 
Please check and update if it can be closed.

( ) / Characters are now removed from the restricted char list.

The updated restricted char list is as below
< > " ' ` & ; \ { } [ ] : = % $ | ^ ~

**Comment by ThulasiP3** [comment]
Fix verified .closing the issue
