### ISSUE TITLE
Pulte - Non-Prod Searches are failing

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#17]
Pulte - Non-Prod Searches are failing, the same was reported in Team with Screenshot.

[16:18] Selvakumar Chandran

now can you check once Praveen

[16:18] Anitha Anthony

Selvakumar Chandran

now can you check once Praveen

Selva may I know what was corrected?

[16:33] Praveen kumar Thangavelu

Now RM data screens-  searches ,background search and exports  are working as expected 

[16:34] Selvakumar Chandran

Anitha I think the node went into some idle state when you triggered the search, but auto-refreshing the node has realigned everything, and now it's working fine. Other than that, there are no issues on the app side

Anitha Anthony

Selva may I know what was corrected?

[16:43] Anitha Anthony

How can we prevent the node from moving into idle state? 

[16:44] Harsha Kotha RajendraPrasad

also i thought there was monitoring setup on non-prod, did not see any alert coming out 

[16:46] Anitha Anthony

Business users have started testing, so we cannot have such occurrences. 

[17:10] Selvakumar Chandran

Anitha  Harsha  Sure, I understand that. We are not creating permanent nodes (task) in the ecosystem. We only have instances. ill keep track and update

[17:38] Harsha Kotha RajendraPrasad

Selva, would be better if there is an automated way to track. Pls see if this can be caught as health check or monitoring. Be it task node or permanent node user experience needs to be seamless

[18:37] Selvakumar Chandran

ok Harsha

Need a way to avoid this situation, since this needs manual intervention it is better to provide automated way to keep services up and running.

**Comment by kilam005** [comment]
@selvakumarchandran please check this

**Comment by kilam005** [comment]
@harsha-kotha 
what is the expectation for this issue?
is this still happening?

**Comment by harsha-kotha** [comment]
Background Searches were never pick up. Selva checked it and mentioned that the Nodes are idle. We need to have this covered and alerted if Node goes it idle. Assuming the root cause is node going idle.

**Comment by selvakumarchandran** [comment]
@harsha-kotha When we trigger a large query, it takes time to complete, and during this time, the node goes idle to clear cache. To address this issue, we close the session and clear the cache once the query is complete. We have tested and verified this solution.

**Comment by kilam005** [comment]
`RCA`
node goes idle while attempting clear cache

`Fix details`
Coding logic was added To close the session and clear the trino cache once the query is complete.

**Comment by kilam005** [comment]
@harsha-kotha 
please check the above comment and provide your comments

**Comment by harsha-kotha** [comment]
Closing out as RCA and fix is added.

**Comment by harsha-kotha** [comment]
can we add email notification if in case if the Node goes idle for any other reason.

**Comment by kilam005** [comment]
This should be possible. 
We need to include in scripting area. 
Will direct it to DevOps team.

**Comment by kilam005** [comment]
Selva has confirmed 
"Script is ready and testing is in progress"

**Comment by Udhayanila8** [comment]
Before trino down, able to perform the search.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/146f4b2f-6fac-49c7-a875-c22fdea53d5e)
While Trino is down search is throwing an error.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/9930900f-bbc1-4334-afee-830e32f4cb40)
Can get the notification mail while Trino is down.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/4bd6460f-bb65-4b46-bda1-ece31879a112)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/57bdb169-8e5d-4474-b59b-76be2909ea1c)
We can get the mail notification in 5 mins frequency when Trino is down.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/1eb05da8-de4f-43aa-9f34-f36cc3b482a4)

**Comment by kilam005** [comment]
@harsha-kotha 
script was prepared and tested.
Please check and provide closure.

**Comment by kilam005** [comment]
@harsha-kotha : reminder to validate and close

**Comment by harsha-kotha** [comment]
Thank you for handling Idle state.
