### ISSUE TITLE
ADS-Cache Error on Search result-NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#170]
After the new deployment ,Executing a search screen with a  input .On landing search result, Receiving the below error. On clearing Cache the issue is resolved and able to fetch results. This issue does not occur for all screens

![image](https://github.com/user-attachments/assets/f0f9a1c5-7e66-4749-baa9-bc6098edf7d7)

**Additional context**
Build no :
Region :Neste
Client :

**Comment by kilam005** [comment]
Please clear cache and try once.

**Comment by suseela22** [comment]
During End user testing we faced similar issue . Since there is no option to clear cache from end user role we cleared with the admin privilege and continued with End user testing. If the same happens during every deployment then there should be an option to clear cache at once instead of clearing cache on every search.

**Comment by kilam005** [comment]
@suseela22 
we have planned for simpler options. 
We'll address this and provide you the way.

@ClementJosh21 
As discussed, once you have the api for gloabal and application based cache clearance ready, let me know.

**Comment by kilam005** [comment]
The global cache clearance, application level cache clearance are being planned and tragetted for 2024.09.45542_P7 release

**Comment by kilam005** [comment]
Backednd dev compleleted. Dev test is in progress
UI integration is planned to start

**Comment by ClementJosh21** [comment]
@kilam005 As per the above comment a global and application level cache clearance has been implemented.

**Comment by Srividhya2506** [comment]
https://dev-support.platform3solutions.com/
**Version: 2024.09.45542_P7**

Created a search and performed, it is fetching data. Cleared cache from application level and triggered search, cache was cleared and result executed. Then cleared cache from global level, cache was cleared and result executed. Checked for search level cache also. It is working as expected.

For global level and application level, job is scheduled for cache clearance in background jobs but not for search level cache clearance and it is verified. It is verified that only for Developer role and Administrator role, Clear cache is applicable in global level and in application level.

Screenshots:
While triggering search for first time.
![image](https://github.com/user-attachments/assets/9b23cb77-9ca0-4670-9ee6-dadbcbcb8fc9)
Application level cache clearance
![image](https://github.com/user-attachments/assets/98a4cbb7-ab18-4fd2-8ff4-a1de1fa2a364)
![image](https://github.com/user-attachments/assets/653b2994-8d2f-4ef6-b09c-de8b4baa74ae)
![image](https://github.com/user-attachments/assets/479d0eaf-ccb9-4b11-bc77-5d4350aa90ac)
![image](https://github.com/user-attachments/assets/0dd4f30f-7393-4961-b8db-833afd597f6f)
![image](https://github.com/user-attachments/assets/30bd51ba-140a-482c-b8c7-762b4b0a9202)
![image](https://github.com/user-attachments/assets/354b0070-7540-4e15-b0cd-bf89e28ff83e)
![image](https://github.com/user-attachments/assets/0cd7cabc-9676-40ee-930b-a0a7467599bb)
![image](https://github.com/user-attachments/assets/0111d2a4-4663-4357-9009-cefa734e2761)
![image](https://github.com/user-attachments/assets/476a8cc9-127c-4d45-bcd8-1337a9ea8192)
Global level cache clearance
![image](https://github.com/user-attachments/assets/c198f1c6-f6db-4e4f-97e0-9b87eb7488ff)
![image](https://github.com/user-attachments/assets/2d228946-b3fd-4cf2-8823-c24b7689b187)
![image](https://github.com/user-attachments/assets/a681c821-b9f3-4dca-8be2-bf2db84fe316)
![image](https://github.com/user-attachments/assets/3ea0a39e-9246-480c-984b-41627526d2fc)
![image](https://github.com/user-attachments/assets/fc36a236-929c-498b-92a5-f4ab0a4bebeb)
![image](https://github.com/user-attachments/assets/99810ec2-0f5f-4f77-b1b6-dc7edb12b4ca)
![image](https://github.com/user-attachments/assets/62ce3a8f-189d-4c43-b076-e1449caa4b68)
![image](https://github.com/user-attachments/assets/ed88fcb1-afdb-42ac-8c70-1c3defc7751f)
![image](https://github.com/user-attachments/assets/2a68ef3f-7f3b-404f-baa0-8cee899d6f94)
Search level cache clearance
![image](https://github.com/user-attachments/assets/a4eb6861-4d42-4782-a356-f7399755b2cf)
![image](https://github.com/user-attachments/assets/b91beb1a-72d0-4a7f-a4d6-0ed469584877)
![image](https://github.com/user-attachments/assets/fb4a9719-c3a3-4c1b-93a5-9b1befc317be)
![image](https://github.com/user-attachments/assets/d4854d16-878f-4dd7-94f4-0cd5307765cd)
Role
![image](https://github.com/user-attachments/assets/9eacc68b-c302-4413-a0f7-7870fd2e4ed6)
![image](https://github.com/user-attachments/assets/a1dd21ee-1ff4-4258-84f7-55796f411a91)
![image](https://github.com/user-attachments/assets/7ed50d23-1f4b-4f7a-bfe2-f3c3d2397e30)
![image](https://github.com/user-attachments/assets/4f44b856-1454-4b91-9119-11b8e15f3610)
![image](https://github.com/user-attachments/assets/9a81772d-ed55-4f6b-b91d-6cf33450b5bb)
![image](https://github.com/user-attachments/assets/d5d8fbc1-aed9-4673-a6ef-2d18e029433b)
![image](https://github.com/user-attachments/assets/84ac156e-7a06-42a8-a408-335cdcbd19dc)
![image](https://github.com/user-attachments/assets/046f2376-197e-4b1b-a9fa-839b6c605cc8)
![image](https://github.com/user-attachments/assets/05435f73-5c7f-48b2-b78f-7e494e1196bf)
![image](https://github.com/user-attachments/assets/f5d6a786-df95-49af-8699-ee77e3d03dd1)
![image](https://github.com/user-attachments/assets/36d763d4-cdf2-4aaf-85b2-52d936205fdb)
![image](https://github.com/user-attachments/assets/fa869f55-0f4c-48b4-9385-69abb16d7cee)
![image](https://github.com/user-attachments/assets/b64d355c-f264-465e-b154-db48f0952b32)
![image](https://github.com/user-attachments/assets/c06c2bfa-909a-4951-9f66-1dfeebd5f25d)
![image](https://github.com/user-attachments/assets/c09fedee-8f01-47d3-955f-52ef770da44e)

**Comment by kilam005** [comment]
@ThulasiP3 
Please check and provide closure

**Comment by kilam005** [comment]
@ThulasiP3 
Reminder to check and provide closure

**Comment by ThulasiP3** [comment]
No longer facing this error.Hence closing the issue.
