### ISSUE TITLE
ADS-Receiving  Error Message on  Sorting -NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#171]
In the new deployment(2024.09.45542_P5) ,On search execution and fetching results, Clicking on the sort icon, Receiving the below error. This issue does not occur for all sorting columns .

![image](https://github.com/user-attachments/assets/02e6bbfd-1f8f-4dc1-ba94-961e5a842965)

**Additional context**
Build no :
Region :NESTE
Client :

**Comment by kilam005** [comment]
@ThulasiP3 
Clear cache once and try.

**Comment by ThulasiP3** [comment]
Used NULL  as Invoice type in query. On using  ' ' as Invoice type for a column We are not getting this error..

**Comment by ClementJosh21** [comment]
`✏️ Description or RCA`

While creating a search, a column is set as 'NULL' in query and while create mapping in the OpenSearch the particular field was not handled properly.

**Comment by kilam005** [comment]
Fix is in progress.
Targetted for 2024.09.45542_P7

**Comment by ClementJosh21** [comment]
PR are merged and the fix will be readily available in the version `2024.09.45542_P7`

BE - [344](https://github.com/P3-Core-Dev-Team/ADS_BE/pull/3444)
FE - [2155](https://github.com/P3-Core-Dev-Team/ADS_FE/pull/2155)


##
`✏️ Description or RCA`
While creating a search, a column is set as 'NULL' in query and while create mapping in the OpenSearch the particular field was not handled properly. 

##
`👨🏻‍🔧Fix Provided`
The mapping creation was altered in such a way to handle NULL values provided the query and also to indicate result fields missed in the query.

**Comment by Srividhya2506** [comment]
https://dev-support.platform3solutions.com/
**Version: 2024.09.45542_P7**

Created an advanced search and the column value is set as 'NULL' in query, and sort is enabled for that column. While performing a search, the error message did not occur on the result screen when triggered the search, and by clicking on sort for the column. It is working as expected.

Screenshots:
![image](https://github.com/user-attachments/assets/8076dd6b-8ac9-44ba-a993-4d0867cb7d1e)
![image](https://github.com/user-attachments/assets/5095023d-e607-4114-b609-52f04d92cf16)
![image](https://github.com/user-attachments/assets/3c0da9fe-177e-4319-933f-e47a809813ac)
![image](https://github.com/user-attachments/assets/b38824c2-2e2e-4b88-9e4d-7181f8d1d476)
![image](https://github.com/user-attachments/assets/3eb8a714-9111-4575-b09a-c364e9f69910)
![image](https://github.com/user-attachments/assets/7085a678-ac1a-4908-a9ad-3e3f1c30f7aa)

**Comment by kilam005** [comment]
@ThulasiP3 
please check and provide closure

**Comment by kilam005** [comment]
@ThulasiP3 
reminder to check and provide closure

**Comment by ThulasiP3** [comment]
Issue resolved in Neste.Closing the issue
