### ISSUE TITLE
ADS-Error on Direct Background search export-NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#172]
**Describe the bug**

On Direct background search ,View the records . Select all and Export .Below error occurs

![image](https://github.com/user-attachments/assets/98cb38fb-e9b7-43c8-b5b8-ba86d89d2d07)

![image](https://github.com/user-attachments/assets/34539d31-b414-435e-9df1-f270fdcdcff1)

**Additional context**
Build no :2024.09.45542_P5
Region :https://neste-dev.platform3solutions.com/
Client :NESTE

**Comment by prakash-kandasamy** [comment]
**`RCA`**
The issue occurs when clicking the background search button. The date fields are not correctly mapped in the uiInfo payload, resulting in incorrect data being passed. Consequently, the export button retrieves and sets the wrong payload when viewing the results.

**`Fix details`**
The issue was resolved by mapping and passing the date field values correctly in the payload during the scheduled background search.

**Comment by Udhayanila8** [comment]
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P6_**

Able to export the results with date field using BG search.
Search form has a date field
![image](https://github.com/user-attachments/assets/2398c492-f9a8-402b-ab23-5cae0f42d809)
BG job triggered
![image](https://github.com/user-attachments/assets/2679dfe8-609a-40ef-9f6a-2da4123ac676)
![image](https://github.com/user-attachments/assets/b14603d4-1d5f-42fa-8366-9cc1a70a04a2)
BG search completed
![image](https://github.com/user-attachments/assets/47b9d118-1987-49e5-8d39-b460cbfd7de9)
![image](https://github.com/user-attachments/assets/2cd2c7ef-8018-4e17-bd4e-515ab60fa128)
Select all records, and click export
![image](https://github.com/user-attachments/assets/3363d6af-f70b-42a7-bc3f-ba7c405502ab)
![image](https://github.com/user-attachments/assets/4de5624e-5216-4679-8513-983164921099)
![image](https://github.com/user-attachments/assets/a56a35fe-28ec-41d6-b4b0-4eb7db950597)
Results export completed
![image](https://github.com/user-attachments/assets/0ebd2e47-6aa7-46a6-b5ab-a31c3e03e33e)
Downloaded
![image](https://github.com/user-attachments/assets/e8776e25-9326-4309-8b93-2f02b050b8a5)
![image](https://github.com/user-attachments/assets/7a7f7d33-2c5b-42c5-9c79-1946668262fa)

**Comment by kilam005** [comment]
@ThulasiP3 please recheck and provide closure

**Comment by ThulasiP3** [comment]
Issue Fixed..Verified in NESTE
