### ISSUE TITLE
ADS-Record count mismatch for direct export (records more than 535000) -NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#173]
**Describe the bug**
Performing a direct export for 535389 records, After job completion. and download the record count 535390(excluding header)

![image](https://github.com/user-attachments/assets/e79a7eae-70b2-4ef5-8211-54239145de2f)
![image](https://github.com/user-attachments/assets/3ad3655a-4d9b-475d-8550-3f2aaf80cf1e)

**Additional context**
Build no :2024.09.45542_P5
Region :https://neste-dev.platform3solutions.com/
Client :NESTE

**Comment by kilam005** [comment]
There is no extra data.
There is a carriage return character causing data to be split into two lines resulting in 1 extra line.

<img width="1792" alt="SS1" src="https://github.com/user-attachments/assets/52f11585-ca9c-4a27-94ee-5227f6cd9480">

**Comment by kilam005** [comment]
@ThulasiP3  please check above

**Comment by ClementJosh21** [comment]
##
`✏️ Description or RCA`

Handling of \r is missed in the export engine

##
`👨🏻‍🔧Fix Provided`

Replaced every \r with \n in the export engine

##
`📑 PR link`

[3426](https://github.com/P3-Core-Dev-Team/ADS_BE/pull/3426)

**Comment by santhanakumari15** [comment]
**Server:** https://uat-ads.platform3solutions.com/login
**Version:** 2024.09.45542_P6

![image](https://github.com/user-attachments/assets/e25af16c-8886-49cc-9f1a-2994cd44fc76)
![image](https://github.com/user-attachments/assets/e3d97c79-b5e0-4dbc-b335-7ac9bd001b05)
![image](https://github.com/user-attachments/assets/0b5fe8bd-3323-4ab6-99d2-52724f63b844)
[Job_name_1732302427968.zip](https://github.com/user-attachments/files/17875026/Job_name_1732302427968.zip)

**Comment by Udhayanila8** [comment]
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P6_**

Data has carriage return character
![image](https://github.com/user-attachments/assets/1a6cad39-1990-443e-a6d5-c26d8a83b911)
Search has 1000 records
![image](https://github.com/user-attachments/assets/d880b333-8c62-494c-a630-4e7c0a25c961)
Export all records in CSV format
![image](https://github.com/user-attachments/assets/c79195e3-542b-4745-afc6-aaee56f044f1)
Job completed
![image](https://github.com/user-attachments/assets/7bf9ce81-0cbf-456d-a6be-557f6d48d256)
The same 1000 records were exported including the header.
![image](https://github.com/user-attachments/assets/de8548dc-900d-4dad-8d2d-f39176d32803)

**Comment by kilam005** [comment]
@ThulasiP3 
please check and provide your closure

**Comment by ThulasiP3** [comment]
Issue fixed and Verified in NESTE
