### ISSUE TITLE
ADS-Error when navigating through nested link and trying a background search-NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#175]
**Describe the bug**

1.Created a group search. Create another group search inside this search. Within the new group search having a primary search and 2 nested search.
2.On navigating from 1st nested search to 2nd nested search getting the below error. 
3.Nested search prompts me to run as Background search.On clicking run as background search ,Getting the below error
We do not get this error on running the search individually.

![image](https://github.com/user-attachments/assets/4ef36acd-d2d6-4c64-ac41-2163facdb272)
![image](https://github.com/user-attachments/assets/853f6e8c-3909-42e6-acf8-ca38b3e2280a)
![image](https://github.com/user-attachments/assets/19c79b48-3f6f-43a0-a0e4-df00e6926520)
![{EC2C6E14-E20E-4AFA-977E-809F8EC3E1A0}](https://github.com/user-attachments/assets/612ad721-f3e2-4227-b96c-10b5e17aef91)

**Additional context**
Build no :2024.09.45542_P5
Region :https://neste-dev.platform3solutions.com/
Client :NESTE

**Comment by harsha-kotha** [comment]
Please add RCA details.

**Comment by ClementJosh21** [comment]
`✏️ Description or RCA`

While scheduling background search for any link, nested payload was not handled.

##
`👨🏻‍🔧Fix Provided`

While scheduling background search for any link, nested payload is passed and set as payload

**Comment by Udhayanila8** [comment]
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P6_**

Able to perform the search, using nested link in BG job.
Created Group search into another group search, created search with a nested link for around 9 lakh records, 
![image](https://github.com/user-attachments/assets/350738d8-2f37-4a6e-816c-d09b06b87274)
![image](https://github.com/user-attachments/assets/f3ac6798-00c4-4b94-b856-092bc307b309)
Triggered the BG job, once the BG job is completed view the results
![image](https://github.com/user-attachments/assets/bbc2c78f-cead-4880-8936-a6eb80a7cd4b)
![image](https://github.com/user-attachments/assets/c08a1590-d698-4e1c-a148-c0ff4aea8d8f)
Click the nested link in the results page, the BG job triggered,
BG job completed, view the results using that nested link
![image](https://github.com/user-attachments/assets/4dbf9b34-0d53-42b2-a903-9ee16ea515ea)
![image](https://github.com/user-attachments/assets/163c2931-df4a-4942-b27d-ebc7547ba014)
View the results, that search also has a link
![image](https://github.com/user-attachments/assets/b0fa1684-e2b5-409d-b0fc-220a128bae75)
click that link
Results displayed
![image](https://github.com/user-attachments/assets/644dc161-30b4-4626-ab91-6d1363aa1e0c)

**Comment by kilam005** [comment]
@ThulasiP3 
please check and provide your closure

**Comment by ThulasiP3** [comment]
Fix verified in NESTE.Error not displayed
