### ISSUE TITLE
ADS- Custom Date  isnt working properly for datetime data in searches-NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#176]
**Describe the bug**
1.Pulling up a datetime column in query.
2.Setting a custom date format option in search configuration.
3.On running the results the search actually displays the day instead of the date.

![image](https://github.com/user-attachments/assets/c16f7931-b670-496d-81df-27e4dca81564)
![image](https://github.com/user-attachments/assets/df3637d5-49a9-41ca-a638-b09b468e27f0)

**Additional context**
Build no :2024.09.45542_P5
Region :https://neste-dev.platform3solutions.com/
Client :NESTE

**Comment by harsha-kotha** [comment]
Please add RCA details.

**Comment by Udhayanila8** [comment]
**_Server: https://uat-ads.platform3solutions.com/
Version: 2024.09.45542_P6_**

Custom date field working properly.
In the result field give the custom date format
![image](https://github.com/user-attachments/assets/94e9fea5-e6a6-49c0-a3ab-4acba823fdff)
BG search performed
![image](https://github.com/user-attachments/assets/43d827e2-e27e-4ee6-a1cf-d0bf6d7badd1)
![image](https://github.com/user-attachments/assets/4b3bcce2-db46-44c5-8805-c0c710f9c41c)
BG search completed
![image](https://github.com/user-attachments/assets/f8239458-6d98-43a1-aa41-34f4675f41cd)
Results displayed in the given custom date format
![image](https://github.com/user-attachments/assets/14f7af41-7c46-4ae0-97bb-4461d6d2e01a)

![image](https://github.com/user-attachments/assets/9e9db631-f880-4683-81af-974c4839ee29)
![image](https://github.com/user-attachments/assets/9f0b45ea-8835-49ef-a69f-a20e62694c20)
Short
![image](https://github.com/user-attachments/assets/ebef9d26-7deb-4728-aa5a-771eb54ed1af)
Medium
![image](https://github.com/user-attachments/assets/d605d21a-2b61-4ebc-a9e4-484e55d5e104)
Short and medium
![image](https://github.com/user-attachments/assets/9496193b-101b-4f35-bd2a-2b2257b880e8)
Long and full
![image](https://github.com/user-attachments/assets/f1aa7232-3ce9-4abf-96fa-2233ac2b0b96)
Custom
![image](https://github.com/user-attachments/assets/9391052d-03af-4547-9167-0a3f3c6a415d)
![image](https://github.com/user-attachments/assets/d441e2de-4a99-4719-96a6-331d5198c4a5)

**Comment by kilam005** [comment]
@ThulasiP3 
please check and provide your closure

**Comment by ThulasiP3** [comment]
Issue fixed in NESTE..
