### ISSUE TITLE
ADS-Background Search- Background Search-Taking Longer Time - ABB

### ISSUE THREAD

**Issue by AshsubM** [P3-Core-Dev-Team/P3-Q-A#177]
**Describe the bug**
The Background Search is taking longer time than usual.

![image](https://github.com/user-attachments/assets/a501ab92-747b-4a7d-a942-a580baa55031)

Before Deployment it  hasn't took this much time for the seaches , but now it is taking longer time

Build no :2024.09.45542_P5
Region : https://dev.ads-platform3.elis.abb.com/login
Client : ABB

**Comment by AshsubM** [comment]
@ClementJosh21 This is a CRT search, it  fetch around 1494958 records from the TABLE name INDEX.
The total number of records in the INDEX tables is 15028389

**Comment by ClementJosh21** [comment]
@AshsubM Records seems to be huge. Job got completed or you are still facing the same issue?

**Comment by Sethu-P3** [comment]
We have taken the time stats report for all searches .It didnt went to background search. Totally we have 5 different searches and here attached the time stats report for these searches.
[ABB TIME Stats - Sheet-finall.pdf](https://github.com/user-attachments/files/17840635/ABB.TIME.Stats.-.Sheet-finall.pdf)

**Comment by AshsubM** [comment]
Yes, Before the deployment, the Search limit Configuration was set to Custom Limit of 10000, and the stats for the each search results were taken with that  limit configuration. 
So post deployement when we performed the search we found there were some time differences, then we checked the Search Limit Configuration  was updated to No limit, and that's the reason for this time difference.
Will check with the team and provide the update
