### ISSUE TITLE
ADS-End user has search edit access in list view-NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#179]
**Describe the bug**
On logging in as enduser able to see Edit search option in list view.

![image](https://github.com/user-attachments/assets/ff1af170-c624-45c5-9929-66ccfc775957)

**Screenshots**

**Additional context**
Build no :2024.09.45542_P5
Region :https://neste-dev.platform3solutions.com/
Client :NESTE

**Comment by prakash-kandasamy** [comment]
`✏️ Description or RCA`
      Cross-app search permissions override individual search permissions.

**Comment by santhanakumari15** [comment]
**Server:** https://uat-ads.platform3solutions.com/login
**Version:** 2024.09.45542_P6

**Working as expected and the Enduser doesn't have search edit access in both the list and grid view**
**For cross-app search:**
- **If the end-user has read access, they cannot have edit access.**
- **If the end-user has to write access, they have edit access.**

![image](https://github.com/user-attachments/assets/14720166-51f7-409a-9fd1-14710cdb65e8)

## List view**
**Applications**
![image](https://github.com/user-attachments/assets/a65c98c9-46cb-4e5c-b050-fee38806d22d)
**Searches**
![image](https://github.com/user-attachments/assets/5cbee658-ba40-47e1-a08d-b20bd0c87db7)
**Crossapp search**
When Enduser has read access
![image](https://github.com/user-attachments/assets/457fd8a6-1191-420a-a786-ef745fcc186b)
When Enduser has read access
![image](https://github.com/user-attachments/assets/200cd5aa-b8fa-491b-b3df-d413b70b3ff9)


## Grid view
**Applications**
![image](https://github.com/user-attachments/assets/5f938959-0745-43b5-95b9-abfade63fa91)
**Searches**
![image](https://github.com/user-attachments/assets/8f2385dd-e3e3-435a-9664-8134ec881ef4)
**Crossapp search** 
When Enduser has read access
![image](https://github.com/user-attachments/assets/1c6ea6ea-f4c7-474a-b305-8d2b7c05b165)
When Enduser has write access
![image](https://github.com/user-attachments/assets/b36ada48-0de2-4d77-b468-5a4fc25fbd6f)

**Comment by ClementJosh21** [comment]
PR has been merged, the feature changes will be available in the version `2024.09.45542_P7`

**Comment by santhanakumari15** [comment]
**Server:**  https://dev-support.platform3solutions.com/login
**Version:**  2024.09.45542_P7

## Working as expected
- The end user doesn't have search edit access in both the list and grid view.
- For cross-app search:
    If the end-user has read access, they cannot have edit access.
    If the end-user has write access, they have edit access.
- Below mentioned privileges are added to ADP_ROLE_ADMINISTRATOR, ADP_ROLE_DEVELOPER
    1. Cache clearance - ADP_ACTION_SEARCH_CACHE_CLEAR 
    2. Import - ADP_ACTION_IMPORT_CROSS_APP_SEARCH*
    3. Export - Owner/Write + ADP_ACTION_EXPORT_CROSS_APP_SEARCH*
These privileges are working as expected, allowing users to access the related features.

**List view**
![image](https://github.com/user-attachments/assets/9a2ea504-53ab-4037-9cdc-10e0ac3602a5)
**Grid view**
![image](https://github.com/user-attachments/assets/5e4a386a-e11c-4add-9a38-e889d191d8c2)

All cases are working as expected, and the corresponding screenshots have been added to the documents below.
[Issue 179.docx](https://github.com/user-attachments/files/17993540/Issue.179.docx)

**Comment by kilam005** [comment]
@ThulasiP3 
please check and provide closure

**Comment by kilam005** [comment]
@ThulasiP3 
Issue #180 which is the duplicate of this (but in ABB environment) has been checked and closed.
Please test and update.
If no update is made issue will be marked auto closed on 20th Dec with reference to confirmation in issue 180.

**Comment by ThulasiP3** [comment]
Issue resolved in NESTE..closing the issue
