### ISSUE TITLE
ADS-End user has search edit access in list view - ABB

### ISSUE THREAD

**Issue by AshsubM** [P3-Core-Dev-Team/P3-Q-A#180]
**Describe the bug**
On logging in as enduser able to see Edit search option in list view.

![image](https://github.com/user-attachments/assets/a579ac79-be65-4d19-8426-9cf10b182cb9)

Build no :2024.09.45542_P5
Region : https://dev.ads-platform3.elis.abb.com/login
Client : ABB

**Comment by kilam005** [comment]
duplicate of issue #179. will be addressed there.
Please check and add issue that are not duplicate.

**Comment by kilam005** [comment]
Tracked as part of #179

**Comment by santhanakumari15** [comment]
**Server:**  https://dev-support.platform3solutions.com/login
**Version:**  2024.09.45542_P7

## Working as expected
- The end user doesn't have search edit access in both the list and grid view.
- For cross-app search:
    If the end-user has read access, they cannot have edit access.
    If the end-user has write access, they have edit access.
- Below mentioned privileges are added to ADP_ROLE_ADMINISTRATOR, ADP_ROLE_DEVELOPER
    1. Cache clearance - ADP_ACTION_SEARCH_CACHE_CLEAR 
    2. Import - ADP_ACTION_IMPORT_CROSS_APP_SEARCH*
    3. Export - Owner/Write + ADP_ACTION_EXPORT_CROSS_APP_SEARCH*
These privileges are working as expected, allowing users to access the related features.

**List view**
![image](https://github.com/user-attachments/assets/9a2ea504-53ab-4037-9cdc-10e0ac3602a5)
**Grid view**
![image](https://github.com/user-attachments/assets/5e4a386a-e11c-4add-9a38-e889d191d8c2)

All cases are working as expected, and the corresponding screenshots have been added to the documents below.
[Issue 179.docx](https://github.com/user-attachments/files/17993540/Issue.179.docx)

**Comment by kilam005** [comment]
@AshsubM 
please check and provide closure

**Comment by AshsubM** [comment]
Hi Team,
Now, The End user doesn't have search edit access in both the list and grid view  hence closing the issue
