### ISSUE TITLE
ADS-Unable to apply Partition and Bucketing-ABB

### ISSUE THREAD

**Issue by AshsubM** [P3-Core-Dev-Team/P3-Q-A#181]
**Describe the bug**

Couldn't able to apply Partitioning and Bucketing.
Partitioning:
![image](https://github.com/user-attachments/assets/e534bf04-5a07-48e1-be52-a3371aa63448)
Bucketing:
![image](https://github.com/user-attachments/assets/b6704b63-6c4e-44fa-9911-16b08d868d26)

Build no : 2024.09.45542_P6
Region : https://ads-platform3.elis.abb.com/     -- PROD
Client : ABB

**Comment by kilam005** [comment]
The issue has been idetified and a fix is already in place.
This fix will be rolled out in 2024.09.45542_P7 build

**Comment by ClementJosh21** [comment]
##
`✏️ Description or RCA`
On applying partition a query was formed for validation, on retrieving the result a invalid casting was made which caused the failure.

##
`👨🏻‍🔧Fix Provided`
The invalid casting was identified and removed.

##
`📑 PR Link`
[3447](https://github.com/P3-Core-Dev-Team/ADS_BE/pull/3447)

**Comment by Udhayanila8** [comment]
**_Server: 192.168.56.146
Version: 2024.09.45542_P7_**

**Able to apply partition and bucketing before and after ingestion**

Before ingestion apply partition and bucketing
![image](https://github.com/user-attachments/assets/8ff51e44-cf2f-4a7a-9258-abb3d72c4cbc)
![image](https://github.com/user-attachments/assets/0556cb9b-4109-4ff7-9df4-8ba2954e126a)
![image](https://github.com/user-attachments/assets/859432ef-40a1-4c27-9205-43b5074c18d0)
Also applied in a string column
![image](https://github.com/user-attachments/assets/4675d61a-f05a-44ff-b1d7-6fea96eb96b1)
Also applied partition for decimal data
![image](https://github.com/user-attachments/assets/da1172c0-0ba0-47f6-8d3f-fc745c36723b)
Apply partition for datetime column
![image](https://github.com/user-attachments/assets/a17794d9-ddd6-4685-ab1d-e5c086c6eac1)
![image](https://github.com/user-attachments/assets/d8e460b0-6fb7-4275-9fb0-cd978829124f)
Double data type not supported for partition and bucketing
![image](https://github.com/user-attachments/assets/8caa1b56-d35c-4673-905d-1f7494953df9)
Blob not supported for partition and bucketing
![image](https://github.com/user-attachments/assets/f8536711-1ce6-44ad-bcee-3126cd7fa08a)
Boolean is not supported for partition and bucketing
![image](https://github.com/user-attachments/assets/b05069b2-1a25-4fd6-b44a-c4d956398fe0)
Trigger ingestion for that
![image](https://github.com/user-attachments/assets/0ee45cf0-53b6-480d-acdd-c8b2c5efbebb)
Ingestion completed successfully
![image](https://github.com/user-attachments/assets/ed963b4b-4900-48e4-995e-799ca1cee460)
After ingestion run the partition and bucketing job
![image](https://github.com/user-attachments/assets/30c07b25-7ed5-4d3a-9373-9111c3bea519)
![image](https://github.com/user-attachments/assets/b2b9b740-3a47-4718-9fbb-1d6e46c8d5c1)
Completed successfully
![image](https://github.com/user-attachments/assets/6393a9be-1ac2-45ce-8578-9123d64c5a5d)

**Comment by AshsubM** [comment]
Hi Team, now able to apply Partition and bucketing in this latest patch P7, Hence closing this issue.
