### ISSUE TITLE
ADS-Export Data incorrect when Custom date feature is used in searches-NESTE

### ISSUE THREAD

**Issue by ThulasiP3** [P3-Core-Dev-Team/P3-Q-A#184]
Having the custom-formatted Date Time column in a search .On export the data is fetched directly from the database , rather than using the format displayed in the UI.Tried export both in Excel and CSV

![image](https://github.com/user-attachments/assets/4476a649-b63d-4643-b1ba-874925d7d152)
![image](https://github.com/user-attachments/assets/f577fc31-4911-4a70-a48d-df8fffdcf994)
![image](https://github.com/user-attachments/assets/6a4c3c2f-4735-4292-beb1-b54d8fa7da76)
![image](https://github.com/user-attachments/assets/3d578799-06a4-4de6-8515-c1bb3f023032)

**Additional context**
Build no : 2024.09.45542_P6
Region : https://neste-dev.platform3solutions.com/
Client : Neste

**Comment by kilam005** [comment]
@ThulasiP3 
The custom date format is used to render info on UI only and not for export.
This was communicated to Rani during the development of the feature.

The date should be in `DATE` or `DATETIME` data type from query to enable proper sort, filter and to active the custom date format parsing. The custom date is only for usage in UI rendering.

### The following is a reference from IA (Version - 22.3) too.
**Configuration and Exported data**
![image](https://github.com/user-attachments/assets/276b5a5e-923b-4887-8822-50861a1a69bd)

**Search result in IA**
![image](https://github.com/user-attachments/assets/4d6014cc-3420-4d35-9414-3042deb4b820)

**Exported CSV viewed from Notepad++**
![image](https://github.com/user-attachments/assets/a7bb41b5-8e10-4b0d-86f8-010670f133a7)

_To enable export in a specific format_, you need to format the date directly in query and render result as in the needed format and not use the custom format option.

Note:  
When you use any custom date format, the sort, filter and other date specific functionallity on the column may not work correct. That is why IA or ADS would not be able to support this except in UI rendering.

Based on the above reasons, the issue will not be considered valid.

**Comment by ThulasiP3** [comment]
Closing the Issue based on the above comment.This is the product behaviour
