### ISSUE TITLE
ADS-BLOB - Unable to view the blob content - ABB

### ISSUE THREAD

**Issue by AshsubM** [P3-Core-Dev-Team/P3-Q-A#185]
**Describe the bug**
After ingesting the blob(PDF file) data , i'm unable to view the blob file

Blob Unable to view:
![Abb Blob unable to view issue](https://github.com/user-attachments/assets/f3d05c39-d14e-4293-aac5-50edaec2e672)

Backend Response:
![BE response details](https://github.com/user-attachments/assets/72dfa39a-397b-44dd-a157-cfc0b77e0828)

Blob API download Success:
![Blob Api Download Success](https://github.com/user-attachments/assets/fba3c538-1052-49b4-9371-bd3f984b25d3)

Front End console error:
![FE console error](https://github.com/user-attachments/assets/78ea0e7a-d81c-4f59-aa56-bec6e0e634ec)

Verified with another brower aswell:
![Verified with bravebrowser as well](https://github.com/user-attachments/assets/d77820fb-0539-4b6a-834c-b8ee5cc43f2c)

Currently P7 tag is deplyed on ABB both Prod and Non-Prod environment.

I have checked the same in the Non-Prod environment , here i can able to view the blob without any issues.

**Additional context**
Build no :2024.09.45542_P7
Region : ABB-PROD
Client :ABB

**Comment by akhilkottedi** [comment]
When Pentest deployment developement team ask to add error page property in web.xml file at apache tomcat conf and informed to update same in all region, so we have updated in abb prod but now we removed that error page property in web.xml.

**Comment by AshsubM** [comment]
Now Able to view the blob file properly in PROD ADS,
![image](https://github.com/user-attachments/assets/af6fdc38-ce31-41fa-b0c2-16ac5519a212)

hence closing this issue.
