### ISSUE TITLE
Error : Data Not Ingested

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#2]
Environment - Pulte New Dev ADS 3.1.7

https://archon-datastore.platform3solutions.com/pulte/dev/login

When a Search is performed with non-matching record, incorrect error is shown "**Data Not Ingested**"

**Comment by harsha-kotha** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/42184278/b79aba72-c459-41eb-a591-b4ed91f507e6)

**Comment by kilam005** [comment]
The bug is acknowledged.
It will be addressed.
Details will be shared in this issue.

**Comment by Udhayanila8** [comment]
Issue has been fixed. Tested in EMR region.

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/9b61a396-cd5d-45f6-aba9-1e530b07abbe)

**Comment by sowndaryameiyazhagan** [comment]
RCA:  custom exception was thrown when searching with non matching record ,now it's rectified, if it is a non matching record the search will be empty

**Comment by harsha-kotha** [comment]
Thanks
