### ISSUE TITLE
Job Management - In Mode Column, icons Need to be more highlight(Set Theme as Deep Purple)

### ISSUE THREAD

**Issue by Udhayanila8** [P3-Core-Dev-Team/P3-Q-A#21]
**Logged by:** Santhanakumari
**Server:**
146
**Module:**
Job Management
**Steps:**
1. Login (User Name : sandy_dev, Password: sandy_dev_D3F@ult)
2. Go to Theme
3. Set Theme as Deep Purple
4. Go to Job management

**Expected Result:**
 In Mode, icons Should be highlighted

**Actual result:**
 In Mode column , icons are not highlighted 

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/d1601cd5-4125-42ab-8789-5db6999ab84b)

**Comment by prakash-kandasamy** [comment]
Issue fixed in 219 region, Pls check



![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/79510599/97a16464-72c2-4f85-802d-0d4216499b5f)

**Comment by Udhayanila8** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/5fa4446b-970f-4c7c-bd63-d58df9ed3837)
 Reopened the issue, because  its not shown properly as per expected.
 Tested in 146 server, by Santhanakumari.

**Comment by Udhayanila8** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/fabb6049-f937-4b9c-9857-340efbb6af18)
Issue resolved and working fine as expected tested in 146  server, by santhanakumari
