### ISSUE TITLE
Export not working as expected

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#22]
Have set the custom limit for the screen  as '10'. The search result is 10 but it is exporting all records while exporting
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/e9ab8cf5-53cb-4673-be52-517aadbd7037)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/33328b0e-cfc5-48cc-a010-2c1d066521a5)

**Comment by harsha-kotha** [comment]
**There was a similar issue : Export Select all has more number of records than selected #13 --> Same repo. The issue was supposed to be fixed and closed. Why is the earlier reported issue which was fixed and closed is re-occuring?**

**Comment by suseela22** [comment]
The tested server is http://192.168.1.218:4081
**Note:** This was tested and reported by the team on 16/10/2023

**Comment by ClementJosh21** [comment]
@suseela22  
The latest code were only deployed on 19/10/2023 can you re-check once and confirm this.

**Comment by harsha-kotha** [comment]
@ClementJosh21 pls mention what was the earlier release that was available in the environment and what is the current release that is deployed? like 3.1.7.12102023.

We need to make sure that we are not wasting team's time in testing old build. Please double check and confirm.

**Comment by kilam005** [comment]
@ClementJosh21 
What is the current status of this. Please update info. Its pending without reply for long time.

@Udhayanila8 / @SivaMahendran17 Please add your response if verified.

**Comment by ClementJosh21** [comment]
@kilam005 The fix is available in the version 2020.01.x, @Udhayanila8 can you confirm the validation status?

**Comment by Udhayanila8** [comment]
Export values match the selected custom limit results. Tested in 146 server.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/e39dad84-c063-4a7e-a4ea-4b92ffe4828b)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/bdbe586f-0492-4ef5-977a-1aa27a024b63)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/a4daefd6-e60f-4410-887a-86f0c0dae666)

**Comment by Udhayanila8** [comment]
@harsha-kotha, selecting all records in a page. Added screenshots for your reference.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/b2fa5c60-746e-4f18-9933-bafc9c72e339)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/010f0356-011f-43db-b2ef-3cee73f28665)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/752e5102-6608-41bd-aea6-f90ae7de91ec)

**Comment by kilam005** [comment]
@harsha-kotha 
Please check the above comments and provide closure.

**Comment by kilam005** [comment]
@harsha-kotha awaiting your response.

**Comment by kilam005** [comment]
`Fix details`
Testing was done prior to deployment on the server for the creation of this issue.
Refer to fix in #13

**Comment by harsha-kotha** [comment]
@suseela22  Please check this issue and confirm.

**Comment by suseela22** [comment]
Working as expected

**Comment by kilam005** [comment]
@harsha-kotha check above statment and conclude the issue soon.
