### ISSUE TITLE
Partitioning not working

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#23]
Ingestion is getting failed after one set is completed

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/4ad9e7f2-721a-4d7e-824f-c3da34f8318e)

**Comment by sowndaryameiyazhagan** [comment]
BE pr link: https://github.com/P3-Core-Dev-Team/ADS_BE/pull/1944

**Comment by sowndaryameiyazhagan** [comment]
RCA : the bucketing /partitioning option will disabled once ingestion done


![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/83161895/c3502cc3-ad6c-426c-b767-5e428f207479)
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/83161895/f93d4ddf-4ec7-4632-835f-69e1b7f50689)

**Comment by Udhayanila8** [comment]
Once the ingestion done. partition and bucketing was disabled.

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/06ba7dab-d1d9-4af5-98ff-4acc87f9c394)

**Comment by ClementJosh21** [comment]
@kilam005 The fix available in version 2024.01.x version.

Now we can change partition even after ingestion and also will ingest multiple sets without any error even if partition(s) is applied

@Udhayanila8  Can you re-check this once and attach the valid screenshot here?

**Comment by kilam005** [comment]
@ClementJosh21 
please provide RCA and fix info for this

**Comment by suseela22** [comment]
Working as expected
