### ISSUE TITLE
Sort/Filtering is disabled for date field in result

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#24]
If the data type is date then the sort/filter is disabled in the result

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/78e79dfa-f94f-43de-a685-89c816d78d99)

**Comment by sowndaryameiyazhagan** [comment]
RCA : added filter and sorting option for date column
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/83161895/84d4e2b6-6ffb-4c17-8934-97df887ecde0)

**Comment by Udhayanila8** [comment]
Working as expected

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/d723a9c5-c52b-48aa-88d0-ef4893651a45)

**Comment by kilam005** [comment]
@Udhayanila8 
please retest and reconfirm this in the expected 2024.01.x version

**Comment by Udhayanila8** [comment]
Able to apply sort and filter for date and datetime datatypes. 
Tested in 2024.02.45353 version.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/042de56a-ad24-4b72-b0d8-9fe5782c009c)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/a057ff29-a4c3-4f4d-b629-646e8c224628)

**Comment by kilam005** [comment]
`RCA`
Data column was missed to be added in the list that should enable sorting and filtering

`Fix details`
Added filter and sorting option for date column

please check and provide closure

**Comment by suseela22** [comment]
Working as expected
