### ISSUE TITLE
Forgot Password not working

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#26]
Email server is not configured in 192.168.1.218  server

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/7f6cc941-76b9-43ad-9c61-79c3bd3caf38)

**Comment by Deepika-ar** [comment]
Informed to @suseela22 for configuring a Email. @suseela22 can you check confirm this.

**Comment by suseela22** [comment]
@Deepika-ar  It is not working

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/557117b4-a4b3-4ca6-b1c5-d0b622af60b0)

**Comment by Deepika-ar** [comment]
![Screenshot from 2023-11-09 15-52-16](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/87174786/0ae2ec01-8185-4b1c-b596-f96524400902)
![Screenshot from 2023-11-09 15-49-47](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/87174786/c87f6da4-f7f2-4e52-a416-e881b245bfda)

**Comment by Udhayanila8** [comment]
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/34dd2a01-af9b-4052-bf0f-16d481c5842c)



![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/942f18bf-7ae9-413b-ac97-5ca83e216179)



![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/3ccf7e2f-9337-48ed-b869-158b02ba13b1)





![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/828711ae-be50-4672-9222-d683ad141066)


![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/e58bd457-5a02-48e7-817d-a5d873b6b975)


![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/b2a6ec06-5574-4747-b2b8-f28f224441c4)
Issue resolved working as expected tested in 146 server by santhanakumari

**Comment by kilam005** [comment]
@Deepika-ar  / @ClementJosh21 can you add the RCA and/or fix details made to reolve this
