### ISSUE TITLE
Null in Export file

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#3]
Environment - Pulte New Dev ADS 3.1.7

https://archon-datastore.platform3solutions.com/pulte/dev/login

App : test
Search : test123

Selected record export in csv format show "Null" it should not be the case. Exported column should be blank.

ADDR_ID | IS_PROV | ADDR_TYPE

90001 | **-NULL-** | F

**Comment by kilam005** [comment]
This behavious as been like this from the start.
This will be corrected in the next release

**Comment by harsha-kotha** [comment]
Fine, please correct and let know for retest.

**Comment by Udhayanila8** [comment]
Issue has been fixed. Tested in EMR region.

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/c6359c83-3b58-4c90-b127-7c19ceb62150)

**Comment by sowndaryameiyazhagan** [comment]
RCA: if the data is empty it was treated as null while export csv report . In the next build if the data is empty it will be a empty row

**Comment by harsha-kotha** [comment]
Please mention build number when this fix will be available.

**Comment by sowndaryameiyazhagan** [comment]
it will be available in V_3.1.7

**Comment by kilam005** [comment]
@harsha-kotha  
this was avaialble in 3.1.7 version and is already moved to all region where we have deployed version 3.1.7_x.
All the regions we gave you for testing has version 3.1.7_x.

Please check once and confirm the fix.

**Comment by kilam005** [comment]
@harsha-kotha 
expecting a closure on this issue or a comment on why this is still unclosed

**Comment by harsha-kotha** [comment]
Closing the issue assuming the fix is propagated properly without any build issues like previous time.
