### ISSUE TITLE
Date Range Issue in search

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#31]
When 2 different containers are used in the search, the date range is not working

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/a74b48d9-3b76-4c9f-9084-f4dbb20e7932)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/70f65fc0-e0ad-4087-bebb-ce1628b0fcae)

**Comment by Vijayakumar-Periyasamy** [comment]
issues fixed in local 
<img width="1436" alt="image" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/125446452/e62332da-77aa-483e-abf4-43277dccf5f3">

**Comment by Vijayakumar-Periyasamy** [comment]
issues fixed in 219
<img width="1439" alt="image" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/125446452/5087b1a1-8645-47ee-9b10-3b9e274e4664">

**Comment by Vijayakumar-Periyasamy** [comment]
issues fixed


![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/125446452/c9696482-6538-46a9-9be2-1c663c143e45)

**Comment by Vijayakumar-Periyasamy** [comment]
create or edit a search.

Search form tab inside Add 2 different containers to the search. any one container inside add the date range field. Then perform the search, but here the date field value  passed "object object".
It's a looping issue. Now it's fixed the issues.

**Comment by Udhayanila8** [comment]
The issue has been fixed. Tested in 146 server.
I have added 2 containers, and also added 2 date range field then performed the search.
It is working.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/64e5bfa9-6727-4f28-a30e-730995dd12db)

**Comment by Udhayanila8** [comment]
Added 2 containers and added the date range in both containers, performed the search, and again edit the search. 
Able to perform.
Tested in 218 region - http://192.168.1.218:4081
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/c8449085-6aab-49c8-85dd-6d0adc7c132b)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/b44f5da4-174d-41fa-90ed-9c1781edab9d)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/37a1de76-c760-4e82-9457-12a5d950bf1e)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/9364b815-cc08-4c7a-9d45-e29d5c92c44a)

**Comment by kilam005** [comment]
The fix is available in the latest build provided to you (@suseela22)
Kindly check and provide closure

**Comment by suseela22** [comment]
Working as expected
