### ISSUE TITLE
CSV ingestion - Report/Message error

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#34]
In Job status the status is showing completed message but data is not Ingested.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/6025e96f-ee42-4f12-a5e7-ed504032cc09)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/318cefc1-e46d-4b5a-ba92-4533e0138d23)

**Comment by kilam005** [comment]
@Surinarayanan please have vijay or vikram check the issue and report the findings

**Comment by kilam005** [comment]
@ClementJosh21  need details on the fix added.

**Comment by Udhayanila8** [comment]
It throws the exception for mismatched date time format. Tested in 146 server
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/8b715c19-c634-4a3f-ac8a-83d5b0865bd3)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/c70a920a-68f3-4e9e-941d-5daf7cee3290)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/18118350-5ffe-4703-80d8-664a572fdfda)

**Comment by kilam005** [comment]
This fixes are ready and verified.
This is planned to be avaialable in version 2024.01.x

**Comment by kilam005** [comment]
@suseela22 

The issue is fixed in the latest version 2024.01.x which is updated in the region given to implemention team.
Kindly check and provide closure

**Comment by suseela22** [comment]
Working as expected
