### ISSUE TITLE
ADS query - Case condition not working as expected

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#35]
There are 3 different cases to be achieved in the query. The query shared by the product team is not working as expected. As per clement statement it requires a backend fix.

**Xquery:**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/09ac1a9a-9e0b-4fcc-8d93-4d3716154cb8)

**ADS query shared by the product team**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/8f3a019d-d295-4664-b383-7ca3578edb86)

**Comment by ClementJosh21** [comment]
@kilam005 Previously, if there were multiple binding values kept between '@@' only a single binding value will get replaced under one condition if the value is passed in the payload. We have modified to replace every binding values between '@@' even if the payload is not passed by the user.

**Comment by Udhayanila8** [comment]
Issue fixed. Tested in 146 server, Able to give multiple binding values.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/5a576d99-7f69-44d8-abbf-0d5d9b68ac2c)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/5b5afd5f-01d2-4e81-b1fa-97dc2b347f50)

**Comment by kilam005** [comment]
This fixes are ready and verified.
This is planned to be avaialable in version 2024.01.x

**Comment by kilam005** [comment]
@suseela22 

The issue is fixed in the latest version 2024.01.x which is updated in the region given to implemention team.
Kindly check and provide closure

**Comment by suseela22** [comment]
Working as expected
