### ISSUE TITLE
Field Label - character length issue

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#36]
The field label is accepting only 20 characters. If there is a requirement having the label name more than 20 characters it will become an issue

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/d19c5bf8-1266-4e1b-9048-76c081dd17f1)

**Comment by kilam005** [comment]
@suseela22 
I'm planning to increase this to upto 30. 
Kindly confirm if this is ok else what should be the ideal expectations?

**Comment by kilam005** [comment]
@suseela22 
Kindly confirm the ideal max character length.

**Comment by suseela22** [comment]
@kilam005 There is no such limitation in IA for Label or binding name. I could not able to conclude to have max of 30 characters.  Can't we give infinite? Does the max limit is playing major role? If so this needs a discussion with my team.

**Comment by kilam005** [comment]
It is part of best practices. To avoid bloating.
in DB also there is a limit for each data type. So as part of validation pen test team recommended we have some max limits.
Also if there is infinite character acceptance, i can wantedly make the field take 1GB worth characters. 
Also the UI appearance and rendering should be considered.

So please discuss with the team and get the max definite and considerable value.

**Comment by kilam005** [comment]
@suseela22 
awaiting final confirmation over this.

**Comment by kilam005** [comment]
@suseela22 
Please provide info or i'll have this length fixed to 30.

**Comment by suseela22** [comment]
Please have the characters fixed to 30 now. Have discussed with the team, so far we don't have any column having more than 30 characters. If we ran into new case in the upcoming project we will request for an enhancement.

**Comment by kilam005** [comment]
This is currently in testing phase

**Comment by yowanrajan** [comment]
<img width="1052" alt="Screenshot 2024-03-27 at 3 03 39 PM" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/43135572/078e2eed-2b13-420c-97a0-5aa9ff7c9e80">

Max character length 20 to changed 30

**Comment by kilam005** [comment]
@ClementJosh21 :
Was the Verification done for this change in BE side?

**Comment by ClementJosh21** [comment]
@kilam005  The issue has been address in BE and attaching the PR link [here](https://github.com/P3-Core-Dev-Team/ADS_BE/pull/2617).

**Comment by kilam005** [comment]
@prabhakaranUI / @ClementJosh21 
Let me know when this version is avaialble for release.
ALso include details on which version this is going to come?

@Udhayanila8 please test and provide verified tag

**Comment by Udhayanila8** [comment]
Maximum characters fixed as 30 now. Fixed in 146 server. Tested in 146 server.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/6399d17f-1729-46ae-8cfb-ae1a8893daaf)

**Comment by kilam005** [comment]
@suseela22 we have update this and based on internal discussions, instead of 30 we have fixed it as 50.
Kindly check and provide closure

**Comment by kilam005** [comment]
`Fix Details`
Feature additions were included
