### ISSUE TITLE
Enhancement - Search Result - Moving result fields  from Main result to expanded result

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#37]
Move results from Main result to expanded result is not available. Results columns switch from main to expanded and vice-versa happens multiple times during requirement change

Reference screenshot from InfoArchive

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/3ddf6e81-2c04-44ef-be81-487e3674d37a)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/4ef926ef-6244-4004-a3a5-887f7f5800ef)

**Comment by kilam005** [comment]
This is UI only issue and can be addressed. Will be taken as enhancement.

⚠️ Two fields with the same label and binding name will not be made available in the same group (main or expanded container)
This may have to be indicated as error when implemented

**Comment by prabhakaranUI** [comment]
@kilam005  Development started @prakash-kandasamy

**Comment by kilam005** [comment]
@prabhakaranUI / @prakash-kandasamy  gave a demo early this week and I (@kilam005) have provided the necessary feedback to correct.

**Comment by prabhakaranUI** [comment]
@prakash-kandasamy gave a demo to @kilam005 yesterday, currently he working on the review correction
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/34a82564-3a19-4eb7-b995-359f319f3ac6)

**Comment by suseela22** [comment]
Demo has been given. Expectation was met. Please continue with your next step.

**Comment by suseela22** [comment]
Working as expected

**Comment by kilam005** [comment]
`Fix details`
This is new feature development designed as per discussions
