### ISSUE TITLE
Enhancement - UI change in search - Need for Filter by Search Type

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#39]
Need filters for search type -  basic search, advanced search, nested, group etc

**Comment by kilam005** [comment]
Options can be provided. 
It will make the UI a little cluttered so working with Daniel on it. 
Once planned it will be discussed for confirmation

**Comment by mdanielkumar** [comment]
Search lisiting mockup with search type filter
<img width="1105" alt="image" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/47356420/30b9a679-40e4-4c34-89a6-4c5697334bb0">

<img width="1105" alt="image" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/47356420/067c947b-de3c-41ac-864c-a834541680fa">

**Comment by mdanielkumar** [comment]
The 'manage categories' icon has been relocated inside the dropdown as a fixed button at the end. The label name has been updated to 'Category Filter / Management.'

**Comment by prabhakaranUI** [comment]
@mdanielkumar we have the same use case in Application compliance pls check and confirm because uniformity missing in this manage category change

<img width="1530" alt="image" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/d98ccc1c-f04f-47d6-83d6-9feaeab93356">

**Comment by mdanielkumar** [comment]
@prabhakaranUI As discussed pls go with the design i sent

**Comment by kilam005** [comment]
Team has obtained all necessary details to proceed for development.
This will be planned for dev in the next sprint cycle.

**Comment by kilam005** [comment]
@prabhakaranUI 
is this avaiable in 2024.01.x (effect tv version)

**Comment by prabhakaranUI** [comment]
@kilam005  fix available in 3.1.9 (2024.02.x)

**Comment by kilam005** [comment]
@prabhakaranUI 
what is the ETA release date for that version (2024.02.x)

**Comment by kilam005** [comment]
@Udhayanila8 please test once you have this release in your environment and confrirm the working.

**Comment by Udhayanila8** [comment]
**In the search type report search option is missing.**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/75b4fa1a-2824-4fef-b6f5-86e465757d6d)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/4ada916f-d1f1-4206-be94-5fa9b78e5bf3)
Category working fine
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/e7a997bd-c53e-49b8-ab4e-0bb6034bca7b)

**Comment by prabhakaranUI** [comment]
@Deepika-ar  report search is missing in the search type dropdown

**Comment by Deepika-ar** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/87174786/3ef3fdbf-7abf-4a4e-98af-bc5a538e5fa3)

**Comment by kilam005** [comment]
@Udhayanila8 please verify and report back

**Comment by Udhayanila8** [comment]
Tested in 146 server. Working.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/609a1b0a-0dd2-4e31-94e6-20162e34a78b)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/4a443610-a6fc-45b9-a015-c0f275bd01b4)

**Comment by kilam005** [comment]
@prabhakaranUI in which version is this avaialble?
is this already released?

**Comment by suseela22** [comment]
Can we add Nested Search, Primary Search , Cross-app Search with this list?

**Comment by suseela22** [comment]
@kilam005 Requested is raised for nested search filter and other search types also. Daniel mockup also shows the nested option. So I thought it will be with this feature request. Since it is not in this release I have added my comment. I can create it as new issue if required.

**Comment by kilam005** [comment]
@suseela22  Daniel gave a sample text for mock up. He is not aware of the details.

Search type are Basic, Advanced, Report and Group.
Nested search is a feature that prevents its from appearing for direct search.
The option for having this is only specific to user who will have search edit development mode access. 

There is no point of having this option for end user.
Its has to be taken in seperate track now.
Please create a new issue for the new need and test the working for the work done to list the search types (this issue) and  close it

**Comment by suseela22** [comment]
@kilam005 I will create new issue in that case. The filter for Search types (Basic, Advanced, Report and Group) are working as expected.
