### ISSUE TITLE
Export - Difficult to map my Export request in background job section

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#4]
Environment - Pulte New Dev ADS 3.1.7

https://archon-datastore.platform3solutions.com/pulte/dev/login

Any Export done in the application, i am not able to tag my request. There is no mechanism to find my Export request name and it becomes not possible to find my Export request in background section without our trial and error.

**Comment by kilam005** [comment]
The tool has always worked like this till now.
This will be taken as an enhancment request and treated.

**Comment by Udhayanila8** [comment]
Issue has been fixed. Tested in EMR region.

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/831dc658-7ce7-47b1-bbe2-1dc283812e79)

**Comment by sowndaryameiyazhagan** [comment]
Enhancement : in previous build the  job name generated automatically  for background jobs, Now  User can able to provide job name for all background jobs

**Comment by harsha-kotha** [comment]
Thanks
