### ISSUE TITLE
Enhancement - UI change in search - Save search as Draft

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#40]
Option to save searches in draft. Save option is required for each page while developing a screen. It is difficult to develop a screen in one shot

**Comment by kilam005** [comment]
Plan for "save as draft" as been discussed with the ADS team
The team will plan the development in the next  sprint cycle.

**Comment by ClementJosh21** [comment]
@kilam005 We have started the development work.

**Comment by kilam005** [comment]
@ClementJosh21 
As dicussed, below will be your implementation

- All searched created will be saved as available in Database when user attempts save
- If all Manadatory inputs are provided and Query is also correct, the save will be marked as Valid else it will be flagged invalid.
- All invalid searches will be maintained at Draft Status.
- All valid seacrhes will initially be in Draft status but user will get the option to make it Active (Published in IA sense)
- An active search can be set as inactive if needed.

⚠ Any change made to search configuration will auatomatiically mark the status as "Draft"

**Comment by Deepika-ar** [comment]
RCA: save searches as draft as per requirement.
![Screenshot from 2024-03-25 12-10-55](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/87174786/7a011a17-4c94-428d-a2bf-b43307f63004)
![Screenshot from 2024-03-25 12-11-42](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/87174786/20eeec4e-0ddc-4ff9-8b7b-814f0f337ab8)
![Screenshot from 2024-03-25 12-12-25](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/87174786/38581773-ab6d-47cc-9633-8daed5fae015)
![Screenshot from 2024-03-25 12-14-44](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/87174786/f71c9dad-cf4e-487f-8aab-496d20e528c3)

**Comment by kilam005** [comment]
show draft search with draft icon (next to the search's icon)
draft icon look something like `</>`

**Comment by kilam005** [comment]
wrongly closed by bot. so reopening

**Comment by kilam005** [comment]
@prabhakaranUI 
if this is ready for testing in any release version pass this to @suseela22 and get her review to close this issue.

**Comment by prabhakaranUI** [comment]
@kilam005  @suseela22 
Changes available in version 2024.02.* and deployed in test region http://192.168.56.146:4081

**Comment by kilam005** [comment]
@prabhakaranUI please give a demo to @suseela22 and confirm if the expectations are met.

**Comment by suseela22** [comment]
Expectations are met but the query validation was requested in the query editor page. @prabhakaranUI Please discuss with your team.

**Comment by prabhakaranUI** [comment]
@suseela22 
Team working on it will connect once it's done

**Comment by prabhakaranUI** [comment]
@suseela22 
As we discussed now we have an option to validate the query.
will connect and close this
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/873161aa-4346-4526-9fbf-f80bd2c53257)

**Comment by kilam005** [comment]
@prabhakaranUI 
Demo please proceed and give if needed
But the issue can be closed once after delivery and testing in their hosted region.

**Comment by suseela22** [comment]
Demo has been given. Expectation was met. Please continue with your next step.

**Comment by kilam005** [comment]
@suseela22 This feature request is avaialble in the release provide in 218 server. Kindly check and provide closure

**Comment by suseela22** [comment]
Working as expected

**Comment by kilam005** [comment]
`Fix Details`
Feature additions were included
