### ISSUE TITLE
Enhancement - Chain of Custody

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#44]
File upload is required (CSV/EXCEL) to run the COC for selective tables

**Comment by kilam005** [comment]
Pain points understood. 
Options can be facilated. 

The template will be decided together with Suseela and team

**Comment by kilam005** [comment]
@maheswarareddyi 
Please assist the team to get this feature implemented.

**Comment by maheswarareddyi** [comment]
@suseela22 The stakeholder discussions have been completed, and the requirements are being reviewed by the PO team, and we will send out a sign off request email by the end of the week or early next week. Following the stakeholders' approval, the requirements will be shared with the development team so that development can begin.

**Comment by kilam005** [comment]
The requirment document has been submitted for review and expected sign off by 10 April.

**Comment by maheswarareddyi** [comment]
@kilam005 @ClementJosh21 @prabhakaranUI
Please find the signed-off requirements [here](https://platform3solutionsllc.sharepoint.com/:f:/r/Shared%20Documents/02.%20PRODUCT/Archon%20Data%20Platform/Requirements/ADS_REQ_0034_Upload%20Schema%20Template?csf=1&web=1&e=0U2zGq) to plan the development activities

**Comment by kilam005** [comment]
Development is in progress

**Comment by kilam005** [comment]
Development complete. @ClementJosh21 Planning internal demo for feeback reviews.

**Comment by ClementJosh21** [comment]
Deployed in test-region (**_192.168.56.146_**) for testing team verification.

**Comment by kilam005** [comment]
First level testing completed.
Testing team raised Issue were fixed and is planned for second stage testing.
Planned to complete testing by EOW.

**Comment by kilam005** [comment]
Testing is partially completed and issues notieced were raised.
Currently testing team is awaiting on issue fixes to be deployed.
Testing to resume post update.

**Comment by Udhayanila8** [comment]
Upload schema template files working as expected, job completes when giving correct input in the template file.
If the wrong input is given, the Job fails and the report and UI display the error.

**_Tested server: 192.168.56.147
Version: 2024.06.45459_RC1_**

Given template file
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/c699641e-2656-4494-afd1-b11bdd69e48c)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/6fa638db-2dc2-4591-b3de-945a81d54120)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/cfca214c-57d7-4eba-a374-1db75ca1ed50)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/7de22b32-7d21-4267-9147-b05c23720fa9)
Able to download and view the same details in the report
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/c31ca0f1-d2ac-4193-b0bd-67fa001cb1dc)
Giving wrong input in the template file, error validation happened in 3 types. adding some examples in below,
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/58d4176c-a0be-42a5-a0cc-89c1374870bf)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/59d100a3-396a-4e8b-9633-15fb982d1175)
In Excel, reports show the error message
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/2796d8d2-78f8-40c7-833d-545ef844fdd9)
UI validation message also displays the error
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/2bbcf837-16cd-4b21-ae3f-ac1b02a61eba)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/d8421069-5c56-4a59-ac9a-fe32b2dca83c)
In the job message also displays the error message
When giving multiple tables in a single line
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f16ceeba-260e-4563-8ee9-eb466a72bbf6)
Giving multiple tables in a single box
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/c1070d89-02a7-4183-a3e7-1156a892d2dc)

**Comment by maheswarareddyi** [comment]
The feature is verified and will be rolled out in the upcoming release.

**Comment by maheswarareddyi** [comment]
@suseela22 This feature is available in ADS v2024.09.45542 on the 218 server in Chennai DC.
Please check and confirm the working and provide closure to this feature.

**Comment by maheswarareddyi** [comment]
@suseela22 Could you please provide the verification status of this feature? If no update is received from your end by October 21, 2024, the feature will be marked as closed.

**Comment by suseela22** [comment]
Working as expected
