### ISSUE TITLE
ADS-Search - Change Advance Search to Advanced Search - (DELL Issue)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#45]
Change Advance Search to Advanced Search

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/0e68483e-902d-41bc-b003-2a8cc44cc49f)

**Comment by kilam005** [comment]
Adding this ticket for tacking purpose.
Originally raised by Kavitha (Dell) via Rani on 12 Dec 2023

**Comment by kilam005** [comment]
@prabhakaranUI : Kindly update details.

**Comment by kilam005** [comment]
The fix is ready after testing. refer the link in previous comments.
It is planned to be made available in next release.

**Comment by kilam005** [comment]
Selva report the issue has been fixed and deployed on Effect TV. 
He had also showed the demo to Rahul on Feb 1st 2024.

**Comment by prabhakaranUI** [comment]
Fix was deployed in Effectv region on 1th Feb 2024.
https://github.com/P3-Core-Dev-Team/lwa-fe-v1/pull/1426
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/85214f3d-9f27-4e0c-9a73-843df1d52d10)

**Comment by prabhakaranUI** [comment]
<img width="1536" alt="Screenshot 2024-02-02 at 3 16 47 PM" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/5e28cb22-a13d-4fb1-ad6a-96ec849409ed">
<img width="1536" alt="Screenshot 2024-02-02 at 3 16 57 PM" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/ed91c6ca-e5ee-4513-ab2e-8cf6d5f85ffd">

**Comment by sumitraRaja** [comment]
Very minor -> Advanced searches or Advanced Search in the breadcrumb

**Comment by kilam005** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/7f50273c-4e03-43f7-9409-21c6595b4ffa)

The changes are made and deployed in Effectv environment.
WRT the previous comments and the screen shot above, closing the issue.

**Comment by kilam005** [comment]
`Fix details`
Typo error was corrected
