### ISSUE TITLE
ADS-Search - Date Range field type to work with from or to date

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#46]
Date Range field type > Should be able to work if FROM or TO date is provided

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/689d9a52-249b-4dfa-a11f-20a45ebe8489)

Adding this ticket for tacking purpose.
Originally raised by Kavitha (Dell) via Rani on 12 Dec 2023

**Comment by kilam005** [comment]
coverd as part of [#1348](https://github.com/P3-Core-Dev-Team/lwa-fe-v1/issues/1348)
The fix is ready after testing. refer the link above.
It is planned to be made available in next release.

**Comment by Udhayanila8** [comment]
As Malik mentioned this issue has been tested and closed already in 146 server. The issue link is [#1348](https://github.com/P3-Core-Dev-Team/lwa-fe-v1/issues/1348)

**Comment by kilam005** [comment]
This has been deployed in Effectv region.
Require Closure sige off from Rani

**Comment by kilam005** [comment]
`Fix details`
Date range was customized to work as per request

**Comment by Udhayanila8** [comment]
**Tested in 3.1.7 version also, 
Server: 192.168.56.172**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/45d92073-c4eb-437b-a023-32f0dd75d685)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/3eae610a-69b8-4c90-8ee5-b13ef8d0e3be)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/e4f0da0c-477b-4420-b601-de1ede757ce2)

**Comment by Udhayanila8** [comment]
Working in 2024.01.45313_P1 version also. Tested in 146 server.

**Comment by raniangamuthu** [comment]
Tested and verified with start or end date to be optional.

**Comment by kilam005** [comment]
Based on above comment closing the issue
