### ISSUE TITLE
ADS-Search - Dropdown values from database (Dell) (Product Functionality Request)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#47]
Dropdown values from database

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/791d02f7-6d78-43c8-ad54-9f2104d9c4f6)

Adding this ticket for tacking purpose.
Originally raised by Rani on 18 Dec 2023

**Comment by kilam005** [comment]
_`[Product Team] (22 Dec 2023) :`_ 
Rani to share or demonstrate how it works in IA for the dropdowns prefilled with the value from database. Also, to share specific use cases where we might use a few of the features from the feedback list. Will be taken as a feature request and facilated once demo and requirment clarity is obtained.

**Comment by maheswarareddyi** [comment]
A stakeholder meeting was scheduled for today. Upon receiving the sign-off, we will deliver the requirements to the development team

**Comment by maheswarareddyi** [comment]
The requirement document has been submitted for review and is expected to be signed off by 26 April.

**Comment by maheswarareddyi** [comment]
@prabhakaranUI @selvakumarchandran 
Please find the signed-off requirements [here](https://platform3solutionsllc.sharepoint.com/:f:/r/Shared%20Documents/02.%20PRODUCT/Archon%20Data%20Platform/Requirements/ADS_REQ_0018_Values%20List%20in%20Searches?csf=1&web=1&e=NWHpxJ) to plan the development activities

**Comment by kilam005** [comment]
Development is in progress

**Comment by kilam005** [comment]
First demo was shown and feedbacks were conveyed. Yet to open for testing.

**Comment by ElakkiyaBalasubramanian10** [comment]
PR in review state from BE

**Comment by prabhakaranUI** [comment]
Feature released for testing in 146 server
Version: 2024.05.45423_RC4

**Comment by ElakkiyaBalasubramanian10** [comment]
Testing in progress

**Comment by kilam005** [comment]
Testing is in progress. ETA for testing completion is Friday 14th June

**Comment by kilam005** [comment]
Testing was carried out and noticed issues were reported back to dev team.
Dev team fixes are planned to be packaged and handed over for testing today,

**Comment by kilam005** [comment]
Delivery expected was delayed. Testing to be carred out today once released is shared to testing.

**Comment by kilam005** [comment]
Cross application side testing has to be completed. Testing team unable to progress because of an indefiied blocker in creation of cross app searches.

**Comment by maheswarareddyi** [comment]
The development team addressed the blocker, and testing is in progress by @Udhayanila8

**Comment by Udhayanila8** [comment]
Basic search:
![image](https://github.com/user-attachments/assets/c709c4a5-787c-421b-b661-27c889f97684)
![image](https://github.com/user-attachments/assets/dcbc3db2-0e55-485c-be83-4098f8fb2b32)
![image](https://github.com/user-attachments/assets/d8046adb-0e65-486d-a466-37fbbd5ff070)
Adv search
![image](https://github.com/user-attachments/assets/03e24e44-9400-4bb1-9861-ad598b075d86)
![image](https://github.com/user-attachments/assets/6582a8b5-3045-4221-a1e7-ae49e049d24d)
![image](https://github.com/user-attachments/assets/bd9e80ee-92c6-4318-954e-4ece9a7cee0b)
![image](https://github.com/user-attachments/assets/f9e4fa36-7c8c-41cd-8925-994be9f6860a)
![image](https://github.com/user-attachments/assets/0e2e10ba-1535-414f-90ef-938d635d90ea)
![image](https://github.com/user-attachments/assets/a6cda50d-409d-449f-87df-56f3b6038f6f)
![image](https://github.com/user-attachments/assets/d0204e71-1378-4f1e-8b41-21fab5485bfc)

![image](https://github.com/user-attachments/assets/43a71ecf-38f4-4f87-bb2a-0dc8284c4f33)
![image](https://github.com/user-attachments/assets/c6f31117-cef9-45c6-8476-6d85bee0ac11)
![image](https://github.com/user-attachments/assets/db1597d3-9de3-467d-9192-be82814e899f)
![image](https://github.com/user-attachments/assets/2f22497b-cee0-45d5-9a1b-7871142da1bf)

Report Search:
![image](https://github.com/user-attachments/assets/05b87189-4129-4df9-90f6-8dc51bef2b24)

![image](https://github.com/user-attachments/assets/f455a81f-2fd1-46e5-b3be-6e8d975b5ff3)
![image](https://github.com/user-attachments/assets/f4fa5351-52e0-487b-b0e1-83c5d690c8cc)

![image](https://github.com/user-attachments/assets/be688f24-8f6e-494a-816d-dc3b7ca20c1d)

![image](https://github.com/user-attachments/assets/ecdb50a0-0b49-4d7c-8ba8-4be5440af74b)
![image](https://github.com/user-attachments/assets/699ac984-bc3d-4fb7-9f5f-15b6e2bff504)
[Job_name_1721221603499.zip](https://github.com/user-attachments/files/16266001/Job_name_1721221603499.zip)
CROSSAPP SEARCH:
![image](https://github.com/user-attachments/assets/7cfb6db9-0be7-4dad-a53b-49a112ba2258)
![image](https://github.com/user-attachments/assets/7611b3f0-82b4-4fbd-a38c-3bddd380c19e)

**Comment by maheswarareddyi** [comment]
@raniangamuthu This feature is available in ADS v2024.09.45542 on the 218 server in Chennai DC.
Please check and confirm the working and provide closure to this feature.

**Comment by maheswarareddyi** [comment]
@raniangamuthu Could you please provide the verification status of this feature? If no update is received from your end by October 21, 2024, the feature will be marked as closed.

**Comment by raniangamuthu** [comment]
verified

**Comment by maheswarareddyi** [comment]
Closing the feature request as it was verified by @raniangamuthu and no concerns were raised.
