### ISSUE TITLE
ADS-Search - Primary search pagination and state when navigated to nested search - (Dell)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#48]
Primary search pagination and state when navigated to nested search

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/9364e4f4-eca6-458b-aebd-7febfb179f59)

Adding this ticket for tacking purpose.
Originally raised by Kavitha (Dell) via Rani on 12 Dec 2023

**Comment by kilam005** [comment]
coverd as part of [#1349](https://github.com/P3-Core-Dev-Team/lwa-fe-v1/issues/1349)
The fix is ready after testing. refer the link above.
It is planned to be made available in next release.

**Comment by Udhayanila8** [comment]
As Malik mentioned this issue has been tested and closed in the 146 server. The closed issue link : https://github.com/P3-Core-Dev-Team/lwa-fe-v1/issues/1349 
@harsha-kotha, can you please validate this.

**Comment by raniangamuthu** [comment]
Verified and good to close

**Comment by kilam005** [comment]
closing issue with reference to the above comment from @raniangamuthu
