### ISSUE TITLE
 ADS - Logo to be customizable in login as well as header (Dell) (Client Customization)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#49]
Logo to be customizable in login as well as header

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/294529b1-057d-447f-be23-55cb2a6e383e)

Adding this ticket for tacking purpose.
Originally raised by Rani on 18 Dec 2023

**Comment by kilam005** [comment]
@ClementJosh21 / @prabhakaranUI 
please update the status here for tracking the feature development

**Comment by ClementJosh21** [comment]
@kilam005 We have completed development, but still in the testing cycle. This feature will be readily available in version 3.1.8.

**Comment by Udhayanila8** [comment]
Able to customize the logo. Reflected in report as well. Tested in 146 server.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/1e4ce45d-4619-43f1-b580-b7a4eba81af9)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/9411e021-695b-4f20-923c-93df234b71e1)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/65f74e7b-5b8a-4aa7-837c-67773a59851a)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/d083d6b2-bcd1-4a18-9622-a6060f807160)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/1f8d019b-6e79-4395-b222-3efce8ff0cba)

**Comment by kilam005** [comment]
This fixes are ready and verified.
This is planned to be avaialable in version 2024.01.x

**Comment by raniangamuthu** [comment]
We have updated effecTV logo and waiting for the client response.

**Comment by raniangamuthu** [comment]
Looks good so far but we see the SAML logout page is very simple with only **sign in** link.

**Comment by prabhakaranUI** [comment]
SAML logout page screen updated in effectv region
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/997f70bc-066f-442f-aaa5-23284cea32f9)

**Comment by raniangamuthu** [comment]
verified and good to close

**Comment by selvakumarchandran** [comment]
Working fine
