### ISSUE TITLE
Ingestion Job - Status/Progress is misleading

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#5]
Environment - Pulte New Dev ADS 3.1.7

https://archon-datastore.platform3solutions.com/pulte/dev/login

App : Recruiting Management

Ingestion Status does not show actual status.

Table : CANDIDATE_BLOB
Launch time
2023-07-23 14:21:30

Start time
2023-07-23 14:21:59 

Current Time Approx : 
2023-07-23 16:07:00

Message
Ingestion in progress...

Almost 90 minutes has passed, Elapsed time show 00 ms and unable to know the current progress/status of the job.
Elapsed time is very much misleading. There has to be better way to show the progress, current one is very misleading.

**Comment by harsha-kotha** [comment]
Pls tell what details needed, i have added as much information as possible. Selva has taken a look at it. Here is Selva's comment

_**Harsha I understand that the total number of files is 110,620, and each file size ranges from 10 KB to 70 KB only. If the file sizes are smaller and more, moving them to S3 will take time.

 

Also same ASSIGNMENT Table total size 10 GB (apprx) and total file 2300 file completed less then 1 hour.**_


For me the justification given is not acceptable.

**Comment by kilam005** [comment]
After disucssion with Harsha the expectation is

- Elapsed time should show the running time from launch time to current time if the job is in not in final state
- If its final time the elaspsed time must show the value from launch time to end time if the job is in final state

⚠️Keep elapsed time a blank if launch time is unavaiable
ℹ️Launch time will be available when the set is scheduled for ingestion process to start operation

**Comment by Udhayanila8** [comment]
Issue has been fixed. Tested in EMR region.

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/14365557-4f25-47a5-b7cb-9d701249cc01)

**Comment by kilam005** [comment]
@harsha-kotha 
fixes are made as per the discussion we had.

`fix details`
> After disucssion with Harsha the expectation is
> 
> * Elapsed time should show the running time from launch time to current time if the job is in not in final state
> * If its final time the elaspsed time must show the value from launch time to end time if the job is in final state
> 
> ⚠️Keep elapsed time a blank if launch time is unavaiable ℹ️Launch time will be available when the set is scheduled for ingestion process to start operation

**Comment by kilam005** [comment]
@harsha-kotha : please check and provide your comments
