### ISSUE TITLE
ADS-COC - COC Report Clarity from Erik - (Dell)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#51]
In COC Report, For Table with 0 Expected Record Count, it shows data not ingested and the validation messages need to have additional details for the warnings with Spaces

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/df0bae0b-90df-4b7d-8adc-cbd987402452)

Adding this ticket for tacking purpose.
Originally raised by Erik (Dell) via Rani on 11 Jan 2024

**Comment by kilam005** [comment]
Rani explained the scenerio on 24th Jan2024. 
Info presented on report needs to be reworded.

As per Harsha & others in call, the message should indicate the columns name alone that do not match the leading or trailing space conditions. 

🚩Additionally, if the count of columns impacted is provided, it is good to have.

**Comment by ClementJosh21** [comment]
@kilam005 We have made changes as above mentioned. Attaching the sample screenshot for reference.


![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/76196584/918d3694-f2a9-4a25-a4e0-843f4b875388)

**Comment by kilam005** [comment]
Suggestions for statement has been asked for confirmation from Implementation team.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/8ac69645-b6e6-42a2-992f-ea4a11d24b69)

**Comment by kilam005** [comment]
This fixes are ready and verified in the expected version 2024.01.x.
@selvakumarchandran to check priority needs from Rani / Kavitha (Dell) to check if this needs to be patched in 3.1.7_x (effectv build version)

**Comment by Udhayanila8** [comment]
Issue fixed. Tested in 146 server. "Column names" following the - "has data with leading/trailing spaces"
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/5f513af6-35dc-48e4-b35c-3aa83dc3f393)

**COC report**
[COC_REPORT_088f1b2c-8ad0-4df3-b116-25481692b133.pdf](https://github.com/P3-Core-Dev-Team/P3-Q-A/files/14122474/COC_REPORT_088f1b2c-8ad0-4df3-b116-25481692b133.pdf)

**Comment by kilam005** [comment]
The issue was deployed in Effectv region.
Expecting closure from Rani & team

**Comment by raniangamuthu** [comment]
verified and ok to close this issue

**Comment by kilam005** [comment]
Based on above comment from @raniangamuthu, closing this issue
