### ISSUE TITLE
ADS-COC - remove the images of tick and red to reduce the size of the report (Dell)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#52]
COC report , can we remove the images of tick and red to reduce the size of the report

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/6d7d0a57-e088-4878-86dd-bf634d85c768)

Adding this ticket for tacking purpose.
Originally raised by Erik (Dell) via Rani on 11 Jan 2024

**Comment by ClementJosh21** [comment]
@kilam005 We are yet to find an alternative solutions for image to reduce the size.

**Comment by kilam005** [comment]
@ClementJosh21 
i remember you saying you found the way.
What is the status of the fix?

**Comment by kilam005** [comment]
`RCA`
New instance of the image was added to the document every time the tick image was supposed to be included

`Fix details`
PDFXobjects type image was create to refer a single instance of the image in every place it was required to bring down the file size that got bloated.

**Comment by kilam005** [comment]
The fix is internally verified, to be packed in 2024.01.x soon

**Comment by raniangamuthu** [comment]
verified that the size has been reduced and it is good to close

**Comment by kilam005** [comment]
closing based on above comment
