### ISSUE TITLE
ADS-Search - Select all issue in forms (Dell)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#53]
Select all is not working in few cases

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/7b9ad92c-20c5-4144-b5fc-9703489269cd)

Adding this ticket for tacking purpose.
Originally raised by Kavitha (Dell) via Rani on 22 Jan 2024

**Comment by kilam005** [comment]
Rani to provide sample search for reverification.
The issue is shown to occurs in some specific cases so need the sample used for testing.

**Comment by prabhakaranUI** [comment]
@kilam005  The issue occurred only for combo boxes with multi. 
Select all not working properly if the key and value are not same.

**Example:** 
I got this sample data from @selvakumarchandran

_Error field data_
AT,Atlanta Database
SG,Atlanta XG Database
CB,Central Billing
NC,Central Central
CC,Central Central XG Database
NE,Central East
CH,Central Houston
NT,Central Texas
CW,Central Twin Cities
NW,Central West
CN,Central West XG Database
SK,Chatt_Knox XG Database

_Working field data_
ADS,ADS
CHQ,CHQ
CSE,CSE
CSH,CSH
CSN,CSN
CSS,CSS
CSW,CSW
SOA,SOA

**Comment by prabhakaranUI** [comment]
We have a fix and deployed it in effectv region

**Comment by kilam005** [comment]
@selvakumarchandran / @prabhakaranUI ,
Kindly get a confirmation from Rani too.
Please inform the build on which the fix is provided.

@Udhayanila8,
Please include this in your test case and check the working of the same in the upcoming and future releases.

**Comment by kilam005** [comment]
> @kilam005  The issue occurred only for combo boxes with multi. 
> Select all not working properly if the key and value are not same.
> 
> **Example:** 
> I got this sample data from @selvakumarchandran
> 
> _Error field data_
> AT,Atlanta Database
> SG,Atlanta XG Database
> CB,Central Billing
> NC,Central Central
> CC,Central Central XG Database
> NE,Central East
> CH,Central Houston
> NT,Central Texas
> CW,Central Twin Cities
> NW,Central West
> CN,Central West XG Database
> SK,Chatt_Knox XG Database
> 
> _Working field data_
> ADS,ADS
> CHQ,CHQ
> CSE,CSE
> CSH,CSH
> CSN,CSN
> CSS,CSS
> CSW,CSW
> SOA,SOA
> 
> 
> 

Please inform root cause and attach pr details.

**Comment by Udhayanila8** [comment]
Able to select all options for multiple search forms,
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/4aa19082-65d5-4577-b538-95d4e074da85)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/4d93d941-ce8d-4d49-be69-c5fba812430b)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/be2ae613-50dd-49f4-a3bd-114eea790d87)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/6eb43897-1709-4022-a16f-1ac73530dd53)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/3649e45e-b746-4c2d-9f81-e0161f332009)

UI is not responding properly after performing the search. @prabhakaranUI can you please check this,
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/b56b6900-1f3b-434d-ac40-a057f905f1ac)

**Comment by kilam005** [comment]
⚠️ Fix was deployed in Effectv region and demoed to team.

**Comment by kilam005** [comment]
@sumitraRaja
Since the demo was given to the team from effectv region, Expecting closure.

**Comment by kilam005** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/a8712da1-3aa5-40a2-9477-39f1a0384814)

The details were discussed with Andrew and Rani and based on the Complete status mark (Refer screen shot above) bring this issue to closure

**Comment by kilam005** [comment]
`RCA`
Select all issues that occurred if key and display values are not the same. There was a coding issue where key value reference were interchanged. This was evident only in the case of key and values were different.

`Fix details`
The usage of key and value and its associated action with select all was rectified
