### ISSUE TITLE
ADS-Search - Timezone issue with Date Range in Search

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#54]
Timezone issue in filter, Edit in search criteria date 

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/bf64cf48-bb41-4718-a57f-3d90411502b0)

Adding this ticket for tacking purpose.
Originally raised by Rani on 22 Jan 2024

**Comment by kilam005** [comment]
Rani explained the scenerio and also demonstrated the issue re-occurance in filters.
Edit search from Results UI also having issue.

⚠️  To also check Adhoc search.

**Comment by kilam005** [comment]
⚠️ Fix was deployed in Effectv region and demoed to team on 25th Jan 2024.

**Comment by kilam005** [comment]
This has been deployed in Effectv region.
Require Closure sige off from Rani

**Comment by kilam005** [comment]
`Fix details`
the UTC time zone enforcement was removed.

**Comment by Udhayanila8** [comment]
Tested in 3.1.7 version also,
Server: 192.168.56.172

`Screenshots`
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/2205a671-2594-4573-b423-8b4c85344aaf)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/96a489be-1d05-409b-8dd2-4aa11cfbdfc0)

**Comment by kilam005** [comment]
This fix was deployed in effectv environment
awaiting closure from Rani

**Comment by Udhayanila8** [comment]
Tested in 2024.01.45313_P1 version in 146 server.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/bc608f7a-e676-4761-ac0e-30a545df97d4)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/30ffb3f4-de47-4afb-8ef4-26105fe41f6b)

**Comment by raniangamuthu** [comment]
Timezone issue tested and verified in effecTV environment.

**Comment by kilam005** [comment]
With the above comment closing the issue
