### ISSUE TITLE
ADS-Search - memory limit error (Dell)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#55]
8 GB memory limit error

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/38fd5a15-ea36-4f0c-a5c4-7718e8a97183)

Adding this ticket for tacking purpose.
Originally raised by Rani on 22 Jan 2024

**Comment by kilam005** [comment]
`RCA`
Write permission were unavailable

`Fix details`
Configuration for the folder was modified to enable write privileges.

**Comment by raniangamuthu** [comment]
Verified. Please close this issue.

**Comment by kilam005** [comment]
With the above comment closing the issue
