### ISSUE TITLE
ADS-Search - Word break in the application description (Dell)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#56]
Word break in the application description

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/eaeaddf2-f301-4a92-b537-945de778f610)

Adding this ticket for tacking purpose.
Originally raised by Rani on 23 Jan 2024

**Comment by kilam005** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/2fd681b7-9a36-407f-8067-5551d2b2f2ca)

The word breaks are to be prevented.

**Comment by prabhakaranUI** [comment]
@kilam005 we have a fix and deployed it in effectv and rented test region.

**Application listing** 

<img width="1535" alt="image" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/d218fcdb-9339-458e-8a32-890e15067c96">

**Search listing**

<img width="1534" alt="image" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/e114c230-3f31-4ba0-aedf-8547ca9ce71f">

**Comment by Udhayanila8** [comment]
Issue fixed for Application and search page. Tested in 146 server.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/01b8bce0-2863-4a62-8291-2547d3238c4a)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/55b8fd1a-0f5b-42d4-8d1a-36d2f886f6a3)

**Comment by kilam005** [comment]
`Fix details`

Css was styled previously to break at any part.
It is now adjusted to break only at word-breaks.

**Comment by ayyandurai-madhes** [comment]
server 146 
word break  fixed in Application info's description 
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/130345456/b4251756-0bf4-4fa3-80a1-26de2db7ad99)

**Comment by Udhayanila8** [comment]
Issue fixed. Tested in 146 server
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/be1977a0-9267-4fbf-8ac3-fc7a00d03251)

**Comment by kilam005** [comment]
@Rani
The fix for this is deployed in effectv
Please check and provide closure

**Comment by Udhayanila8** [comment]
Tested in 3.1.7 version also
Server: 192.168.56.172
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/7a9ed9c3-ca69-495c-ac49-08da678f1c91)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/59ae9299-9c7c-442f-a6bd-26757a483d57)

**Comment by Udhayanila8** [comment]
Tested in 2024.01.45313_P1 version in 146 server.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/7bcccd9d-ec6a-48e1-a94e-55db6cea85dc)

**Comment by raniangamuthu** [comment]
word break is fixed but can we have the app desc to be justified.

**Comment by kilam005** [comment]
@raniangamuthu 

Justified will not look good with work break forced to happen for each word.
Words that cannot be accomoated will be forced to move to next line, which can make fewer words appearing in previous line be distributed with bigger gaps.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/58c93192-2aab-4837-a2ae-2c39ce7dc7ea)

Recommend to keep it like how it is now.
please let me know if its ok.

**Comment by raniangamuthu** [comment]
Ok agreed, we are good to close this issue.
