### ISSUE TITLE
ADS-Search - Search Results enhencements (Dell)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#57]
Mutiple issue tracked because of similarity

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/feb2d1b2-b1c8-4d6d-8e19-27cbcfcc2236)

Adding this ticket for tacking purpose.
Originally raised by Rani or by Kavitha via Rani on 24 Jan 2024

**Comment by prakash-kandasamy** [comment]
Issue fixed

<img width="1680" alt="302600867-bf2edff5-21e2-4b93-9a03-16a38cbcae56" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/79510599/edfa08b0-3144-46f7-a131-bcc4ebedd543">
<img width="1680" alt="302601006-03974d09-a62b-4c79-9e5a-f082bff14e2b" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/79510599/039b0ee9-59d6-4cd9-ade7-7f5f457b0a7d">

**Comment by prakash-kandasamy** [comment]
Issue fixed
<img width="1676" alt="302605069-4933fedd-b5d9-42ce-9227-f9fa2fe2cd17" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/79510599/c9525798-861a-4794-b654-8e22158d1fa7">
<img width="1674" alt="302605199-28f9c4bf-51c3-4c4f-a206-ba478be89632" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/79510599/5587a6b0-aa65-408c-9d4d-173e520152ba">

**Comment by kilam005** [comment]
`Fix details`
CSS and UI cosmetic fixes are made to support

1) Column width adjustment
2) See more and see less option for long text
3) fix expanded row layout on horizontal scroll
4) configure column option was provided to support user's  selection to view preffered result column's

**Comment by Udhayanila8** [comment]
Server: 192.168.56.172
Tested in 3.1.7 version.

`Screenshots`
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/89d4298b-5778-435d-b7e1-cbd86fd66df9)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/e8c47e4c-2120-464f-8e6d-2d60e3f1b40f)

**Comment by raniangamuthu** [comment]
verified and good to close

**Comment by kilam005** [comment]
based on comment from @raniangamuthu, closing this issue
