### ISSUE TITLE
ADS- Searches - Manually edited Date causing issues in form (Dell)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#58]
When search form has 2 fields one with dropdown(mandatory) and date range(optional) and when manually edited the value for date and  search button remains disabled even selected the dropdown option.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/cbcd8f9a-2093-4962-a472-0eeef5517a98)

Adding this ticket for tacking purpose.
Originally raised by Kavitha (Dell) via Rani on 24 Jan 2024

**Comment by kilam005** [comment]
@prabhakaranUI I hope the fix is avaialble. Please provide fix details and add screen shots for history tracking

**Comment by prabhakaranUI** [comment]
Search result date range field - from date was removed, when the user edits manually.
have a fix and deployed it in effectv region and 3.1.8.

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/59fe98db-7966-4390-8693-b2924ef18786)

**Comment by kilam005** [comment]
`RCA`
The date picker field was designed for date entry only through the datepicker option (though manual entry was possible)
Manually entry (typing) of date input but was not properly parsed to be retained as a date picker object that caused some irregularities.

`Fix details`
Code updates were made to adapt to both date picker and manual date entry.

**Comment by kilam005** [comment]
[`Exact code fix reference`](https://github.com/P3-Core-Dev-Team/lwa-fe-v1/pull/1405/commits/6e4279e7f151dc940a592125ae059eac337b0ca9)

**Comment by kilam005** [comment]
⚠️  This fix is deployed in Effectv environment and given for review top Rani & team

**Comment by kilam005** [comment]
The issue is marked as Complete by Rani on tracker.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/93e13672-348c-4a8e-8f24-dc7cedbba8de)

**Comment by Udhayanila8** [comment]
After entering the date manually the search icon is enabled and able to perform the search.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/731a7c83-2c11-4eaf-ad82-03c2c59cec4b)

**Comment by kilam005** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/cd3fb501-5851-48f5-bbcd-31862177b95a)

WRT the previous comments and screen shot above, marking the issue as closed
