### ISSUE TITLE
Export Issue - Data Exported is exponential from csv viewed in Excel

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#6]
Environment - Pulte New Dev ADS 3.1.7

https://archon-datastore.platform3solutions.com/pulte/dev/login

App : Recruiting Management
Search : Test_Assign

Selected record export in csv format shows exponential from csv viewed in Excel, should maintain as number/id from source.

Value in Export:
COL1
--
5.01047E+12

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/42184278/1e910446-4f9c-47a1-8755-fc4390f84437)

**Comment by kilam005** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/feefee57-c3e1-4894-8658-e7ffd7543d75)

CSV file is properly generated.
While opening in excel, the data is displayed in exponential. but data is exported as number only.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/da987e2f-f7f2-4962-8363-5cef90d5c644)

**Comment by harsha-kotha** [comment]
what is default fix? i saw the value in txt file. By default many will use Excel, apparently it looks as if it is data issue in first sight when looked.

**Comment by harsha-kotha** [comment]
i have nothing to re-test, i want a way for excel to work

**Comment by kilam005** [comment]
Excel auto converts when loading data. 

Read more:
[https://csvloader.com/csv-guide/how-to-stop-excel-from-formatting-numbers-in-scientific-notation#:~:text=If%20you%20have%20numbers%20longer,are%20displayed%20as%20scientific%20notations.](url)
[https://csvloader.com/csv-guide/how-to-open-csv-in-excel](url)

**Comment by kilam005** [comment]
There is no fix, except load in EXCEL using Data import wizard.
This is outside scope of the tool.
As indicated, the data is loading in CSV format properly.

If there is any other workaround, do let us know.

**Comment by kilam005** [comment]
@harsha-kotha 
You need to see the comments above and give a conclusion to this.

**Comment by kilam005** [comment]
`details`
There is no fix, except load in EXCEL using Data import wizard.
This is outside scope of the tool.
As indicated, the data is loading in CSV format properly.


@harsha-kotha 
Please check and give a conclusion

**Comment by harsha-kotha** [comment]
Closing for now, if there is a client requirement this needs to be revisited.
