### ISSUE TITLE
Dell-Sorting in search results 

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#60]
Execute search > View Search results > Advanced filter > click add filter > now sort the results > throws error

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/b68fbfb7-1a0d-4a2e-9248-0132dade4d16)

**Comment by Udhayanila8** [comment]
I have faced a similar issue in the 146(test region) server also,
**Server details**: 192.168.56.146:4081
**Application name**: 3.1.8_BLOB_HDFS
**Search Name**: USA_YEAR_END
**Steps:**

1. Create a search, that has 44 columns, 
2. All columns should be enabled with sort and filter options.
3. Perform the search.
4. Perform basic filter.
5. Once results pop up, click the sort option.

**Screenshots**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/cc0a9d39-a9da-443a-8c95-c271b046c6de)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/5831f4b8-3dc5-410d-b6e1-10106a08b2ed)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/6ce6aa40-2066-4ab6-8c46-dfc94efdad06)

**Comment by prabhakaranUI** [comment]
Fix was deployed in Effectv region and demoed to the team on 1st Feb 2024.
https://github.com/P3-Core-Dev-Team/lwa-fe-v1/pull/1429

<img width="1534" alt="image" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/d2d33b2e-1b2d-473e-a78d-b43839b8ecc2">

**Comment by kilam005** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/c407802b-dc02-47d4-a09c-526423da62b3)

The details were discussed with Andrew and Rani and based on the Complete status mark (Refer screen shot above) bring this issue to closure

**Comment by kilam005** [comment]
`RCA`:
while user click the pagination, if user select the advance filter and leave the input field as empty. the payload send with empty rule. So we got exception in API

`Fix details`
Correction was applied to work as per the applied filted condition only
