### ISSUE TITLE
ADS-Search - Search Criteria display order in breadcrumb (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#61]
Search criteria not displayed in the order as in search form in the breadcrumb in the search results page.

**Comment by kilam005** [comment]
@raniangamuthu 
please attach screen shots for clarity and to use in comparision after code fixes.

**Comment by kilam005** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/0ce543dc-ad1a-473f-b034-4e9566753588)

WRT above screen shot, we are awaiting confirmation to proceed

**Comment by raniangamuthu** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/ec2c6360-c769-4664-bab0-f2509e21944b)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/137440c0-7e4a-4a58-a1da-208cbe025f1c)

**Comment by raniangamuthu** [comment]
The order of the criteria in the breadcrumb should be in the order of the fields as defined in the search form, for ex: company ID and then Agency

**Comment by kilam005** [comment]
https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/e9c0af98-4613-4ebf-806f-2c6508668b78

👆 Sample view of working for feedback

**Comment by kilam005** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/792290a1-0e3f-4ee2-83de-8f7868414d05)

@prabhakaranUI Take the above screen shot as confirmation and bring the development made live to release.

**Comment by prakash-kandasamy** [comment]
Issue fixed

<img width="1680" alt="302608834-58e5abbc-e8ba-4549-8c67-2473d191b0ce" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/79510599/f2e8c75a-357b-49df-ae59-021ec80ad657">

**Comment by kilam005** [comment]
`Fix details`

The payload info was not sorted before. Sorting in the order of form fields was included to provide the fix.
Addition to avoid any screen cluttering, if there are more than 2 fields then the search criteria will be position to on demand view that open a pop-over as shown in the screen shot(s) and videoes above.
