### ISSUE TITLE
ADS-Search - filter condition options - Case insensitivity & Does not Contain option (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#62]
In Search results page, advanced filter option is case sensitive which was raised as a question to have the case insensitive option.
Also, there is an option in filter condition like not in which is exact match, so we might need an option like does not contain to have a wildcard filter of not in.

**Comment by raniangamuthu** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/197f5ec4-fc4e-4855-aa81-5094c8bca77a)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/02644a8d-19f6-4b73-93f7-b6ebab497898)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/8df12644-3b53-452b-a034-7c24f12b8936)

**Comment by kilam005** [comment]
@raniangamuthu 
the possibilities of this is being explored.
this would take at least 3 days to confirm support possibility.

Please expect this sometime on or before the week of Feb 26th

**Comment by kilam005** [comment]
@raniangamuthu 
This is partially fixed.
Case insensitivity issue is resolved.
Does not contain option is being validated. Fix will be available soon.

**Comment by Udhayanila8** [comment]
Case insensitive fixed in 3.1.7 version
Server: 192.168.56.172

`Screenshots`
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/762b50e5-9660-42e0-90f2-797d7c991afd)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/8cd9a019-62e1-43c7-aa26-219fe85f9ac1)

**Comment by dinesh-p3** [comment]
`RCA`
In Open Search, the default configuration does not include case-insensitive properties for string data types

`Fix details`
The required properties, including a normalizer with case insensitivity, are included

**Comment by kilam005** [comment]
@raniangamuthu These issue is already avaialble in the build shared with effectv.
Please check, verify and provide closure to this.

**Comment by raniangamuthu** [comment]
Tested and working fine
