### ISSUE TITLE
ADS-Search - Pagination Issue (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#63]
In the search results page when we click random on next next page we get the below screen, and it is also inconsistent. Refer to the below screenshot:
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/f3b531f2-b844-4044-aca2-7dde895b6564)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/36d10eff-7ce9-4b45-b995-ebdd8542f4d7)

**Comment by kilam005** [comment]
@raniangamuthu,
Can you provide the step to recreate this?
We need more clarity to work on this as it is currently not reproducable.

**Comment by kilam005** [comment]
@raniangamuthu 
Any update possible?
If is not repoducible, we need to get this closed

**Comment by kilam005** [comment]
@raniangamuthu 
If no action is taken from your end on or before April 20, the issue will be auto closed as it is not reproducable.

**Comment by raniangamuthu** [comment]
not reproducible and hence parked as of now
