### ISSUE TITLE
ADS-Search - Sorting and Pagination (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#64]
Search results page > sort any field > Move to next page we get the below error:
![Screenshot 2024-01-31 104527](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/4d72027f-fede-4fca-88f3-224a60773dcd)

**Comment by kilam005** [comment]
@ashoksri0 / @prabhakaranUI 
any update on this.
Are we checking on this issue.
Is this any side effect?
Will post conversion of sort and order fix this too?

**Comment by kilam005** [comment]
the fixes are made. This will be avaialble in 2024.01.x release.

**Comment by Udhayanila8** [comment]
Able to sort and click the next page. Tested in 2024.02.45353 version.

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/3b1ae117-8574-4fec-9a0f-3b0f4675b2fb)

**Comment by kilam005** [comment]
`RCA`
there was a mistake with internal call route when sort or filter is applied leading to this issue occurance.

`Fix details`
the junk character added due to typo was removed.

**Comment by raniangamuthu** [comment]
Verified
