### ISSUE TITLE
Dell - decimal value in search results

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#65]
We did the right format of amount columns with 2 decimal places using cast and mapped to decimal column type but still the results are not formatted correctly in the search results page.
Verified using the same columns in the query editor and we get the format as expected using cast as decimal.

**Comment by raniangamuthu** [comment]
Tested

**Comment by kilam005** [comment]
'RCA'
the insignificant zeros on numeric, double and float types were automatically discarded during save and retrieve.

`Fix details`
Open search mapping configuration has been enhanced to provide support for decimal formats correctly and retain all insignificinats digits as ingested.
