### ISSUE TITLE
Dell-Export results after background search

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#67]
Search run in background > Export selected records - records are randomly exported and does not match the selected records.

**Comment by kilam005** [comment]
@raniangamuthu 
please provide more details, screen shots and sample searches to recreate and debug

**Comment by raniangamuthu** [comment]
Execute background search > selected records export
<img width="960" alt="BGSearchView1" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/b5c0f103-bbf2-48ac-8323-25859fff5712">
<img width="960" alt="BGSearchExport1" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/1e41bcb0-3067-4ed2-b32a-a30a151d99a8">

**Comment by kilam005** [comment]
Requester @raniangamuthu for the search query to debug more

**Comment by Udhayanila8** [comment]
Tested in both 3.1.7 and 2024.01.45313_P1 version.
Server 3.1.7 - 192.168.56.172
server 3.1.8 - 192.168.56.146
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/a9bcf9d4-41b8-4e62-b65f-7d6907660ff0)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/6425f2d5-e65b-41f2-a0a3-b6ba18370a04)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/0f0a9d8a-c7f2-45d1-a5b7-16f0b5171df4)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/c6622900-02f1-462b-8f6a-ce7c6952286c)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/e441b500-b535-4f47-93a8-c45062f333f8)
