### ISSUE TITLE
Dell - Search form fields in multiple containers

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#68]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/834ffe7a-0969-4d01-acf6-3cf041cfc49e)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/8fe9dd6e-605f-45ac-bdaa-b37477e8a1fa)

**Comment by raniangamuthu** [comment]
Search throws Something went wrong popup message

**Comment by prakash-kandasamy** [comment]
Issue fixed
<img width="1680" alt="302601175-63755e8d-e32d-4317-acab-e218173d12ee" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/79510599/d1f087d3-faa6-419a-97d8-393de9d97d8a">

**Comment by kilam005** [comment]
`RCA`
A partially developed code fix for ordering search items in ui was packed in release build.

`Fix details`
The issue is fixed by correcting the code
