### ISSUE TITLE
Dell- Search Result - String sort

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#71]
String sort columns not working as case insensitive.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/1e6b3fc4-c697-4344-bed3-8f46aad90470)

**Comment by kilam005** [comment]
@ashoksri0 / @selvakumarchandran  
this should be dicussed.

@kilam005 to get back to @raniangamuthu and team about the possibliity.

**Comment by kilam005** [comment]
@raniangamuthu 
This is being checked along with #62 
the possibilities of this is being explored.
this would take at least 3 days to confirm support possibility.

Please expect this sometime on or before the week of Feb 26th

**Comment by kilam005** [comment]
@raniangamuthu 
Priliminary fix is ready. 
Testing is being performed

**Comment by Udhayanila8** [comment]
Tested in 3.1.7 version.
Server: 192.168.56.172

`Screenshots`
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/7cbbcaf4-d89d-411b-992b-c9fc9e3690b8)

**Comment by Udhayanila8** [comment]
Tested in 2024.01.45313_P1 version in 146 server.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/bffc35d9-5065-44a1-a0ce-367dc38b7bd3)

**Comment by kilam005** [comment]
@ashoksri0 / @VikramSelvadurai 
please add RCA and Fix details

**Comment by dinesh-p3** [comment]
RCA: The case insensitive property is not enabled by default to all the columns with String Data type
Fix: The required property is added to the String fields while saving the data in open search to enable the case insensitivity to columns with String Data type
