### ISSUE TITLE
ADS-Search - Column configured not fully effective in search area & Binding names used in customize column. (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#72]
After executing search and when customized using "Configure Columns" this does not reflect under "Advanced Filter" columns

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/650879eb-782d-48de-b26b-2791b8ba3232)

**Comment by kilam005** [comment]
Binding names are being displayed in the column selection option. This needs to be corrected and the permission seem to be ineffective.

**Comment by kilam005** [comment]
@prabhakaranUI 
need to check for column set area (on hidden fields)

**Comment by kilam005** [comment]
@prabhakaranUI / @Thilak-Saravanan 
need to create custom function to make role based determination on hidden columns to display the customize column options.
This is to be done in addition to the binding name to label change

**Comment by kilam005** [comment]
@raniangamuthu 
this issue as of today is partially fixed.
ie) All ui related issue are fixed, one BE fix is in progress. the BE fix will get this issue to complete closure.

UI fixes support the following
- Binding name to Label update
- hiding of columns in column customization
- Additionally added option for column sort in customize columns area.

BE fix in progress
- Support for hiding hidden column in advance filter area

**Comment by kilam005** [comment]
`Fix details`
the code change to refer to the label (instead of binding name) was corrected.
BE response bean did not differentiate between hidden and non-hidden column. Fix is made to correct it out.

**Comment by kilam005** [comment]
@raniangamuthu 

The required issue is fixed.
see reference video 

[Column view customization, width adjustment, Column position shift with state manegement.webm](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/87484d1c-7e5e-48c2-987c-8c906a867d17)

**Comment by Udhayanila8** [comment]
Tested in 3.1.7 version.
Server: 192.168.56.146

**Screenshots**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/1015f9ff-523e-458b-9c56-b34adb4e31e6)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/3ff2a3ae-de2f-4bc0-a23d-84e608947449)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/9a028440-cd0b-4d59-a499-cd9b46a7cedf)

**Comment by Udhayanila8** [comment]
Tested in 2024.01.45313_P1 version, in 146 server
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/efe8776f-34e4-4603-b217-49f0b8637694)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/d61b25d8-e7e0-46c0-882d-23e0dd2194ab)

**Comment by kilam005** [comment]
The fix is complete and is release in 2024.01.45313_P1.
To be deployed in effectv environment

**Comment by raniangamuthu** [comment]
Verified and good to close
