### ISSUE TITLE
Dell - Date filter option "between and" does not allow future date

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#74]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/79e036b9-fb8c-471c-ad61-2ed0e2865e9f)

**Comment by kilam005** [comment]
Max data should not be set to current date.
This is in search area and user should be able to enter any data in the past and future.

**Comment by kilam005** [comment]
`RCA`
Min and max date was set on date fields

`Fix details`
The added restrictions were revoked.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/e2536cac-c695-4c59-b827-662574ec52e2)

Fix will be avaialble in next patch build and in future releases

**Comment by raniangamuthu** [comment]
Additionally, if we manually edit the date a weird date is added, and it becomes hard to enter the date.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/1baf72a7-79d4-4e08-8561-8a26963036a1)

**Comment by kilam005** [comment]
tracking the quoted issue as #80 
as they are unrelated

> Additionally, if we manually edit the date a weird date is added, and it becomes hard to enter the date.
> 
> ![image](https://private-user-images.githubusercontent.com/69497085/304139895-1baf72a7-79d4-4e08-8561-8a26963036a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzUxNTIsIm5iZiI6MTcwNzgzNDg1MiwicGF0aCI6Ii82OTQ5NzA4NS8zMDQxMzk4OTUtMWJhZjcyYTctNzlkNC00ZTA4LTg1NjEtOGEyNjk2MzAzNmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE0MzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YWE3NGEwNTRmYzBkM2I0ZmVkM2IyMjc0Y2I1ZGEyMmRkYmFiMmRiODRhMTdiNmM2ODg0ZTUzNDc0OWNmYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LmPLW4WPb2GEqiIlV1EvdQHDLSfctjqOn0Xl91pPIL4)

**Comment by Udhayanila8** [comment]
**Server: 192.168.56.172**
Tested in 3.1.7 version 

**Screenshots**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/9bb462a3-71eb-492f-a60f-b72380f9769a)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f48b4e92-471c-48ac-befb-c97d4d7dd411)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f2354333-407e-4b8b-851c-1e09a3385b6f)

**Comment by Udhayanila8** [comment]
Tested in 2024.01.45313_P1 version in 146 server.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f8be4d59-70f3-4df3-b6bd-949fb38829b2)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/8fcf64a2-83d6-4ce5-95c2-b695f0d52db2)
