### ISSUE TITLE
Dell-User Preference updated with MM-dd-yyyy date format. Search critiera breadcrumb doesnt reflect that format and datefilter not working

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#75]
Login>update the date preference to be MM-dd-yyyy
Search Form >  Enter the date criteria using the calendar and the date format displayed as set in user preference.>Execute search>Search result page the breadcrumb still shows in yyyy-MM-dd format.
Also, the date filter is not working as expected. Attached screenshots below:
![Screenshot 2024-02-11 202211](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/6268dbf2-c361-4317-ac84-f4cce36767a4)
![Screenshot 2024-02-11 202146](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/1d2092c7-acd1-4ca9-915c-71a453749cab)
![Screenshot 2024-02-11 202132](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/2df84e24-5a4b-4e1f-8090-a69a5d871022)

**Comment by kilam005** [comment]
This issue has been infomred to team.
Work is in progress.

**Comment by kilam005** [comment]
@raniangamuthu 
the changes are made and will be avaialble by tomorrow for deployment.

For Date format in breadcrumb
`Fix details`
the user preference was pushed to the breadcrumb area
See references below

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/3d0e35b0-d41e-4678-84b1-f9f1672f0287)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/f8bf046d-72b1-42ac-b462-575b74871477)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/3cd362a9-b2da-4ab5-8a4c-2a8dea2af6af)

---

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/31ad543f-3332-497e-8f4d-e59d48c40644)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/b6d3a304-5559-49e2-8fd5-9083e588d7e2)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/49dd31b2-5832-44de-950a-c2d7a14e1d70)


----

w.r.t Date filter not working
`RCA`
there was a code typo.

`Fix details`
code typo was rectified.
See references below
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/7b724a4f-c3a7-463e-969b-8a563c795996)

**Comment by raniangamuthu** [comment]
Additionally, the sorting is not working when the preference is changed.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/219ee313-7327-41fb-9fa8-85f6e8157102)

**Comment by kilam005** [comment]
@raniangamuthu 
Please check of the result column's configuration is marked as date.
This seems to be `query formatted date column` and result column is configured as `string`

**Comment by raniangamuthu** [comment]
you are right Malik but i am not able to cast the string say 01/01/2024 to date type, looks like Trino limitation. Need some guidance here

**Comment by kilam005** [comment]
@raniangamuthu 

Can you give some clarity on the date column field and some sample data to understand the format.

- is the data type of the column a data or string or datetime
- if it's in string what is the format in which the data exist. (Ymd or mdy or something else)

Once I get these info, I can provide you query guidance

**Comment by Udhayanila8** [comment]
Tested in 3.1.7 version also.
Server : 192.168.56.172

`Screenshots`

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/37cb3d2a-9d6e-4ca7-82e9-5d21d716afab)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/1a91c2fa-fce5-4542-9dcb-528a9c5b32e4)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/dd5cb638-c005-4155-9f8d-799b093067b1)

**Comment by Udhayanila8** [comment]
Tested in 2024.01.45313_P1 version in 146 server.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/d082d968-56ed-4b75-b75f-9004473b7ff4)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/e538ae58-1dfe-4882-9f65-1f0fa2101346)

**Comment by kilam005** [comment]
@raniangamuthu 
the fix is available in Effectv environment.
Please check and give closure
