### ISSUE TITLE
ADS-Search - Pagination, no option to move to first and last page (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#76]
Issue raised by dell team- kavita
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/c191ba52-de5a-4392-82ab-d954e05e881f)

**Comment by prabhakaranUI** [comment]
Pagination controls will be limited to the previous and next page when results exceed 10000 rows.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/27a193bb-53f2-4a21-82ef-cf3f615808b4)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/cd50939c-b6b2-4f87-bb2e-2d7accac6955)

**Comment by prabhakaranUI** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/af28cc82-245e-49d1-9703-04b2cb753409)

**Comment by kilam005** [comment]
@prabhakaranUI 
As dicussed in call, the first and last page moving button appearance should be controlled by the no of results for the query and not based on the limit configuration.
 
 

If the number of results received for a given query is 
- **less than or equals to 10000** then first and last page buttons **should be available**
- **exceeds 10000** then first and last page buttons **should not be available**

**Comment by Udhayanila8** [comment]
Paginations working on based on the results in the search.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/4ab3a0b5-ba4d-4fb6-aef3-6d71a903699c)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/ba456c9f-6072-49ad-b910-0466d4a51bc6)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/4b8bbb80-63dc-4061-b934-8ad44eadcdaf)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/cacfa8a7-1807-48fe-b0e2-269156ddb2f9)

**Comment by kilam005** [comment]
@raniangamuthu ,

Pagination works as designed.
if ther result exceed 10000, first and last options will not be available.
This is explained as a disclaimer too. please check the note next to warning icon in the above screen shots.

Please check and provide comments.

**Comment by kilam005** [comment]
`Details`
There is no issue. It is wroking as per design.

**Comment by raniangamuthu** [comment]
Tested and Agreed
