### ISSUE TITLE
ADS-Search - Filter String with wildcards (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#79]
Execute Search > filter option for string Starts with > throws error
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/c6d55673-1d5e-47e9-9efd-e2eee0b16d52)

**Comment by Udhayanila8** [comment]
Tested in 2024.01.45313_P1 in 146 server
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/206027eb-be11-411a-a85d-22da08ccf439)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/08a85d7c-d525-4c9b-bccd-195da19db0df)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/ac2991d8-1641-40de-86b6-5fa1b7e06dd1)

**Comment by kilam005** [comment]
Need RCA and Fix details @prabhakaranUI & Dinesh

**Comment by dinesh-p3** [comment]
RCA: Issue occurred while decoding the encoded special character value send in the URL of the Search Filter API
Fix: The respective Search Filter API method is changed from GET to POST to receive the request payload in the body

**Comment by Udhayanila8** [comment]
Able to search with wildcards.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/72bc174d-5f19-4511-ab28-58c007eec028)

**Comment by kilam005** [comment]
@raniangamuthu 

please check this in effectv region and confirm the working.

**Comment by raniangamuthu** [comment]
verified and working as expected
