### ISSUE TITLE
Export Issue - Select All and Export is not working

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#8]
Environment - Pulte New Dev ADS 3.1.7

https://archon-datastore.platform3solutions.com/pulte/dev/login

App : Recruiting Management
Search : Test_Assign

Export with 1 Column and 10000 rows of data is in running for about 2.5 Hours. Expectation is to have it done immediately or within few mins.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/42184278/5daed8a1-ecc7-41a1-b172-4109c54a7bfc)

**Comment by kilam005** [comment]
Bug noted. Will be looking into it.
Myself or team will update on this once we debug

**Comment by kilam005** [comment]
Search service has some issues.
RCA to be determined.

Current info avaialble : Permissions / Configuration missed out in deployment.

**Comment by harsha-kotha** [comment]
Please share what permission was updated or what config was updated.

**Comment by harsha-kotha** [comment]
As of this morning, issue still persist. Now export fails immediately. Refer below screenshot.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/42184278/5740c0fa-bbd8-4f75-bc9d-265d466d28cd)

**Comment by Udhayanila8** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/34e86843-9d79-4fa0-8f43-148df6c783bf)


![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/e5d903d3-a871-4d5e-be49-e241e01603e4)



Issue has been fixed and tested in https://ads-dev.platform3solutions.com:4082 , by santhanakumari.

**Comment by harsha-kotha** [comment]
I do not see what was fixed, can you please share what was the root cause, What we have done to make sure issue does not re-occur?

**Comment by kilam005** [comment]
@ClementJosh21 / @ashoksri0 please provide track history for the cause and fixes provided.
I belive the cause is to do with the memeory configurations. Please elobrate.

@Udhayanila8 like previously stated in another issue, this issue needs to be checked in pulte-dev and closing must be perfromed by @harsha-kotha and his team. You should validate and confirm the wokring state and add your comments but dont mark the issue as closed.

**Comment by ClementJosh21** [comment]
@harsha-kotha  

**_RCA:_** There are two cause for this issue, one the was the max heap is set very low in opensearch and the other one is that content length (max length of the data that opensearch can handle) is not handled properly when pushing data tp opensearch.

**_Fix:_** We have increased the heap size of opensearch and also added a filter criteria in ADS for max content length (can be configurable) on which the data will be pushed to opensearch.

**Comment by kilam005** [comment]
@harsha-kotha 
please validate and provide your response for closure

**Comment by harsha-kotha** [comment]
Closing as RCA is added.
