### ISSUE TITLE
ADS-Search - Date manual entry in Advanced Filter - Dell

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#80]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/0d45a275-2fae-49d0-b6d6-9e61baf27e04)

Issue was originally created by Rani

**Comment by ayyandurai-madhes** [comment]
RCA:  The date field couldn't accept  manual input
fix:  while pressing the backspace or delete button to control the autofill date through allowing the manual input
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/130345456/8b59c94a-ea40-4aae-be83-64f2fb87320a)

**Comment by Udhayanila8** [comment]
Able to edit the date manually, version - 2024.01.45313_P1
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/fe14773b-0b0d-447b-bd5b-107faa520820)

**Comment by raniangamuthu** [comment]
Verified and working as expected. Good to close.

**Comment by kilam005** [comment]
Based on above comments, closing the issue
