### ISSUE TITLE
ADS-Search - Search performance issue for huge volume of data (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#81]
For 496 results it went to background that took 15sec. More info can be provided over a call.
We have joined 3 tables that are huge and to edit & save itself it is time consuming. 
This is the same screen that caused the memory limit 2GB error.

**Comment by raniangamuthu** [comment]
High Priority - Client UAT starting on 20 FEB

**Comment by kilam005** [comment]
does it have a order by ?

**Comment by kilam005** [comment]
@raniangamuthu 
We will not be able to proceed on this issue till we get query.
putting issue on hold till furthur details are obtained

**Comment by raniangamuthu** [comment]
Looks the team has resolved by increasing the limit may be and we are seeing this error now.
