### ISSUE TITLE
ADS-Search - Search Screen Update - Error (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#82]
Trying to update the search form
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/22a5429d-f801-4ac4-a702-87385c78f737)

**Comment by kilam005** [comment]
@selvakumarchandran / @ClementJosh21 
Has anyone checked this?

**Comment by ShaliniSettu** [comment]
@raniangamuthu 
Can you provide the step to recreate this?
We need more clarity to work on this as it is currently not reproducable.

**Comment by raniangamuthu** [comment]
this was verified and working
