### ISSUE TITLE
Dell-Search results that takes to background - View -throws error - high

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#83]
Steps to create: Search that takes to background > View from background >throws error that is not so consistent
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/846e4699-ad4d-4438-8cf3-44bd1fe3be50)

**Comment by kilam005** [comment]
@selvakumarchandran has indicated to @raniangamuthu on Chat

```
This issue was fixed and deployed. 
Please check and close
```

**Comment by kilam005** [comment]
@raniangamuthu ,

@selvakumarchandran has alrady shown the fix for this to you.
Please confirm and give a closure

**Comment by raniangamuthu** [comment]
tested the fix and good to close

**Comment by selvakumarchandran** [comment]
Please check and close

**Comment by raniangamuthu** [comment]
Verified
