### ISSUE TITLE
ADS-Search - Search results - export - count mismatch (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#84]
This is so random, but it is across all the search screens. Search > results in 34336 results but exported file shows 34337 results excluding column headers.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/7464ea1e-4dbe-4fed-bc87-8020cd67b2d5)

**Comment by raniangamuthu** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/4da32a55-6776-4b05-b2b2-5061da8ada08)
 one of the record's last column came to the next row during export. Need to see how to fix this?

**Comment by kilam005** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/c3ae630c-755e-4e70-aa0d-9d63b6bfd7cd)

Carriage return was detected and needs to be escaped in CSV, TXT, TSV, pasically every Text type export.

The details of this has been discussed internally and the correction will be available soon.

**Comment by kilam005** [comment]
@ShaliniSettu ,
Please update current status on this.

**Comment by kilam005** [comment]
@raniangamuthu 
team has deployed the build with this fix in effectv region. kindly test and provide closure.

**Comment by kilam005** [comment]
@raniangamuthu 
can you check and provide comments (or) closure

**Comment by raniangamuthu** [comment]
Verified
