### ISSUE TITLE
ADS-Search - Search form>string value containing single quote - error (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#85]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/cae9a4e9-7b25-4ece-8f18-0638e10e7509)

**Comment by kilam005** [comment]
@raniangamuthu  
please pass the query synopsis for deeper understanding

@Surinarayanan / @ClementJosh21 
Also i believe this is connect with escape character treatment for necessary chars

**Comment by ShaliniSettu** [comment]
RCA
search input which containing single quote is splitting a input values in payload

Fix provided
replaced the single quotes(') which is coming in payload with double the single quotes('')
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/33217746/196d5950-381a-4393-9897-db89f6391373)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/33217746/707ae01c-343e-41b9-bf5f-29f58ccb1d64)

**Comment by kilam005** [comment]
@ShaliniSettu / @ClementJosh21 
please check this for multiple select, radio where there is an `in` query usage
in basic and advanced.

There is a chance that the code would not work correctly

**Comment by raniangamuthu** [comment]
Looks like the fix is not available in current effecTV environment. Will wait for the fix to verify before closure

**Comment by kilam005** [comment]
@raniangamuthu  this is being worked upon, i have not added Awaitiing release.
but we need sample query used for getting some idea to conclude if the popup came up becasue of something else other than quote identifier

**Comment by Udhayanila8** [comment]
Tested single quote value in 137 server.
Server: 192.168.56.137:4081
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/2e3ff503-663f-4fc1-9071-beb1215c89e8)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/b48842f8-51e5-4284-969c-7201a9a11863)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/0063a3d1-9ad0-4719-b652-95eed8e27060)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/12aa4b4a-a242-4c81-8798-8a4ed7fe7386)

**Comment by kilam005** [comment]
@raniangamuthu 
Please check this in effectv region and provide closure

**Comment by kilam005** [comment]
`RCA`
The `'` Single quote is a quote identifier within the SQL engine used by ADS. So it was unable to differentiate key words and input resulting the SQL syntax error detection

`Fix Details`
Code fix was made to escape and handle quote identified.

**Comment by raniangamuthu** [comment]
Working as expected.
