### ISSUE TITLE
ADS-Search - Search without giving the input for the mandatory field (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#86]
Captured in the audit log 

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/f3c9877e-486b-4ce7-83f2-409a36cd7091)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/7f2eb803-c3f0-4e58-8143-2b54ecc3ab86)

**Comment by kilam005** [comment]
@ClementJosh21 / @prabhakaranUI 
how did the search button get enabled to execute?

**Comment by kilam005** [comment]
@raniangamuthu ,
need steps to redproduce this.
This is not occuring when we try.
Kindly provide details to proceed on this issue.

placing on Hold till receiving details from you

**Comment by raniangamuthu** [comment]
Not able to reproduce but this scenario was captured in the audit log

**Comment by kilam005** [comment]
@raniangamuthu 
we tried mutiple ties, but this is not reproducible.
Request you to close the issue for now.
We can reopen this if the issue re-occurs.

**Comment by raniangamuthu** [comment]
Steps to reproduce > execute search > search result page > browser refresh

**Comment by kilam005** [comment]
@ClementJosh21 / @prabhakaranUI 
please check and confirm if above steps (indicated by Rani) help recreate the issue

**Comment by prabhakaranUI** [comment]
Issue not reproduced. @selvakumarchandran pls confirm this with @raniangamuthu in effectv region

**Comment by kilam005** [comment]
@raniangamuthu 
the issue is not reproducible even after following the step you provide.
Request you to close the issue for now.
We can reopen this if the issue re-occurs.

**Comment by raniangamuthu** [comment]
this issue is reproducible and demonstrated the issue to Selva and Maheswara

**Comment by kilam005** [comment]
@selvakumarchandran give necessary details.
I cannot be going back and forth on this.

@raniangamuthu or @selvakumarchandran  
if you have details elaborate it or record and give a video.

**Comment by kilam005** [comment]
This issue will be on hold till the necessry details are available on this tracker

**Comment by prabhakaranUI** [comment]
`RCA`
  Search input cleared while the user refresh the page. so the payload was sent as an empty.

`Fix'
  If the user refresh the page, gets the payload information from the browser state.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/ad82eea9-f20e-4607-a4a6-41f919a77959)

**Comment by Udhayanila8** [comment]
Performing a search using payload after refreshing the page the payload will not change.
Tested in 146 region.
Version: 2024.02.45353_RC8
[screen-capture (6).webm](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/5f7c1a43-3b4a-4b81-907d-16f81bd15148)

**Comment by kilam005** [comment]
Fix is ready. Planned to be relesed in the upcoming version

**Comment by Udhayanila8** [comment]
Tested in 218 server. attaching screen recording for reference
Version: 2024.03.45414_P1

[screen-capture (17).webm](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/96011ea1-15a2-45e9-81c3-a4bcab4d22c0)

**Comment by kilam005** [comment]
Fix has been verifed and the feature will be rolled out durig month end release.

**Comment by maheswarareddyi** [comment]
@raniangamuthu This fix is available in ADS v2024.09.45542 on the 218 server in Chennai DC.
Please check and confirm the working and provide closure to this fix.

**Comment by maheswarareddyi** [comment]
@raniangamuthu  Could you please provide the verification status of this fix? If no update is received from your end by October 21, 2024, the fix will be marked as closed.

**Comment by raniangamuthu** [comment]
verified
