### ISSUE TITLE
ADS-Search - Background Search-elapsed time display not clear (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#87]
When the search is taken to background the time taken to execute is not clear, pls explain
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/d8f82024-029c-43e7-897c-9b1577e78521) 
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/c22e1ce7-0333-4a16-b046-a2d0f50c1fbb)

**Comment by kilam005** [comment]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/d5f2a47b-9f3e-4f64-a6e5-3b5380013d44)

the job was scheduled at 2-20-2024 8:56:43
the job was picked up (started time) 2-20-2024 8:56:48
the job processing ended (end time) 2-20-2024 8:59:11

The elapsed time is end time - start time = 2 min 11 sec


![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/0f491315-2568-43e8-ab4c-1781b3d569cc)
the time taken to fetch the infrom on UI in 30ms

**Comment by kilam005** [comment]
@raniangamuthu hope the above comment answers

**Comment by raniangamuthu** [comment]
ok understood, thanks Malik

**Comment by kilam005** [comment]
if its clear, please close the issue

**Comment by kilam005** [comment]
`Fix details`
Reqruied info provided
