### ISSUE TITLE
ADS-Search criteria in breadcrumb is different (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#88]
Steps to Create:
Execute a search with 2 search criteria CompanyID and PostDate > Takes to background
Execute a search with 3 citieria to narrow down CompanyID, PostDate,Customer > Search result is displayed
Open the completed job in background > View Search Results > in the breadcrumb 3 criteria displayed instead of 2
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/9e0fa899-7855-44c5-a95e-c0e190a3288c)

**Comment by kilam005** [comment]
@Udhayanila8 please check this issue and try to get the actual scenerio demoable.

**Comment by kilam005** [comment]
`RCA` 
Previous search criteria were not cleared while opening a background search result

`Fix details`
Code correction added to clear and update details

**Comment by raniangamuthu** [comment]
Verified and working as expected
