### ISSUE TITLE
Unable to view content loaded into table

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#9]
Environment - Pulte New Dev ADS 3.1.7

https://archon-datastore.platform3solutions.com/pulte/dev/login

App : Recruiting Management
Search : Test_Assign

Unable to view Blob content ingested into Table. On Click of Content icon(ATTACHMENT_RESUME) throw error.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/42184278/4a67c6fc-f624-4383-bc70-ebe47c16d8d0)

**Comment by kilam005** [comment]
Folder Permission was missed durings setup.
It has been provided now.

Please recheck

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/93300845-fb50-4d98-86ce-3978f637dab9)

**Comment by harsha-kotha** [comment]
How can we prevent this happening?
Please add this to product manual

**Comment by harsha-kotha** [comment]
Needs proper documentation to avoid same issue in future.
