### ISSUE TITLE
ADS-Search - Date format preference at search form level (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#90]
Currently we have the date format display as per the setting at the user preference level, but we need to have it at the search form level as in Info archive.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/5929c381-6539-49d3-915b-879a0f68bbbe)

**Comment by kilam005** [comment]
@ClementJosh21  / @prabhakaranUI 
Thilak and suriya have already worked on this fix. This should be taken up and checked from development, testing presepective.
Please ensure export, import also works in accordance to the feature request.

⚠️ I'm unable to tag Thilak and Suriya to this.

**Comment by Udhayanila8** [comment]
Tested in 137 server.
Server: 192.168.56.136:4081
**Short date and medium date**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/8d507cbe-c4b4-4cbe-ab5c-581a4a2dcddf)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/a1d493e6-8e5d-4eef-814a-438566f2295d)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f53e25db-ffd7-4f41-bb35-30dc553d9e40)
**Long date and full date**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/277c11df-a04d-4d5e-bf4a-59c152b341a3)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/33b36779-15a8-4f7d-86f2-b00b4b586732)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/df2e37c0-fb6b-442f-be52-74f31ef37f10)
**For custom format**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/66cc505b-a1db-4129-98fa-16619c8d1864)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/801531f5-57a2-48df-a311-fd4f02072c47)
Also giving the default sorting option
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/0bc48a4a-eb83-4b8e-a4ee-c4c71682c620)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f1320ecc-0e66-4016-aefa-9503cb51fee7)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/fbd132f0-81c1-4e86-a268-ac260a6cd38e)

**Comment by prabhakaranUI** [comment]
Tested on effectv region
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/dc0509dc-1968-44a9-93a4-b656f5c6ab4f)
<img width="1206" alt="image" src="https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/18c4c80a-fab3-4193-b3fa-fb2c0a6d983e">

**Comment by kilam005** [comment]
@raniangamuthu 
Please check above and test in effectv region and provide closure

**Comment by kilam005** [comment]
`Fix details`
Feature enhancment was added in line with IA references as discussed and accepted between @raniangamuthu  and myself (@kilam005)

Both date format and sorting order setting feature are provided

**Comment by raniangamuthu** [comment]
Testing in progress

**Comment by kilam005** [comment]
@raniangamuthu 
has the testing been completed?
Can you provide comments or closure

**Comment by raniangamuthu** [comment]
Verified
