### ISSUE TITLE
ADS-Search - Form Date Range fields logging (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#91]
Not consistent when we skip from date or to date in the date range field. Please ref to the audit log attached below:

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/b9a391d9-6056-4c5c-843a-da282f92ea1b)

**Comment by kilam005** [comment]
@ClementJosh21 & @prabhakaranUI please track this and assign this to the necessry people and get this fixed asap.
This is related to logs and may have impact if left unattended for long.

**Comment by prabhakaranUI** [comment]
_RCA_:
While performing search, We got an empty string when users removed 'From' or 'To date' manually and got an 'Invalid date' string when users didn't selecting 'From date' or 'To date'.

_Fix Details_:
When users removed manually or didn't selecting 'From' or 'To date', FE only passed an empty string to BE. 

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/271773d2-7d98-4bb2-a31c-9949293836e1)

**Comment by kilam005** [comment]
@prabhakaranUI once this is deployed pass this to @Udhayanila8 for testing and confirming this

**Comment by raniangamuthu** [comment]
Verified and working as expected
