### ISSUE TITLE
ADS-Search - sorting not proper for null values (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#92]
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/8847f79d-0c4c-497b-81ab-428ed1fb04b6)

**Comment by kilam005** [comment]
@raniangamuthu please let me know the details. With the image alone, i'm unable to understand the problem here.

**Comment by raniangamuthu** [comment]
If there are null values for any column the sorting when it is done in ascending order it should be listed on the top which is not working like that, this applies to any data type column like string, date etc.,

**Comment by kilam005** [comment]
@ashoksri0 and team please check on this

**Comment by kilam005** [comment]
@raniangamuthu 
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/159db8e1-3c6b-46f2-80bc-faf5821132c6)

This is sort behaviour in Excel and we employ the same strategy.
null has no value to include for positioning it up or down based on sort order.

**Comment by kilam005** [comment]
Please check and reflect on the above comment.
This is not an issue.

**Comment by raniangamuthu** [comment]
Expectation to work as in legacy
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/967d15f8-73b1-4e82-a6ee-26a6a44448df)

**Comment by kilam005** [comment]
Replace null with space and it will get arranaged as you show.
try use [coalesce function](https://trino.io/docs/current/functions/conditional.html#coalesce)

**Comment by kilam005** [comment]
@raniangamuthu,

Fix for this was provide in the last release `ADS v2010.01.45313_P1`
Please check and confirm the working and provide closure to the issue

**Comment by kilam005** [comment]
`RCA` 
No specific coding configuration was added on how to treat null or missing values. So it operated on the default mode of keeping null at the end

`Fix details`
Code modifcation were added to set missing values be put at top if sort is ascending and move it to the last when sorted in descending
