### ISSUE TITLE
ADS-Search - MAS500 RESULTS - Advanced Filter for decimal type result columns - Effectv/Dell

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#93]
Not able to enter the decimal value for the decimal data type result column in the search results filter page.

---

**To reproduce**
Execute Search >> Displays Search Results >> Advanced Filter >> Add Decimal data type column like Amount - no option to enter the decimal value.
---

**Screenshots**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/3789eb15-e361-4346-9131-b012fdb4032f)

---

Additional context
Build no : ADS v2024.01.45313
Client : Effectv

**Comment by kilam005** [comment]
Fix has been made in the informed area.
Regression check is being done to validate if there is a need to so similar fix in other places.

**Comment by kilam005** [comment]
`RCA`
All number, decimal, double, float, integer fields were configured to take input from a number only accepting text field.

`Fix details`
Correction was made to support and provide the text fields to accept inputs correctly based on the field type.

**Comment by prabhakaranUI** [comment]
Search advanced filter
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/ab5ddfb1-84a6-4f17-b85e-a29ec47816f8)

Job management
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/ecec9d1c-ebf3-4460-9cfb-85abe517e72c)

Adhoc search
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/a6d1ba9c-1958-4b17-8608-2ce53261b0cd)

**Comment by prabhakaranUI** [comment]
Tested in Effectv region
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/041f7a47-01a2-4cc6-bb33-c843ea5d0be3)

**Comment by kilam005** [comment]
@raniangamuthu 
please check above comments.
Verify and provide closure.

**Comment by raniangamuthu** [comment]
Verified at effecTV and working as expected
