### ISSUE TITLE
ADS-Search in background - Suggestion on the popup display- Effectv/Dell

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#94]
Bug/Suggestion
When trying to cancel the background job, it is understandable that the cancellation is not possible while the job is running or completed, but the response should not be red error alert kind. Suggestion to display as a message and not like an Error.

Search Form >> Execute search in background >> try to cancel the background job.
---

**Screenshots**
![Screenshot 2024-03-05 084640](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/65d5b9af-f07c-4cd1-adb2-ff55b6b85170)

---

Additional context
Build no: ADS v2024.01.45313
Client: Effectv

**Comment by kilam005** [comment]
@raniangamuthu 
how do you think it has to be treated?

Suggestion:
We can change the text "Error" and make it as NOTE or somthing similar.
Red color is used to ensure attention.
I can make this as a pop-up with warning or info.

Please provide info to proceed

**Comment by raniangamuthu** [comment]
The background request cannot be deleted as it has been processed/completed can be a message instead of error.
Below is the message from infoarchive for reference
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/bbaf5c32-f07e-45ea-b02b-71392cb7031c)

**Comment by kilam005** [comment]
@prabhakaranUI / @ClementJosh21 
please proceed accordingly to the comments above.

@maheswarareddyi please check and help

**Comment by maheswarareddyi** [comment]
@kilam005 @prabhakaranUI @ClementJosh21

Recommended solution for this issue fix:
- We shouldn't allow the users to perform an action that is not supposed to be done concerning the current job status (Display the icon in disabled mode on the UI screen)
- For the rest API service we can use the following message "The requested action cannot be processed because the job "<job name>" is currently in the status "<status>" ".

**Comment by ShaliniSettu** [comment]
RCA:- Technical issue. We will use different api's to kill or cancel the jobs according to that specific jobs status. This issue occurs when the user tries to kill the job that is in the state of scheduled when they triggered but when it reaches BE that job's status were update to in-progress, so that's why this issue has occurred.
Fix:- fixed this issue with inter calling api  to kill that job according to their status.

**Comment by kilam005** [comment]
@ClementJosh21 / @ShaliniSettu :
in which version will this be out? or is this already out?

**Comment by kilam005** [comment]
@Udhayanila8 were you able to test it?

**Comment by Udhayanila8** [comment]
Able to cancel and stop the job while it is schedule and in-progress status.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/c1169cb1-1345-4128-b055-8e04eb98dbc9)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/bbd26de4-5b6e-4319-a893-85755f508f1b)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/ff9c4b73-9c35-4eff-9d64-6b8b9b336964)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/9690db01-16c1-4a98-bc56-af115189376f)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/e988960c-c53f-4e63-a9d3-3d1d15933f10)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/a9fce175-cc78-407f-b3af-30bbacd8165d)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/5c409afa-3da6-4f5d-ae17-fa0ce2f3f319)

**Comment by kilam005** [comment]
@Udhayanila8 please recheck this and if everything is working as expected update the Verified tag and add Awaiting Closure and move to Rani for verification and closure

**Comment by Udhayanila8** [comment]
Verified 2024.05.45423_RC1 version.
Tested in 146 server. Hence moving this issue to rani.
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/223734fc-bbf7-4c64-8c5a-5352152d6c5d)
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/9b39b317-fbc6-4304-a918-357f383a4c78)
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/3e447cff-604d-4129-97ce-1e4c3141d58b)
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/cd9dfe1d-d789-4e29-a09d-8ddc29078efb)
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/8a01ebf7-f3b4-4ad1-86f8-f3bb7f1bd6a1)
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/884d64cb-b754-4769-9f87-6a8b8e0fba6f)

**Comment by kilam005** [comment]
Based on last comment marking as verified

**Comment by kilam005** [comment]
@raniangamuthu this is waiting for closure since May 15th.
Please verify and provide closure soon.

based on testing team's confirmation, i will have to auto close this is no action is taken from your side by Jun 7th

**Comment by kilam005** [comment]
@raniangamuthu since there is no response and no concerns raised. this issue is marked closed.
