### ISSUE TITLE
ADS-Search - Add Advanced Filter - filter empty values - Effectv/Dell

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#96]
**Describe the bug**
Need an option to filter null or empty data in string column.
Also, the message is not proper.

---

**To reproduce**

Steps to reproduce the behavior :
Execute Search >> Search Results >> Add Advanced Filter - filter to get the list of any column with null values so tried space.

---

**Screenshots**

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/e83c0fd1-ae9e-41e3-94f3-736d5f70c3d2)

---

Additional context
Build no : ADS latest version in effecTV
Client : Effectv

**Comment by kilam005** [comment]
@prabhakaranUI / @VikramSelvadurai / @dinesh-p3 
Need to add Is Empty and Not Is empty check function for String type columns
Also check and Is Null and Not Is Null check function for String, Date type columns

**Comment by kilam005** [comment]
@raniangamuthu 
please validate the above comment and confirm it

**Comment by selvakumarchandran** [comment]
Wrongly closed Please check and close

**Comment by prabhakaranUI** [comment]
Fixes deployed and tested in effectv region
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/4c466916-2288-4c72-8edd-61eec25948d8)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/34186578/3e21ef68-1a77-4ce8-8052-573fe5f7ea47)

**Comment by kilam005** [comment]
@raniangamuthu 
please check and provide closure

**Comment by raniangamuthu** [comment]
verified
