### ISSUE TITLE
ADS-Audit - export with filter applied and exported the report as html - Effectv/Dell

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#97]
Report not generated

---

**To reproduce**
System Management >> Audit >> Add Filters>Export as html

---

**Screenshots**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/45530a71-4351-4b70-8e49-c9c8c6133445)

---

Additional context
Build no : ADS v
Client : Effectv

**Comment by kilam005** [comment]
unzip the file and then open the index.html
The files seems to be open from temp path with only unzipping the single file.

**Comment by kilam005** [comment]
@raniangamuthu 
please check again by unzipping the contents of the audit report first and then open the index.html

**Comment by raniangamuthu** [comment]
Verified
