### ISSUE TITLE
ADS-Search Form- previously entered Date values missing when edited - Effectv/Dell

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#99]
**Describe the bug**
When there is a date range entered and execute the search and after seeing the results we edit the search form to enter different input and during this process the previously entered data in date range is missing

---

**To reproduce**
Search form - fill in date range > Execute Search > Edit the criteria

---

**Screenshots**

---

Additional context
Build no : ADS latest version
Client : Effectv

**Comment by kilam005** [comment]
@raniangamuthu 
Please provide more clarity

**Comment by kilam005** [comment]
@raniangamuthu 
this issue need clarity and we are unable to proceed. Please update or clode this issue.
If no updates are avaialble i'll have to force close on 15th May.

**Comment by raniangamuthu** [comment]
Tested in pulte version and looks like it is fixed and hence closing this issue
